{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}小型张“澳门中国古典诗词－木兰辞”（ 600018）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<span style="color:#696969;"><strong>小型张&ldquo;澳门中国古典诗词－木兰辞&rdquo;（ 600018）</strong></span><br />
														交易参数：<br />
														【交易代码】：600018<br />
														【首日挂牌指导价】：16元/张<br />
														【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：60000张<br />
														【最小变动价位】： 0.01元<br />
														【最小提货数量】: 1张<br />
														【市场流通量】：60000张<br />
														【备注】：&nbsp;以整枚自提<br />
														<br />
														藏品信息：<br />
														【藏品名称】：澳门中国古典诗词－木兰辞<br />
														【藏品类别】：中国古典诗词邮票<br />
														【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
														【规 &nbsp; &nbsp; &nbsp; 格】：138mm&times;90mm<br />
														【齿孔度数】：13&frac14; x 13&frac14;<br />
														【版 &nbsp; &nbsp; &nbsp; 别】：照相凹版印刷术<br />
														【防伪方式】：法国防伪纤维纸<br />
														【设 计 &nbsp;者】：潘锦玲<br />
														【发行机构】：澳门特别行政区邮政<br />
														<br />
														藏品介绍：<br />
														《木兰辞》是中国南北朝时期（公元420年--公元589年）流传于北方的一首长篇叙事民歌，是北朝乐府民歌的代表作。在中国文学史上它和《孔雀东南飞》并称为&ldquo;乐府民歌双璧&rdquo;。&ldquo;乐府&rdquo;是古代掌管音乐的官署。&ldquo;乐府民歌&rdquo;是指&ldquo;乐府&rdquo;所采集的来自民间的歌谣。<br />
														《木兰辞》也称为《木兰诗》，通过叙述木兰女扮男装代父从军的故事，塑造了木兰这一光辉的女英雄形象。它是民间的集体创作，在长期流传的过程中，可能经过文人的加工、润色，但仍保持着民歌特具的风貌。<br />
														&nbsp;邮政局此次发行以《中国古典诗词---木兰辞》为题材的邮品，分为四枚邮票和一枚小型张。<br />
														木兰辞（小型张）：《木兰辞》塑造的英姿飒爽的巾帼英雄木兰的事迹千古流传，历代文人不断传承并润色，出现了诗歌、戏剧等不同的文学样式。《木兰辞》最早见于南朝陈时的僧人 智匠所撰的《古今乐录》，但他声称&ldquo;木兰不知名&rdquo;，显见他是把&ldquo;木兰&rdquo;视为姓氏了。但南北朝时的数学家祖冲之《述异记》中提到木兰姓花。明代文学家徐渭将《木兰辞》改编为《雌木兰替父从军》，剧中自称&ldquo;妾身姓花名木兰&rdquo;，&ldquo;世住河北魏郡。俺父亲名弧字桑之。&rdquo;此后，花木兰之名蜚声中华，远播海内外。<br />
														风险分析：<br />
														各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
