{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}充满时代特征的马雅可夫斯基、莱蒙托夫邮票{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-28 23:27:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	马雅可夫斯基（1893-1930年），前苏联著名的无产阶级诗人。他所发明的阶梯诗，被誉为无产阶级革命的冲锋号。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	马雅可夫斯基诞生于前苏联格鲁吉亚共和国，从小在父母的熏陶下喜爱文学，在中学时代便开始创作诗歌。他一生大约创作了1300多首短诗、14首长诗、3部剧本、12部电影剧本。代表作有《向左进行曲》、《一亿五千万》、《开会谜》；长诗《列宁》、《好》、《穿裤子的云》、《放开嗓子歌唱》等。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	自1930年4月14日马雅可夫斯基因为失去领袖和布尔什维克的信任，遭受外界诽谤及个人感情生活受挫而自杀以后，前苏联多次发行纪念他的邮票。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	设计马雅可夫斯基邮票的是前苏联著名画家伊万&middot;杜巴索夫。1922年，杜马索夫刚从红军复员，便参加了庆祝十月革命5周年邮票优秀图案的竞赛，获一等奖。杜氏从此担任邮票的设计绘画工作，以设计无产阶级领袖邮票而闻名，如纪念列宁、高尔基等人的邮票均出自其手。杜巴索夫设计的马雅可夫斯基邮票：一是显示了强烈的时代性，二是构思慎密、简练、色彩鲜明，将粗犷美与艺术美融为一体。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1953年，前苏联邮电部发行了一枚马雅可夫斯基诞生60周年纪念邮票（见图一）。设计者以西洋油画的手法，十分扼要地突出主题：马雅可夫斯基作为无产阶级诗人，是在布尔什维克党的指引下成长起来的。图案正面是马雅可夫斯基的标准肖像，背景是象征苏维埃革命的红旗、红旗正在迎风飘扬，意为诗人为之奋斗的事业仍在前进。图案上方是1953年斯大林在《真理报》上发表的谈话：&ldquo;马雅可夫斯基过去是，现在仍然是我们苏维埃时代最优秀、最杰出的诗人。&rdquo;下方文字为纪念伟大的苏联诗人马雅可夫斯基诞生60周年。<br />
	&nbsp;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GK33P-1b32.jpg" style="width: 163px; height: 198px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	▲ 图一</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	图二所展示的邮票发行于1955年，图案下面为诗人肖像，背景是印着镰刀斧头的前苏联国旗。在无数红旗的簇拥下，推出诗人的长诗《好》的结尾部分：&ldquo;我赞美/祖国的/现在，/但三倍地赞美/祖国的将来。&rdquo;<br />
	&nbsp;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GK39630-23501.jpg" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	▲ 图二</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1943年，前苏联发行了两枚一套的马雅可夫斯基诞生50周年纪念邮票（图三、五）。当时，第二次世界大战、特别是苏联的卫国战争正处在转折关头，设计者将马雅可夫斯基在十月革命胜利后、14个帝国主义国家武装干涉苏维埃时所写的政治鼓动诗，《向左进行曲》中描绘红军的一段，放在图案左上方：&ldquo;世界上没有一样东西/比合金还要硬/红军是我们的力量/光荣属于我们的红军！&rdquo;右上方为诗人的肖像，仿佛他正在向红军朗诵诗作。图案下方是苏联红军的飞机和坦克。从构图的红、蓝色调看，显得非常庄严和气势恢宏，让人产生一股铁流向前、无坚不摧的力量。这套邮票当时鼓舞了千百万抗击德国法西斯的红军和苏联人民，如今很难觅到它们。<br />
	&nbsp;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GK43250-33018.jpg" style="width: 151px; height: 212px;" /><br />
	&nbsp;</p>
<div r="1" style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GL46020-4I43.jpg" style="width: 150px; height: 213px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GK33P-1b32_lit.jpg{/dede:field}
