<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","首届“邮币卡”电子盘峰会举行",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",212,262);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-25 01:48:00 &nbsp",264,329);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	本报讯 记者杨开新报道：中国首届&ldquo;邮币卡&rdquo;电子盘创新发展与社会责任峰会日前在北京举行。峰会由人民日报社《民生周刊》杂志社主办、北京福丽特玩家邮币卡市场有限公司承办，数百名与会者围绕管控投资风险、加强行业自律、承担社会责任等话题进行了交流。</p>\r\n<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	据介绍，&ldquo;邮币卡&rdquo;是邮票、钱币、电话卡的简称，广受投资理财人士和收藏爱好者的关注，全国年交易额超过1000亿元。相关行业适应移动互联网用户的需求，形成了邮币卡电子交易（俗称&ldquo;邮币卡电子盘&rdquo;）的新型交易模式，促进行业线上线下健康有序发展。</p>",331,1411);
$z[6][4]['name']="body";
$z[7]=Array("field","",1413,1452);
$z[7][4]['name']="litpic";

?>