{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中华人民共和国电子签名法{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<div>
		&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
