{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮票上的水乡古镇{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-30 23:11:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GN44020-93139.jpg" style="width: 500px; height: 243px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="text-indent: 2em;">江南水乡，风光秀美，桑田纵横，河湖似镜。&ldquo;村村皆画图，处处有诗材。&rdquo;尤其是水乡古镇，条条街巷傍水流，户户人家尽枕河。一条条美丽如画的水巷，配以古色古香的石拱桥，恰如一幅幅静物画。偶尔小巧的乌篷船划破平静的水面，从青藤缠绕的桥洞中穿过，马上就给画面注入了神韵和活力。上桥下桥，步移景换，令人目不暇接。再加上粉墙竹影、古树苍藤的映衬，更浓化了江南水乡使人神往遐想的诱人风光。为从艺术角度展现江南水乡，中国邮政曾于2001年4月7日发行《水乡古镇》特种邮票6枚，包含江南水乡6个古镇（吴县甪直、昆山周庄、吴江同里、桐乡乌镇、湖州南浔、嘉善西塘）。这套邮票是一位叫黄里的画家绘就的，黑白颜色，浓淡相宜，底色采用鲜艳的红色，使这套邮票显得既古朴典雅又充满了东方神韵。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	由江苏科学技术出版社出版的《中国古建筑之旅&mdash;&mdash;&mdash; 江南水乡古镇》精选全国颇具价值、特色的古镇、古村、古民居、古代建筑群等，以当地的建筑元素为主体，进行功能性、历史性、溯源性解读，深入浅出的解读让大家可以领略建筑背后蕴含的故事。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GN44020-93139_lit.jpg{/dede:field}
