<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","《珍惜矿产资源》等藏品上市的公告",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",218,268);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-04 15:11:16 &nbsp",270,335);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将《普30珍惜矿产资源》、《中国现代科学家》、《普31中国鸟&mdash;绿尾虹雉》藏品在本中心正式发行和上市交易，具体事项公告如下：<br />\r\n<strong>&nbsp;一、&nbsp;上市商品信息</strong></span>\r\n<div style=\"text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OX61230KP-3NZ.jpg\" />",337,935);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX61230KP-3NZ_lit.jpg",937,1023);
$z[7][4]['name']="litpic";

?>