<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《唐伯虎》系列字画藏品托管入库公告",89,184);
$z[2][4]['name']="title";
$z[3]=Array("field","",186,225);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",227,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-11 15:30:00 &nbsp",279,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: justify;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《1999己卯年》特种邮资明信片唐伯虎系列字画选（以下简称&ldquo;唐伯虎&rdquo;）藏品已完成托管入库流程，详情见下表：</span>",346,902);
$z[6][4]['name']="body";
$z[7]=Array("field","",904,943);
$z[7][4]['name']="litpic";

?>