<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","智慧金融—需要精雕细琢的工匠精神",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",218,268);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-07 10:33:00 &nbsp",270,335);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">喜欢不断雕琢自己的产品，不断改善自己的工艺，享受着产品在双手中升华的过程。工匠们对细节有很高要求，追求完美和极致，对精品有着执着的坚持和追求，把品质从99%提高到99.99%，其利虽微，却长久造福于世。</span>",337,864);
$z[6][4]['name']="body";
$z[7]=Array("field","",866,905);
$z[7][4]['name']="litpic";

?>