<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","藏品介绍—《西游记》（一）（T)小型张特种邮票",89,192);
$z[2][4]['name']="title";
$z[3]=Array("field","",194,233);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",235,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-06-15 15:15:00 &nbsp",287,352);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div class=\"fgx\" style=\"padding: 0px; margin: 0px; clear: both; height: 8px; line-height: 8px; color: rgb(51, 51, 51); font-family: arial, 宋体, sans-serif; text-indent: 28px;\">\r\n	&nbsp;",354,579);
$z[6][4]['name']="body";
$z[7]=Array("field","",581,620);
$z[7][4]['name']="litpic";

?>