{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}藏品介绍—《西游记》（一）（T)小型张特种邮票{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-15 15:15:00 &nbsp{/dede:field}
{dede:field name='body'}<div class="fgx" style="padding: 0px; margin: 0px; clear: both; height: 8px; line-height: 8px; color: rgb(51, 51, 51); font-family: arial, 宋体, sans-serif; text-indent: 28px;">
	&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
