{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}热烈庆祝西邮所首届战略投资人战略研讨会圆满{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-05 10:17:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">2016年8月3日，西邮所主办的首届战略投资人战略研讨会在宁夏总部召开。来自全国各地的战略投资人代表云集宁夏银川。大会总结了2016年上半年市场发展情况，对优秀战略投资人进行了表彰颁奖，并对下半年市场发展规划、策略进行了认真、深入的探讨，参会代表各抒己见，会议讨论氛围热烈。本次大会中市场也拿出百万优惠对各战略投资人的合作支持进行答谢。</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OY05R62220-1I13.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 500px; height: 295px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OY05R62220-1I13_lit.jpg{/dede:field}
