{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“邮票上的中山”邮展20日举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-31 23:18:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">记者从市邮政获悉，为纪念中国邮政开办120周年，本月起，中山邮政将在东区集邮旗舰店举办&ldquo;亮丽伊人节&rdquo;、&ldquo;邮票上的中山&rdquo;等集邮文化活动，3月20日当天，发行《中国邮政开办一百二十周年》纪念邮票1套4枚，有兴趣的市民可到全市各邮政网点咨询。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-size: 16px; text-indent: 2em; font-family: 宋体, arial; line-height: 25px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-size: 16px; text-indent: 2em; font-family: 宋体, arial; line-height: 25px;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp;&nbsp;&nbsp;&nbsp;据了解，3月5日至3月8日举办的&ldquo;亮丽伊人节&rdquo;，包括&ldquo;三月霓裳&rdquo;专题集邮展览、&ldquo;果色添色&rdquo;进口水果免费品尝等，前往现场的女士有机会以面值价提前预订《中国邮政开办一百二十周年》邮票套票。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-size: 16px; text-indent: 2em; font-family: 宋体, arial; line-height: 25px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-size: 16px; text-indent: 2em; font-family: 宋体, arial; line-height: 25px;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp;&nbsp;&nbsp;&nbsp;3月20日，我市邮政各网点将同步首发《中国邮政开办一百二十周年》纪念邮票，期间将举办&ldquo;邮票上的中山&rdquo;邮展，展览内容为近20年来中山邮政为全市各行业发行的个性化纪念邮票近100套，通过邮票展现中山的独特魅力。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
