{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z001防止大气污染藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-04 12:52:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年7月1日对挂牌藏品《保护人类共有的家园》&mdash;防止大气污染普通邮票（以下简称&ldquo;防止大气污染&rdquo;）面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<img alt="" src="/uploads/allimg/c161123/14OXM0941020-32126.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 668px; height: 244px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM0941020-32126_lit.jpg{/dede:field}
