<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016Z001防止大气污染藏品申购中签公告",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",220,270);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-04 12:52:00 &nbsp",272,337);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年7月1日对挂牌藏品《保护人类共有的家园》&mdash;防止大气污染普通邮票（以下简称&ldquo;防止大气污染&rdquo;）面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OXM0941020-32126.jpg\" style=\"padding: 0px; margin: 10px; border: none; max-width: 700px; width: 668px; height: 244px;\" />",339,1195);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXM0941020-32126_lit.jpg",1197,1286);
$z[7][4]['name']="litpic";

?>