{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《映日荷花》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-19 16:18:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将邮资明信片&nbsp;&ldquo;映日荷花&rdquo;（以下简称&ldquo;映日荷花&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：</span><br />
<strong style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">一、&nbsp;上市商品信息</strong>
<div style="text-align: center;">
	<strong style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;"><img alt="" src="/uploads/allimg/c161123/14OXM0596220-34493.jpg" style="width: 579px; height: 493px;" /></strong>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM0596220-34493_lit.jpg{/dede:field}
