<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","《映日荷花》藏品上市的公告",89,166);
$z[2][4]['name']="title";
$z[3]=Array("field","",168,207);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",209,259);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-19 16:18:00 &nbsp",261,326);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将邮资明信片&nbsp;&ldquo;映日荷花&rdquo;（以下简称&ldquo;映日荷花&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：</span><br />\r\n<strong style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">一、&nbsp;上市商品信息</strong>\r\n<div style=\"text-align: center;\">\r\n	<strong style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\"><img alt=\"\" src=\"/uploads/allimg/c161123/14OXM0596220-34493.jpg\" style=\"width: 579px; height: 493px;\" /></strong>",328,1363);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXM0596220-34493_lit.jpg",1365,1454);
$z[7][4]['name']="litpic";

?>