<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","邮币卡电子盘迎战国时代(图)",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",208,258);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-24 17:27:00 &nbsp",260,325);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div align=\"left\" style=\"padding: 0px; margin: 0px; font-size: 16px; text-indent: 28px; color: rgb(37, 37, 37); font-family: 宋体, sans-serif; line-height: 28px;\">\r\n	<div style=\"text-align: center;\">\r\n		<img alt=\"\" src=\"/uploads/allimg/c161124/14O95J4910U0-140H.jpg\" style=\"width: 550px; height: 379px;\" /><br />\r\n		<span style=\"color: rgb(102, 102, 102); font-family: 微软雅黑, 宋体; line-height: 32px;\">在青岛一家邮币卡交易大厅内，工作人员在研判走势。</span>",327,856);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95J4910U0-140H_lit.jpg",858,946);
$z[7][4]['name']="litpic";

?>