{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮币卡电子盘迎战国时代(图){/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 17:27:00 &nbsp{/dede:field}
{dede:field name='body'}<div align="left" style="padding: 0px; margin: 0px; font-size: 16px; text-indent: 28px; color: rgb(37, 37, 37); font-family: 宋体, sans-serif; line-height: 28px;">
	<div style="text-align: center;">
		<img alt="" src="/uploads/allimg/c161124/14O95J4910U0-140H.jpg" style="width: 550px; height: 379px;" /><br />
		<span style="color: rgb(102, 102, 102); font-family: 微软雅黑, 宋体; line-height: 32px;">在青岛一家邮币卡交易大厅内，工作人员在研判走势。</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95J4910U0-140H_lit.jpg{/dede:field}
