{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于防止大气污染普通邮票藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-30 01:30:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2002壬午年》普通邮票《保护人类共有的家园》&mdash;防止大气污染（以下简称&ldquo;防止大气污染&rdquo;）藏品已完成托管入库流程，详情见下表：</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O9553PMH0-2cM.jpg" style="width: 658px; height: 198px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O9553PMH0-2cM_lit.jpg{/dede:field}
