<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","1992-9T《三国演义》(第三组)藏品托管入库",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",224,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-26 18:57:00 &nbsp",276,341);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div>\r\n	<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《三国演义》（第三组）1992-9T（以下简称&ldquo;三国演义&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n	<div style=\"text-align: center;\">\r\n		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt=\"\" src=\"/uploads/allimg/c161124/14O955419D20-34Z6.jpg\" style=\"width: 634px; height: 157px;\" /></span>",343,1154);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O955419D20-34Z6_lit.jpg",1156,1244);
$z[7][4]['name']="litpic";

?>