{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}1992-9T《三国演义》(第三组)藏品托管入库{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-26 18:57:00 &nbsp{/dede:field}
{dede:field name='body'}<div>
	<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《三国演义》（第三组）1992-9T（以下简称&ldquo;三国演义&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
	<div style="text-align: center;">
		<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161124/14O955419D20-34Z6.jpg" style="width: 634px; height: 157px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O955419D20-34Z6_lit.jpg{/dede:field}
