<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","嘘，新兴市场的大军来啦",89,160);
$z[2][4]['name']="title";
$z[3]=Array("field","",162,201);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",203,253);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-07 10:00:00 &nbsp",255,320);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">在收藏领域，邮币卡一直是一个较大的板块，随着时代的发展，邮币卡承载的使用功能在慢慢褪去，更多被赋予了艺术鉴赏价值及收藏价值，而且邮币卡的价格随着年代越久远越高，有着显而易见的增值价值。例如 猴票、祖国山河一片红、袁大头等，这些邮票、钱币目前市场上单个售价已经突破百万元大关，邮币卡投资的高回报让更多的投资者想要踏足此领域。</span>",322,1045);
$z[6][4]['name']="body";
$z[7]=Array("field","",1047,1086);
$z[7][4]['name']="litpic";

?>