{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}嘘，新兴市场的大军来啦{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-07 10:00:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">在收藏领域，邮币卡一直是一个较大的板块，随着时代的发展，邮币卡承载的使用功能在慢慢褪去，更多被赋予了艺术鉴赏价值及收藏价值，而且邮币卡的价格随着年代越久远越高，有着显而易见的增值价值。例如 猴票、祖国山河一片红、袁大头等，这些邮票、钱币目前市场上单个售价已经突破百万元大关，邮币卡投资的高回报让更多的投资者想要踏足此领域。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
