{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D022号《澳门中国书法》藏品的停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-10 15:31:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61O964P-2T29.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 594px; height: 105px;" /><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 自2016年10月11日09时30分起，挂牌藏品《澳门中国书法小版票》暂停交易一天，于2016年10月12日09时30分起恢复交易。&nbsp;<br style="padding: 0px; margin: 0px;" />
										&nbsp;<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 特此公告！</span>
										<div style="padding: 0px; margin: 0px; text-align: right;">
											<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
											二零一六年十月十日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61O964P-2T29_lit.jpg{/dede:field}
