{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}小型张“香港经典邮票系列第十辑”（ 600023）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<span style="color:#696969;"><strong>小型张&ldquo;香港经典邮票系列第十辑&rdquo;（ 600023）</strong></span><br />
														交易参数：<br />
														【交易代码】：600023<br />
														【首日挂牌指导价】：10元/张<br />
														【涨跌幅度】:&nbsp;&plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：150000张<br />
														【最小变动价位】：&nbsp;0.01元<br />
														【最小提货数量】:&nbsp;500张<br />
														【市场流通量】：150000张<br />
														&nbsp;<br />
														藏品信息：<br />
														【藏品名称】：香港经典邮票系列第十辑<br />
														【图案面值】&nbsp;：5.00元(港币）<br />
														【发行日期】：1997年6月30日<br />
														【全套枚数】：1枚<br />
														【材 &nbsp; &nbsp; &nbsp; 质】&nbsp;:&nbsp;纸质<br />
														【邮票规格】：130mm&times;78mm<br />
														【齿孔度数】：14.4度<br />
														【版 &nbsp; &nbsp; &nbsp; 别】：照相凹版印刷术<br />
														【设&nbsp;计 &nbsp;者】：林炳培<br />
														&nbsp;<br />
														&nbsp;藏品介绍：<br />
														&nbsp; &nbsp; &nbsp; &nbsp; 一八六二年十二月八日至一九九七年六月三十日发行的通用邮票精选&rdquo;于6月30日发行。其中邮票选用1991年8月25日发行的&ldquo;香港邮政署一百五十周年纪念&rdquo;邮票中面值5元的一枚，与该系列第一辑邮票图案相同，面值不同（第一辑为10元）。<br />
														小型张上描绘了四个不同时期的香港邮政总局建筑外观，右侧印有选自七套香港通用邮票中的9枚邮票，有五位英国国王在这些邮票中亮相，他们分别是：维多利亚女王（1862年发行）、爱德化七世（1903年发行）、乔治五世（1912年发行）、乔冶六世（1938年发行）、伊丽莎白二世（1954、1968、1987年发行）。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;该小型张由林炳培设计，其最特别之处是在背面印有说明文字，此举在香港邮票史上尚属首次。由于小型张邮票上皇冠标志，所以它的邮政寿命只有一天，到7月1日就不能使用了。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;这是该系列的最后一枚小型张。邮票图案与第一辑形成首尾响应，反映了一段完整的邮政史。它也是英国管治下的香港发行的最后一套邮票，成为名符其实的&ldquo;关门票&rdquo;邮政寿命仅一天,历史意义不寻常。<br />
														<br />
														风险分析：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
