{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}英国发行猴年金银纪念币 最重达1公斤{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 01:24:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HOTX0-93630.jpg" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	&nbsp; &nbsp; &nbsp; &nbsp;英国发行猴年纪念币</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	为庆祝即将到来的中国农历新年，英国皇家造币厂5日发行系列猴年生肖纪念币。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其中一款最贵的纪念币重1005克，直径为10厘米，是英国皇家造币厂首次发行重达1公斤且直径最大的纪念币。这款纪念币由万足金打造，面值为1000英镑，只发行8枚，每枚建议零售价为4.25万英镑。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	皇家造币厂纪念币部门主管安妮&middot;杰索普说：&ldquo;我们之所以只发行8枚，是因为8在中国文化里意味着财富。&rdquo;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	除了这款超级纯金纪念币外，本套猴年生肖纪念币还包括其他6款大小不一的金、银纪念币，每款纪念币发行数量从8枚到8054枚不等。所有纪念币正面为英国女王伊丽莎白二世的头像，背面为一大一小两只猕猴，大猴旁边刻有一个汉字&ldquo;猴&rdquo;。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	猴年生肖纪念币的设计者是英籍华裔艺术家何文津。此前，皇家造币厂发行的马年、羊年生肖纪念币均由她设计。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	安妮&middot;杰索普说：&ldquo;本套猴年纪念币将英国皇家造币厂千年的铸币工艺和历史悠久的中国文化传统融合在一起。我们知道，中国人过春节的习俗是发红包。因此，我们选取了大红色作为猴年纪念币包装盒的颜色。&rdquo;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	英国皇家造币厂是英国唯一的生产钱币的机构，属财政部管辖。皇家造币厂不仅生产本国钱币，也面向世界60多个国家和地区制作、出口钱币，同时还制作各种奖章，其中包括2012年伦敦奥运会和残奥会的奖牌。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HOTX0-93630_lit.jpg{/dede:field}
