<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","1990年普26邮票“宁夏民居”（600003）",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",218,268);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-06 11:37:00 &nbsp",270,335);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OY05FZ620-13261.jpg\" style=\"padding: 0px; margin: 10px; border: none; max-width: 700px; width: 500px; height: 379px;\" />",337,714);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OY05FZ620-13261_lit.jpg",716,804);
$z[7][4]['name']="litpic";

?>