{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}1990年普26邮票“宁夏民居”（600003）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-06 11:37:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<img alt="" src="/uploads/allimg/c161123/14OY05FZ620-13261.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 500px; height: 379px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OY05FZ620-13261_lit.jpg{/dede:field}
