{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z012《长江三峡》藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-31 10:21:46 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size: 16px"><font size="3">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年10月 29日对挂牌藏品特种邮票长江三峡面向所有投资人会员进行定价申购发行，具体事项公告如下：</font></span><br />
<div style="text-align: center">
	<span style="font-size: 16px"><img alt="" src="/uploads/allimg/c161123/14OX611343D0-11010.png" style="width: 600px; height: 218px" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX611343D0-11010_lit.png{/dede:field}
