{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西邮所“你来打新、我来买单”活动开启{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-30 10:09:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">为推动新藏品上市工作，鼓励更多场外资金进场参与交易，共同创造财富，西邮所将于<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">7月1日至7月31日</span>开启新一轮<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">&ldquo;你来打新、我来买单&rdquo;</span>活动，活动详情请登陆西邮文化艺术品交易中心<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">官方网站（www.81xiyou.com）进行查询</span>。</span>
										<div style="padding: 0px; margin: 0px; text-align: center;">
											<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OY29Cb920-4QR.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 530px; height: 333px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OY29Cb920-4QR_lit.jpg{/dede:field}
