{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}银行回存航天纪念钞{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-27 01:17:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	航天纪念钞发行量颇大，令该类纪念钞升值空间较小。针对有部分储户在兑换到航天钞后又想存入银行的事宜回应，昨日，中国人民银行扬州市中心支行表示，为便于储户存入航天钞，扬州的238个银行网点开设航天钞回笼窗口，办理回笼业务。同时，现场公布了办理回笼业务的238个银行网点名称和地址。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国人民银行扬州市中心支行称，中国航天纪念钞与现行流通人民币职能相同，与同面额人民币等值流通，各单位不得拒收。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	北京商报记者向北京地区的央行营管部人士咨询此事，该人士表示，航天钞是纪念币，也是国家法定货币，可以流通，可以使用，也可以存入银行，所以北京的银行网点也是可以存的。如果银行拒收，客户可以向上级银行反映。需要提醒的是，航天钞和普通人民币不是同一个防伪系统，ATM机不具备航天纪念钞的识别参数，因此市民存款需要到柜台办理。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	纪念钞是为了纪念重大事件而特别发行的钞票。去年11月26日央行发行中国航天普通纪念币、航天纪念钞，这也是新中国成立以来发行的第四套纪念钞。此前，中国人民银行在1999年发行庆祝中华人民共和国成立50周年纪念钞；2000年发行迎接新世纪纪念钞；2008年发行第29届奥林匹克运动会纪念钞。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	由于此前发行的几类纪念钞在钱币收藏市场比较受追捧，因此，各地民众对航天纪念钞兑换热情很高，去年12月，曾出现多家银行出现市民排队兑换航天纪念钞的热闹场景。不过，航天纪念钞发行量与此前的纪念钞相比超出太多，这也大大影响了其升值空间。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
