{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}珍藏：达摩易筋经明信片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-22 00:09:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	少林达摩易筋经</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	少林达摩易筋经是禅宗始祖菩提达摩所创的一种内外兼修的养生功法。&ldquo;易筋经&rdquo;采用调息与静止性用力相结合的修炼方法，能疏通各个经络脏腑，将萎缩松弛的肌肉变为强壮结实的肌肉，长期修炼可以达到保健强身，防病祛病，抵御早衰，延年益寿的目的。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	声明：版权所有，转载请注明出处！<br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH02350-13192.jpg" style="width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH14530-24628.jpg" style="width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH1S10-33396.jpg" style="width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH21030-41I3.jpg" style="width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH491F-5B17.jpg" style="width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH543P-C159.jpg" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HH5S20-IK2.jpg" style="text-align: justify; text-indent: 2em; width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HITC0-W408.jpg" style="text-align: justify; text-indent: 2em; width: 600px; height: 410px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HIX450-93135.jpg" style="width: 600px; height: 410px;" /></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HH02350-13192_lit.jpg{/dede:field}
