<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D033号《宁夏民居》藏品停牌的公告",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",226,276);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-25 16:32:54 &nbsp",278,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:<br />\r\n&nbsp; &nbsp; &nbsp;<img alt=\"\" src=\"/uploads/allimg/c161123/14OX5bX0b0-5T34.jpg\" style=\"width: 640px; height: 116px;\" /><br />\r\n&nbsp; &nbsp; &nbsp;根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年10月26日09时30分起停牌，挂牌藏品《宁夏民居》暂停交易一天，于2016年10月27日9时30分起复牌交易。<br />\r\n&nbsp; &nbsp;<br />\r\n&nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n&nbsp; &nbsp; 特此公告！</span>\r\n<div style=\"text-align: right;\">\r\n	<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心有限公司<br />\r\n	二零一六年十月二十五日</span>",345,1213);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX5bX0b0-5T34_lit.jpg",1215,1301);
$z[7][4]['name']="litpic";

?>