{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普31“中国鸟-褐头凤鹛”（ 600011）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><strong style="padding: 0px; margin: 0px;">普31&ldquo;中国鸟-褐头凤鹛&rdquo;（ 600011）</strong></span><br style="padding: 0px; margin: 0px;" />
															交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：600011<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：5元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															&nbsp;【单笔最大委托量】：200000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 30枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：200000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整版自提<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：普31中国鸟-褐头凤鹛<br style="padding: 0px; margin: 0px;" />
															【藏品分类】：版票<br style="padding: 0px; margin: 0px;" />
															【藏品志号】：普31<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】 : 1.20元<br style="padding: 0px; margin: 0px;" />
															【材 &nbsp; &nbsp; &nbsp;质】 : 纸质<br style="padding: 0px; margin: 0px;" />
															【邮票规格】：27&times;38mm<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：30枚<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2006年11月15日<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：影写<br style="padding: 0px; margin: 0px;" />
															【设 计 &nbsp;者】：黄华强<br style="padding: 0px; margin: 0px;" />
															【发行机构】：中国邮政<br style="padding: 0px; margin: 0px;" />
															【印刷单位】：北京邮票厂<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 为展现中国丰富的鸟类，进一步增强爱鸟护鸟，保护鸟类的意识，中国国家邮政局于2月1日开始新普票系列《中国鸟》的发行。褐头凤鹛邮票是普31中国鸟中的第五组的第二枚，也是全套的最后一枚。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 褐头凤鹛，雀形目、 莺科、凤鹛属，是台湾特有种。常见于海拔 1000&mdash;2800米的温带森林，性合群活泼，藏隐于森林较低层，常加入混合鸟群，不惧生。</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
