{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于“平安银行核心业务系统升级”的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-30 11:51:00 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的会员：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;为了给您提供更优质的服务，平安银行将于2016年10月15日（星期六）至16日（星期日）进行核心业务系统升级。受此次系统升级影响，平安银行营业网点将于15日、16日暂停对外服务，平安银行企业网银、企业手机银行、个人网银、口袋银行、移动支付、电话银行、ATM/POS/CRS/远程视频等渠道将陆续从2016年10月14日（星期五）15：30暂停服务,并计划于2016年10月16日（星期日）18：00陆续恢复对外服务。请您提前做好资金安排，如有疑问，请拨打平安银行24小时客服热线95511-3，或咨询营业网点工作人员。<br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">&nbsp; 【西邮所定于2016年10月15日停止交易一天】</span></strong><br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 由此给您带来的不便，我们深表歉意！感谢您对本中心的理解和支持。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp; 特此公告。</span>
<div style="text-align: right;">
	<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;二零一六年九月三十日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
