<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D049号《西游记》小型张藏品的停牌公告",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",232,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-12 15:26:38 &nbsp",284,349);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size: 16px\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品：<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img alt=\"\" src=\"/uploads/allimg/c161123/14OX613Q30P-2SC.png\" style=\"width: 652px; height: 132px\" /><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2016年11月14日09时30分起停牌，挂牌藏品《西游记小型张》暂停交易一天，于2016年11月15日09时30分起复牌交易。<br />\r\n&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;特此公告！</span>\r\n<div style=\"text-align: right\">\r\n	<span style=\"font-size: 16px\">宁夏西邮文化艺术品交易中心有限公司<br />\r\n	二零一六年十一月十二日</span>",351,1388);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX613Q30P-2SC_lit.png",1390,1476);
$z[7][4]['name']="litpic";

?>