{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普32邮票“美丽中国”（600004）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">普32邮票&ldquo;美丽中国&rdquo;（600004）</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：600004<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：5.00元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：100000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 25枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：100000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整版自提</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：普32邮票&ldquo;美丽中国&rdquo;<br style="padding: 0px; margin: 0px;" />
															【图案面值】 : 0.8元/枚<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2013年5月19日<br style="padding: 0px; margin: 0px;" />
															【全 套 &nbsp;数】：6版（每版25枚）<br style="padding: 0px; margin: 0px;" />
															【藏品规格】：40&times;30毫米<br style="padding: 0px; margin: 0px;" />
															【齿孔度数】：13度<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：25枚<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：雕刻版<br style="padding: 0px; margin: 0px;" />
															【防伪方式】：防伪纸张、防伪油墨、微缩文字、异形齿孔、荧光喷码<br style="padding: 0px; margin: 0px;" />
															【设 &nbsp;计 者】：马立航 、姜伟杰<br style="padding: 0px; margin: 0px;" />
															【印 制 &nbsp;厂】：北京邮票厂<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;霞浦位于福建省东北沿海，是福建海岸线最长的县市，在摄影界被誉为&ldquo;中国最美丽的滩涂&rdquo;。<br style="padding: 0px; margin: 0px;" />
															滩涂，是陆地和大海之间的纽带。现代汉语词典是这么解释的：河流或海流夹杂的泥沙在地势较平的河流入海处或海岸附近沉积而形成的浅海滩。仅福建省就有近三百万亩的滩涂，在漫长的岁月长河中，经过无数次的潮起潮落，滩涂形成了自己特有的景观，尤其是这些年迅速发展起来的近海滩涂养殖，那些渔排木屋，那些小舟鱼网，那些浮标竹竿，随着潮水的涨退，变幻着无穷的组合，吸引来无数摄影人的目光。滩涂是海的一个部分，涨潮时它和大海浑然一体，有着水天一色的辽阔，有着惊涛拍岸的壮美。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;霞浦滩涂位于福建省宁德市霞浦县，霞浦依山临海，风光旖旎，有着长达480公里的海岸线，是福建海岸线最长的县市。据《霞浦县志》载，&ldquo;清置霞浦县，县境西南有霞浦江，东流入海。又有霞浦山，海中有青、黑、元、黄四屿，日出照映，江水如霞彩，这是山以江名，县以江名。&rdquo;霞浦浅海滩涂面积一百零四万亩，是全国滩涂风光最典型最集中的地方，形成了自己独特的景观，让海内外摄影家趋之若鹜，被誉为&ldquo;中国最美的滩涂&rdquo;，每年接待摄影爱好者10多万人次。<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
