<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","西邮所让梦想照进现实",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",200,250);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-04 10:33:00 &nbsp",252,317);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">朋友，你有没有想过，比如生与死，生是没能预料的梦想，死是谁也逃避不了的现实。</span><br />\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">每种下一颗麦子、稻谷都是现实的问题，如果想要世界不再有饥荒，这曾是很多人的梦想。梦想不能实现，我们称之为不切实际的空想。但是，在特定的历史时期，比如矛盾尖锐世态纷繁复杂，使人们从一个不堪的现实世界走向另一个未知的现实世界的，却正是这种近乎有些狂热的所谓空想的引领。</span>",319,1214);
$z[6][4]['name']="body";
$z[7]=Array("field","",1216,1255);
$z[7][4]['name']="litpic";

?>