{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西邮所让梦想照进现实{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-04 10:33:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">朋友，你有没有想过，比如生与死，生是没能预料的梦想，死是谁也逃避不了的现实。</span><br />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">每种下一颗麦子、稻谷都是现实的问题，如果想要世界不再有饥荒，这曾是很多人的梦想。梦想不能实现，我们称之为不切实际的空想。但是，在特定的历史时期，比如矛盾尖锐世态纷繁复杂，使人们从一个不堪的现实世界走向另一个未知的现实世界的，却正是这种近乎有些狂热的所谓空想的引领。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
