{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邯郸古墓群出土大批古钱币（图）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 17:29:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(64, 64, 64); font-family: 宋体; font-size: 16px; line-height: 24px; text-indent: 32px;">记者从河北省邯郸市文物考古管理所获悉，该市文物考古部门近日在配合某基建工地进行文物勘探时，发现一处清代时期的墓葬群，发掘出土一批精美随葬品，其中的一批光绪龙洋，保存完好，十分罕见。</span><br />
<p style="padding: 0px; margin: 21px 10px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 24px; text-indent: 32px; text-align: center;">
	<span style="padding: 0px; margin: 0px; color: rgb(64, 64, 64); font-family: 宋体;"><img alt="" src="/uploads/allimg/c161124/14O95J4a64Z-24B4.jpg" style="width: 553px; height: 394px;" /></span></p>
<p style="padding: 0px; margin: 21px 10px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 24px; text-indent: 32px;">
	<span style="padding: 0px; margin: 0px; color: rgb(64, 64, 64); font-family: 宋体;">&nbsp; 经上级文物部门批准，邯郸市文物考古管理所对该墓葬群进行了抢救性发掘，共发掘出古墓12座，其中8座为土坑墓，4座为砖室墓，年代为清代晚期到民国初期。考古专家在清理发掘该墓葬群时，发现这些墓葬曾被严重盗扰，只有5座土坑墓保存完好，出土的瓷器、银元、铜币数量种类较多，有青花瓶、罐、光绪元宝、大清银币、宣统元宝等，从出土的文物来看这些墓葬属于贵族官员墓葬。</span></p>
<p style="padding: 0px; margin: 21px 10px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 24px; text-indent: 32px; text-align: center;">
	<span style="padding: 0px; margin: 0px; color: rgb(64, 64, 64); font-family: 宋体;"><img alt="" src="/uploads/allimg/c161124/14O95J5460I0-36230.jpg" /></span></p>
<p style="padding: 0px; margin: 21px 10px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; text-align: justify; line-height: 24px; text-indent: 32px;">
	<span style="color: rgb(64, 64, 64); font-family: 宋体;">据现场发掘的考古工作人员介绍，考古专家在该墓葬群还发掘出土了近百枚大清银币，其中&ldquo;长须龙&rdquo;两枚，&ldquo;曲须龙&rdquo;数枚，其余的都是光绪银元及大量的铜币。这些古钱币尤以墓主人胸前摆放的大清银币&ldquo;长须龙&rdquo;最为珍贵。这些银元经过特殊处理保存完好，从表面氧化程度考古专家推测这些钱币应为墓主人生前流通币，死后随葬。出土的两件青花瓷盘，一件是乾隆官款，一件莲花纹饰，保存较为完好。虽埋藏地下一百多年，经过文物专家特殊处理后这些钱币和瓷器依旧如新。另外，考古专家还从这个墓葬群发掘出了古玉璧如手指肚大小，考古专家表示，该墓葬群出土的随葬品，为研究项城清代至民国时期的墓葬形制、风俗习惯，提供了典型的实物依据。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95J4a64Z-24B4_lit.jpg{/dede:field}
