{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D043号《黄果树瀑布》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-07 16:05:11 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size: 16px">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品：</span>
<div>
	<span style="font-size: 16px"><img alt="" src="/uploads/allimg/c161123/14OX6131403P-19342.png" style="width: 650px; height: 130px" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX6131403P-19342_lit.png{/dede:field}
