<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D043号《黄果树瀑布》藏品停牌的公告",89,186);
$z[2][4]['name']="title";
$z[3]=Array("field","",188,227);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",229,279);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-07 16:05:11 &nbsp",281,346);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size: 16px\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品：</span>\r\n<div>\r\n	<span style=\"font-size: 16px\"><img alt=\"\" src=\"/uploads/allimg/c161123/14OX6131403P-19342.png\" style=\"width: 650px; height: 130px\" /></span>",348,667);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX6131403P-19342_lit.png",669,758);
$z[7][4]['name']="litpic";

?>