{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“互联网+邮币卡文化”推动邮币卡电子盘发展{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-26 01:47:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	人民网北京11月16日电 （周素雅）15日，主题为&ldquo;互联网+邮币卡文化&rdquo;的2015年中国首届邮币卡电子盘创新发展与社会责任峰会在北京举行。据了解，本次会议针对邮币卡交易出现的问题进行把脉问诊，并就交易平台如何管控风险，行业自律和对社会负责的主题进行了探讨。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	邮币卡通常是指邮票、钱币、电话卡。广义的邮包括邮票、邮资明信片、邮资信封、实寄封、实寄片首日封、小本票、印花税票等一切邮政用品。钱币包括国内外流通中的纸币和硬币、金银质地的贵金属币和除金银外的非贵金属币，总之是指可以合法买卖的所有钱币。电话卡，最早特指一种叫做田村卡的由日本田村公司及其协作企业制造的日本技术磁卡，也是我国使用最早的电话卡，现已被IC卡替代，随着电话卡的变化，邮币卡收藏中的卡也变成了IC卡。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	邮币卡因为有了鉴赏和投资理财价值，在一定的社会环境下，产生了收藏行为，并与社会金融联系紧密。据业内人士透露，上世纪80年代起，全国范围内逐渐发展形成了62个邮币卡线下交易市场。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	目前，根据国家促进文化产业发展、推进&ldquo;互联网+&rdquo;战略的要求，我国邮币卡交易行业积极创新，形成了邮币卡电子交易（俗称邮币卡电子盘）新型的交易模式。邮币卡交易由线下转到线上发展，解决了传统邮币卡交易的局限。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	近年来，邮币卡电子盘发展日渐蓬勃。李克强总理在政府工作报告中提出，制定&ldquo;互联网+&rdquo;行动计划，推动移动互联网、物联网、云计算、大数据等与现代制造业结合。显然，邮币卡也搭乘上了&ldquo;互联网+&rdquo;的列车。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;传统的邮币卡交易逐渐被邮币卡电子盘所取代是必然的。&rdquo;北京福丽特玩家邮币卡市场有限公司董事长樊德安指出，但是邮币卡电子盘这一中国独创的新型交易模式还很稚嫩，各地交易所在发展过程中产生了风控效果不明显、行业准入标准不明晰等种种问题。行业应该加强自律，承担社会责任，促进邮币卡电子盘健康有序发展。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	会上，全国政协原副主席白立忱、人民日报社《民生周刊》杂志社总编辑全世杰等还分别就 &ldquo;邮币卡文化在北京文化发展及经济建设中的重要性&rdquo;&ldquo;邮币卡文化与互联网金融的关联性&rdquo;&ldquo;邮票发展趋势&rdquo;等进行了话题讨论。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
