{dede:noteinfo notename="西邮所" channelid="1" macthtype="string"
refurl="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/list_8_(*).html"
startid="1" endid="13" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<section id="newContent">{/dede:areastart}
    {dede:areaend}</section>{/dede:areaend}
{/dede:listrule}
