{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}重要通告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-14 09:43:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的广大交易商、各会员单位：</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp;&nbsp;</span><span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;）， 为规范业务行为，维护市场秩序，保障投资者的合法权益。经本中心核实，现通告：挂牌藏品600005《花开富贵电影套票》发售商，在上市过程中对藏品存在违规宣传，严重损坏了广大交易商正常会员利益。本中心根据《宁夏西邮文化艺术品交易中心风险控制管理办法》的规定特此决定追加其锁仓期限6个月，共18个月，锁仓比例追加至40%，并限制其新建仓位卖出3个月。如后续发现其它违规行为，会采取更严厉的处罚，确保广大会员的利益。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp;<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 特此公告!</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<br style="padding: 0px; margin: 0px;" />
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	二零一六年九月十四日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
