{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普31“中国鸟—绿尾虹雉”（ 600022）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<strong>普31&ldquo;中国鸟&mdash;绿尾虹雉&rdquo;（ 600022）</strong><br />
														交易参数：<br />
														【交易代码】：600022<br />
														【首日挂牌指导价】：8元/枚<br />
														【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：200000枚<br />
														【最小变动价位】： 0.01元<br />
														【最小提货数量】: 30枚<br />
														【市场流通量】：200000枚<br />
														<br />
														藏品信息：<br />
														【藏品名称】：普31中国鸟&mdash;绿尾虹雉<br />
														【图案面值】 ：0.40元<br />
														【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
														【邮票规格】：27&times;38mm<br />
														【齿孔度数】：13.5度<br />
														【整张枚数】：30枚<br />
														【整张规格】：162&times;258毫米<br />
														【发行日期】：2006年11月15日<br />
														【版 &nbsp; &nbsp; &nbsp; 别】：影写<br />
														【防伪方式】：防伪纸张、防伪油墨、异形齿孔、荧光喷码<br />
														【设 计 &nbsp;者】：黄华强<br />
														【责任编辑】：秦巍<br />
														【发行机构】：中国邮政<br />
														【印刷单位】：北京邮票厂<br />
														<br />
														藏品介绍：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;绿尾虹雉，属鸡形目雉科，大型鸟类。体长约58&mdash;82厘米，体重约692&mdash;1400克，雌雄个体有差异。绿尾虹雉于每年4-5月繁殖。该物种以前分布广泛，数量多，但近代由于受到生态环境被破坏以及人类的威胁，数量急剧减少，分布于中国西南地区。国内保护级别：一级；被世界列为世界性易危物种。营巢于大树下和灌丛中，每窝产卵6&mdash;12枚，孵化期23&mdash;25天。雄鸟头顶、脸的下部及耳羽等都闪着绿色虹光，向后转为金属赤红色，从头顶后部耸起冠羽覆盖着颈部，呈金属青铜色，向后转为红铜色；后颈和颈侧以及背的前部呈金属红铜色，背的中部、肩羽及翅上覆羽等转为紫铜色，并闪着金属绿蓝色；下背及腰部羽白色。飞羽黑褐具绿缘，尾羽蓝绿色。下体黑色，嘴角灰色。上体羽毛在阳光的照射下犹如雨后的彩虹故成&ldquo;虹雉&rdquo;，因其尾绿，故得名&ldquo;绿尾虹雉&rdquo;。栖息于林线以上海拔3000一5000米左右的高山草甸、灌丛和裸岩地带，尤其喜欢多陡崖和岩石的高山灌丛和灌丛草甸，冬季常下到3000米左右的林缘灌丛地带活动是典型的植食性鸟类，以植物的果实、种子和浆果等为食。冬季由于高山积雪过厚，难以找到砂砾，这时它就吞吃火炭，因此又名&ldquo;火炭鸡&rdquo;，又因它的嘴很坚固，而且前端弯曲呈钩状，很像老鹰的嘴，称为&ldquo;鹰鸡&rdquo;。<br />
														风险分析：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
