<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","央行将发行新版100元人民币 系2015年版第五套百元",89,192);
$z[2][4]['name']="title";
$z[3]=Array("field","",194,233);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",235,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-25 18:03:00 &nbsp",287,352);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div>\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 宋体; font-size: medium; line-height: 26px; text-indent: 28px;\">&nbsp; 央行10日宣布，将于2015年11月12日起发行2015年版第五套人民币100元纸币。在保持规格、主图案、主色调等与2005年版第五套人民币100元纸币不变的前提下，对票面图案、防伪特征及其布局进行了调整，更易于识别伪。</span>",354,811);
$z[6][4]['name']="body";
$z[7]=Array("field","",813,852);
$z[7][4]['name']="litpic";

?>