{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D058号《宁夏民居》等藏品的停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-23 16:04:28 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：<br />
&nbsp; &nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OXY4L6120-111b.jpg" style="width: 593px; height: 249px;" /><br />
&nbsp; &nbsp; &nbsp; 根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br />
&nbsp; &nbsp; &nbsp; 自2016年11月24日09时30分起，挂牌藏品《普26宁夏民居》、《抗战七十周年纪念》、《十二届人大政协封》暂停交易一天，于2016年11月25日09时30分起恢复交易；挂牌藏品《普22黄果树瀑布》暂停交易一小时，于2016年11月24日10时30分起恢复交易。<br />
&nbsp;&nbsp;<br />
&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />
&nbsp; &nbsp; &nbsp; 特此公告！<br />
&nbsp;</span>
<div style="text-align: right;">
	<span style="font-size:16px;">宁夏西邮文化艺术品交易中心有限公司<br />
	二零一六年十一月二十三日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXY4L6120-111b_lit.jpg{/dede:field}
