<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","“西邮所”送好礼，原始票大配送会员名单",89,184);
$z[2][4]['name']="title";
$z[3]=Array("field","",186,225);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",227,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-02 20:26:00 &nbsp",279,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<br />\r\n	<span style=\"padding: 0px; margin: 0px;\">各位交易会员：</span>",346,618);
$z[6][4]['name']="body";
$z[7]=Array("field","",620,659);
$z[7][4]['name']="litpic";

?>