<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于调整出入金时间的通知",89,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",206,256);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-20 20:59:10 &nbsp",258,323);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<br />\r\n<span style=\"font-size: 16px\">尊敬的会员：<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;随着文化商品品种及交易量的增加，为确保客户资金清算工作安全、稳定、顺利地进行，本中心资金入金时间将调整至每个交易日19:00后进行，故从2016年10月21日起银行签约绑定及出入金时间也相应调整，具体时间为：<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;签约绑定时间：8:30&mdash;19:00（交易日）<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;入金时间：9:00&mdash;19:00（交易日）<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出金时间：9:00&mdash;16:00（交易日）<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;请各会员据此做好工作安排。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;特此通知</span><br />\r\n<br />\r\n<div style=\"text-align: right\">\r\n	<span style=\"font-size: 16px\">宁夏西邮文化艺术品交易中心<br />\r\n	二〇一六年十月二十日</span><br />\r\n	<br />\r\n	&nbsp;",325,1365);
$z[6][4]['name']="body";
$z[7]=Array("field","",1367,1406);
$z[7][4]['name']="litpic";

?>