{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于调整出入金时间的通知{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-20 20:59:10 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="font-size: 16px">尊敬的会员：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;随着文化商品品种及交易量的增加，为确保客户资金清算工作安全、稳定、顺利地进行，本中心资金入金时间将调整至每个交易日19:00后进行，故从2016年10月21日起银行签约绑定及出入金时间也相应调整，具体时间为：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;签约绑定时间：8:30&mdash;19:00（交易日）<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;入金时间：9:00&mdash;19:00（交易日）<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出金时间：9:00&mdash;16:00（交易日）<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;请各会员据此做好工作安排。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;特此通知</span><br />
<br />
<div style="text-align: right">
	<span style="font-size: 16px">宁夏西邮文化艺术品交易中心<br />
	二〇一六年十月二十日</span><br />
	<br />
	&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
