<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D002号《牧牛图》上市发起人锁仓公告",89,186);
$z[2][4]['name']="title";
$z[3]=Array("field","",188,227);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",229,279);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-08-04 14:34:00 &nbsp",281,346);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">尊敬的经纪会员、交易会员：<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; 为配合营销配售活动，《牧牛图》上市发起人已通过市场回购，累计持仓《牧牛图》达到了约定锁仓的上限61000枚，特申请自2016年8月8日起锁仓一年。&nbsp;<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; 经西邮所研究决定同意其申请并提供相关技术支持。<br style=\"padding: 0px; margin: 0px;\" />\r\n具体如下：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OXM15AR0-3L24.jpg\" style=\"padding: 0px; margin: 10px; border: none; max-width: 700px; width: 599px; height: 82px;\" />",348,1363);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXM15AR0-3L24_lit.jpg",1365,1451);
$z[7][4]['name']="litpic";

?>