{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D024号《西游记》小型张藏品的停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-11 17:51:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：</span>
<div>
	<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;"><img alt="" src="/uploads/allimg/c161123/14OXLc55220-324M.jpg" style="width: 593px; height: 106px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXLc55220-324M_lit.jpg{/dede:field}
