<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016D024号《西游记》小型张藏品的停牌公告",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",226,276);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-11 17:51:00 &nbsp",278,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：</span>\r\n<div>\r\n	<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\"><img alt=\"\" src=\"/uploads/allimg/c161123/14OXLc55220-324M.jpg\" style=\"width: 593px; height: 106px;\" /></span>",345,913);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXLc55220-324M_lit.jpg",915,1002);
$z[7][4]['name']="litpic";

?>