{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}小型张“抗日战争胜利七十周年纪念”（700001）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">小型张&rdquo;中国人民抗日战争胜利七十周年纪念（香港）&ldquo;（700001）</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：700001<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：20元/张<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：57000张<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 1张<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：57000张<br style="padding: 0px; margin: 0px;" />
															【备注】： 以整封自提<br style="padding: 0px; margin: 0px;" />
															&nbsp;<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：中国人民抗日战争胜利七十周年纪念（香港）邮票小型张<br style="padding: 0px; margin: 0px;" />
															【藏品分类】：型张<br style="padding: 0px; margin: 0px;" />
															【藏品志号】：WY201<br style="padding: 0px; margin: 0px;" />
															【单张面值】：10.00（圆/港币）<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2015年9月2日<br style="padding: 0px; margin: 0px;" />
															【藏品规格】：80毫米 &times; 40毫米<br style="padding: 0px; margin: 0px;" />
															【外形规格】：135毫米 &times; 85毫米<br style="padding: 0px; margin: 0px;" />
															【齿孔度数】：14 度(两面直边各有一个椭圆形齿孔)<br style="padding: 0px; margin: 0px;" />
															【整 &nbsp;张 数】：1张<br style="padding: 0px; margin: 0px;" />
															【印刷方法】：平版<br style="padding: 0px; margin: 0px;" />
															【防伪方式】：防伪纸张、防伪油墨、异形齿孔、荧光喷码<br style="padding: 0px; margin: 0px;" />
															【设&nbsp;计 &nbsp;者】：伍尚豪<br style="padding: 0px; margin: 0px;" />
															【承 印 &nbsp;者】：法国Cartor Security Printing<br style="padding: 0px; margin: 0px;" />
															【纸 &nbsp; &nbsp; &nbsp;张】：混有防伪纤维<br style="padding: 0px; margin: 0px;" />
															【印&nbsp;制 &nbsp;厂】：香港邮政<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;一九四五年九月二日，日本向同盟国递交投降书，中国人民在经历长达八年的抗日战争后，最终获胜。为铭记历史和缅怀先烈，中央人民政府把九月三日定为「中国人民抗日战争胜利纪念日」，并在全国各地举办一连串大型纪念活动。二○一五年是抗日战争胜利七十周年，香港邮政发行一款邮票小型张，以志其事。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 在抗日战争中获胜，让中国人在努力复兴国家的路上迈出重要一步，亦为今日中国经济及社会的长足发展奠定基础，是我国历史的重要一页。香港同胞同样经历了祖国对日八年抗战和太平洋战争，适逢抗日战争胜利七十周年，香港特别行政区政府举办多项纪念活动，包括官方纪念仪式、展览、讲座、研讨会、电影放映等，让市民了解这项胜利对建立和平与先进的中国的重大意义。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 邮票小型张把当年抗日的情景与今天香港的繁华景象作一对比，藉此强调和平稳定得来不易，必须好好珍惜。<br style="padding: 0px; margin: 0px;" />
															&nbsp;<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
