<?php
$z[0]=Array("arclist","\r\n                    <li class=''>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <div class=\"time\">\r\n                                <div class=\"date\">[field:pubdate function=strftime('%m-%d',@me)/]</div>\r\n                                <div class=\"year\">[field:pubdate function=strftime('%Y',@me)/]</div>\r\n                            </div>\r\n                            <div class=\"textBox\">\r\n                                <div class=\"tit\">[field:title/]</div>\r\n                                <div class=\"text\">[field:description function=\"cn_substr(@me,80)\"/]...</div>\r\n                            </div>\r\n                            <div class=\"arrow\"></div>\r\n                        </a>\r\n                    </li>\r\n                ",38,894);
$z[0][4]['titlelen']="60";
$z[0][4]['row']="200";
$z[0][4]['typeid']="son";
$z[0][4]['pagesize']="8";

?>