{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国家邮政局5月19日将发行黄姚古镇邮票{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-29 23:20:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GN02R0-T0O.jpg" style="width: 650px; height: 432px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	黄姚古镇邮票体现了一幅和谐、秀美、生态、环保人文的城镇。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	据了解，国家邮政局将黄姚古镇选题列入了2016年邮票发行计划。邮政集团公司拟于2016年5月19日（世界旅游日）当天发行《中国古镇（第二组）》6枚邮票，内容为：上海青浦区朱家角镇、江苏姜堰市溱潼镇、贵州贵阳市青岩镇、广西昭平县黄姚镇、广东沙湾镇、浙江省江山市廿八都镇。这是暨2003年国家邮政局发行了涉及贺州的麒麟樽邮票后，时隔12年贺州市再次幸运的迎来黄姚古镇选题的邮票发行！</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	贺州黄姚古镇邮票经国家邮票印制局设计绘画大师现场采风、反复绘制，经贺州市旅游发展改革委员会和黄姚景区管委会鉴定无误最终确定图稿。该图稿直接、生动的刻画了黄姚古镇标志性景点，更体现了一幅和谐、秀美、生态、环保人文的城镇。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GN02R0-T0O_lit.jpg{/dede:field}
