{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法国举行猴年生肖纪念邮票首发式 贺中国新年{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-23 01:26:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	法国邮政总局1月29日在巴黎集邮商店&ldquo;墨方厅&rdquo;举行猴年生肖纪念邮票首发仪式。法国邮政总局邮票事务负责人吉勒&middot;利夫基茨、中国驻法国使馆文化处公参李少平、邮票设计师法国华人艺术家李中耀以及法国集邮爱好者等出席仪式。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	法国猴年生肖纪念邮票全套一枚，单张票面中央一只水墨技法绘就的猴子敏捷而灵活，票面上分别写有法文和中文&ldquo;猴年&rdquo;字样，邮票面值为0.8欧元。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
