<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法国举行猴年生肖纪念邮票首发式 贺中国新年",89,188);
$z[2][4]['name']="title";
$z[3]=Array("field","",190,229);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",231,281);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-23 01:26:00 &nbsp",283,348);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	法国邮政总局1月29日在巴黎集邮商店&ldquo;墨方厅&rdquo;举行猴年生肖纪念邮票首发仪式。法国邮政总局邮票事务负责人吉勒&middot;利夫基茨、中国驻法国使馆文化处公参李少平、邮票设计师法国华人艺术家李中耀以及法国集邮爱好者等出席仪式。</p>\r\n<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	法国猴年生肖纪念邮票全套一枚，单张票面中央一只水墨技法绘就的猴子敏捷而灵活，票面上分别写有法文和中文&ldquo;猴年&rdquo;字样，邮票面值为0.8欧元。</p>",350,1233);
$z[6][4]['name']="body";
$z[7]=Array("field","",1235,1274);
$z[7][4]['name']="litpic";

?>