{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮票上的妈妈 献给母亲的赞礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 01:23:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;慈母手中线，游子身上衣。临行密密缝，意恐迟迟归。谁言寸草心，报得三春晖&rdquo;&mdash;&mdash;世间最伟大的爱莫过于母爱。每年5月第二个星期日(今年为5月10 日)，是国际上普遍认定的&ldquo;母亲节&rdquo;。母亲节最早出现在古希腊;而现代的母亲节则源于美国。1934年初，为了纪念第20个母亲节，曾任全美士兵母亲协会主席的麦克鲁斯夫人，向当时的美国总统罗斯福提出在母亲节发行一枚纪念邮票，以纪念这一节日。身为总统和集邮爱好者的罗斯福亲自设计了这枚邮票的草图。邮票选用了美国著名画家惠斯勒的&ldquo;艺术家的母亲&rdquo;作为主图，在邮票的左下角加上了一个插满康乃馨的花瓶，这是世界上第一套母亲节邮票。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1947年巴西发行的母亲节邮票，展现了母亲怀抱婴儿的温馨画面。1967年奥地利发行的母亲节邮票以芬迪(Peter Fendi)1841年的油画为主图，描绘了正准备用奶瓶喂孩子的年轻母亲。1983年比利时发行了一套3枚母亲节邮票，用简洁的白描线条画再现了3位不同年龄的母亲正在工作和照顾子女的场景。1987年美国发行的一套8枚《问候》邮票中，有1枚就是在母亲节向妈妈表达爱意的图景。古巴在同一时期也连续发行多套用不同鲜花作为主图的母亲节邮票。而爱沙尼亚2005年4月2日发行的邮票，则以特写镜头留住了孩子用小手把花朵送给妈妈的感人一刻。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1999年法属波西尼亚发行的母亲节邮票别出心裁，图案中并未出现母亲形象，主角是排成一列、展露笑颜的3个小兄弟。孩子的健康成长正是送给母亲最好的礼物。2008年4月8日摩纳哥发行的母亲节邮票以心形为背景，前景是手捧一束玫瑰花母亲与儿子喜悦的笑脸。2008年5月2日墨西哥发行的邮票则以怀抱婴儿的母亲为主图。2009年5月10日土耳其发行了双齿孔票(有心形齿)一套4枚，图案分别为雌鸟寻食回巢、母亲手托婴儿、母亲手托握花的婴儿之手、母子亲昵，场面十分温馨感人。2009年6月3日塞内加尔发行一套2枚邮票，描绘了女儿向妈妈送花和母女拥抱的情景，富有鲜明的非洲特色。2013年5月10 日墨西哥发行母亲节纪念邮票，图案为表现母与子的印第安风格工艺品。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	阿拉伯地区的许多国家将母亲节定在3月21日&ldquo;春分&rdquo;日。当地人认为&ldquo;春分&rdquo;是春天的开始、一年之始，以此表现母亲的伟大。这些国家也多在这一天发行母亲节邮票。比如埃及1957年发行的母亲节邮票，图案是一对儿女与母亲撒娇亲昵的画面。1963年伊朗发行了一套2枚同图不同色的邮票，图案是一轮明月下怀抱婴儿的母亲剪影。叙利亚是发行母亲节邮票最多的国家之一，长期以来每年都推出一枚，以绘画、雕塑、照片等艺术形式，展现了一系列母与子的形象。2013 年3月21日，阿联酋发行母亲节纪念邮票，以此表达对&ldquo;阿联酋之母&rdquo;&mdash;&mdash;前总统扎耶德酋长的夫人法忒麦&middot;宾特&middot;穆巴拉克的感谢，她一直致力于改善妇女地位、提高妇女教育水平、保护家庭和儿童、鼓励妇女就业等，并为阿联酋和中东地区做出了巨大贡献。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国邮政曾于2013年5月11日母亲节前夕发行了《感恩母亲》邮票和小全张，图案为心形中间的一株康乃馨，心形下方为金色丝带，刮开金色丝带的覆盖层，每枚邮票都印制了一条祝福语，可显出感恩母亲的四句话，分别为&ldquo;妈妈，我爱您&rdquo;&ldquo;祝妈妈永远幸福&rdquo;&ldquo;世上只有妈妈好&rdquo;&ldquo;谢谢妈妈养育之恩&rdquo;。这是中国邮政首次推出的&ldquo;刮出祝福&rdquo;邮票新品种。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
