<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","会员管理办法（暂行）",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div>\r\n	<div>\r\n		&nbsp;",283,343);
$z[6][4]['name']="body";
$z[7]=Array("field","",345,384);
$z[7][4]['name']="litpic";

?>