{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z002《宁夏民居》藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-08 09:48:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年7月7日对挂牌藏品《宁夏民居》普通邮票面向所有投资人会员进行定价申购发行，具体事项公告如下：</span><br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										<img alt="" src="/uploads/allimg/c161123/14OXM09CH0-411b.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 672px; height: 246px;" /><br style="padding: 0px; margin: 0px;" />
										<span style="padding: 0px; margin: 0px;">&nbsp; &nbsp; &nbsp; &nbsp;单一品种单一账户中签总数&nbsp;＝&nbsp;单账号持仓市值&nbsp;&divide;&nbsp;参与申购交易会员总持仓市值&nbsp;&times;&nbsp;0%该品种可供申购总量&nbsp;＋&nbsp;单账户该品种申购资金&nbsp;&divide;&nbsp;该品种申购总资金&nbsp;&times;&nbsp;100%该品种可供申购总量＋&nbsp;随机分配数量。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 中签商品查询：登录西邮文化艺术品交易中心客户端查询（必须注册实盘账户）<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp;《宁夏民居》将于2016年7月11日正式挂牌交易，首日价格涨幅为30%，跌幅为30%。自2016年7月12日起上述藏品的正常交易日价格涨幅为10%，跌幅为10%。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;特别提醒：本中心入金时间：9:00&mdash;17:30（交易日）；出金时间：9:00&mdash;16:00（交易日）为保证出入金通道顺畅，请勿集中于9:00至10:00办理出入金业务，请合理安排您的出入金时间。<br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										特此公告！</span>
										<div style="padding: 0px; margin: 0px; text-align: right;">
											<br style="padding: 0px; margin: 0px;" />
											<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM09CH0-411b_lit.jpg{/dede:field}
