{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于平安银行出入金系统临时维护的通知{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-14 09:24:44 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="font-size:16px;">尊敬的交易会员：<br />
&nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），根据业务需求接到通知，系统需要临时维护。本中心平安银行出入金系统及签约临时暂停，预计恢复时间2016年11月14日12时。<br />
<br />
&nbsp; &nbsp; &nbsp; 感谢您对交易中心的支持！<br />
&nbsp; &nbsp; &nbsp; 请各位客户知晓，由此给您带来的不便敬请谅解！<br />
<br />
&nbsp; &nbsp; &nbsp; 特此通知<br />
&nbsp;<br />
&nbsp;</span>
<div style="text-align: right;">
	<br />
	<span style="font-size:16px;">宁夏西邮文化艺术品交易中心有限公司<br />
	&nbsp;&nbsp;&nbsp;2016年11月14日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
