<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于平安银行出入金系统临时维护的通知",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",224,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-14 09:24:44 &nbsp",276,341);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<br />\r\n<span style=\"font-size:16px;\">尊敬的交易会员：<br />\r\n&nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），根据业务需求接到通知，系统需要临时维护。本中心平安银行出入金系统及签约临时暂停，预计恢复时间2016年11月14日12时。<br />\r\n<br />\r\n&nbsp; &nbsp; &nbsp; 感谢您对交易中心的支持！<br />\r\n&nbsp; &nbsp; &nbsp; 请各位客户知晓，由此给您带来的不便敬请谅解！<br />\r\n<br />\r\n&nbsp; &nbsp; &nbsp; 特此通知<br />\r\n&nbsp;<br />\r\n&nbsp;</span>\r\n<div style=\"text-align: right;\">\r\n	<br />\r\n	<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心有限公司<br />\r\n	&nbsp;&nbsp;&nbsp;2016年11月14日</span>",343,1165);
$z[6][4]['name']="body";
$z[7]=Array("field","",1167,1206);
$z[7][4]['name']="litpic";

?>