{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}风险提示：任何对产品预期价格或者收益的承诺{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-28 18:17:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">风险提示：任何对产品预期价格或者收益的承诺均为虚假，请各位会员切勿相信。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">投诉邮箱：</span><span style="color:#ff0000;"><u><span style="font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">2125142503</span><span style="font-size:16px;"><u>@qq.com</u></span></u></span>&nbsp;<span style="color:#ff0000;"> 、&nbsp;<u><span style="font-size: 16px;">2932845760@qq.com</span></u></span><br />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<img alt="" src="/uploads/allimg/c161123/14OY055613R0-1F63.png" style="padding: 0px; margin: 10px; border: none; max-width: 700px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; height: 257px; width: 1031px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OY055613R0-1F63_lit.png{/dede:field}
