{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪念邮票“建党九十周年”（ 600012）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">纪念邮票&ldquo;建党九十周年&rdquo;（ 600012）</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：600012<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：20元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：240000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 6枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：240000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整套自提<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：《中国共产党成立九十周年》<br style="padding: 0px; margin: 0px;" />
															【藏品志号】：2011-16<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2011年6月22日<br style="padding: 0px; margin: 0px;" />
															【图案面值】<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-1）开天辟地&nbsp;&nbsp;&nbsp;&nbsp;1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-2）烽火岁月 &nbsp; 1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-3）执政创业&nbsp;&nbsp; 1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-4）改革大潮&nbsp; &nbsp;1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-5）世纪跨越&nbsp;&nbsp; 1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp;（6-6）科学发展 &nbsp;&nbsp;1.20元<br style="padding: 0px; margin: 0px;" />
															&nbsp; 小型张&nbsp; 中国共产党成立九十周年&nbsp; 6元<br style="padding: 0px; margin: 0px;" />
															【材 &nbsp; &nbsp; &nbsp;质】 : 纸质<br style="padding: 0px; margin: 0px;" />
															【全套枚数】：6枚，小型张1枚<br style="padding: 0px; margin: 0px;" />
															【齿孔度数】：13度<br style="padding: 0px; margin: 0px;" />
															【邮票规格】：33&times;44毫米<br style="padding: 0px; margin: 0px;" />
															【整张枚数】<br style="padding: 0px; margin: 0px;" />
															&nbsp; 版式一 12枚<br style="padding: 0px; margin: 0px;" />
															&nbsp; 版式二 6枚（6-1、2、3图各2枚/张；6-4、5、6图各2枚/张）<br style="padding: 0px; margin: 0px;" />
															【整张规格】：版式一 165&times;190毫米、版式二 130&times;140毫米&nbsp;&nbsp;<br style="padding: 0px; margin: 0px;" />
															&nbsp; 小型张邮票规格：50&times;42毫米<br style="padding: 0px; margin: 0px;" />
															&nbsp; 小型张外形规格：92&times;125毫米<br style="padding: 0px; margin: 0px;" />
															&nbsp; 小型张齿孔度数：13度<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：影写版<br style="padding: 0px; margin: 0px;" />
															【背面刷胶】：[G]<br style="padding: 0px; margin: 0px;" />
															【防伪方式】：防伪纸张&nbsp;&nbsp;防伪油墨&nbsp;&nbsp;荧光喷码<br style="padding: 0px; margin: 0px;" />
															【设 计 &nbsp;者】：郝旭东<br style="padding: 0px; margin: 0px;" />
															【责任编辑】：秦巍<br style="padding: 0px; margin: 0px;" />
															【印 制 &nbsp;厂】：北京邮票厂<br style="padding: 0px; margin: 0px;" />
															【原 作 &nbsp;者】：何红舟 黄发祥（《启航》原画作者）<br style="padding: 0px; margin: 0px;" />
															【摄 影 &nbsp;者】：任国恩 袁学军 张桐胜</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;2011年是中国共产党成立90周年。隆重热烈地纪念中国共产党成立90周年，对于鼓舞全党全国各族人民意气风发地投身改革开放和社会主义现代化建设，坚定不移地把中国特色社会主义伟大事业推向前进，具有十分重要的意义。中国邮政特发行《中国共产党成立九十周年》纪念邮票一套6枚，小型张1枚。中国集邮总公司同时发行首日封一套7枚，启用纪念戳一枚。&nbsp; 　<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 该套邮票充分展现了我们党建党90年来的光辉历史进程，纵向回顾，展现成就，憧憬未来。中国共产党自强不息，与时俱进，一次次带领中华民族从胜利走向胜利，书写着永载史册的光辉篇章。邮票图稿选取了代表各个时期的典型元素，以更好地诠释每枚邮票的主题。邮票色调以党旗红、黄为主，邮票设计以飘动的党旗作为统一邮票画面的基本元素，布局优美、主题鲜明、层次清晰。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第一枚&ldquo;开天辟地&rdquo;，以党的&ldquo;一大&rdquo;上海会址和大型油画作品《启航》为画面元素。党的&ldquo;一大&rdquo;宣告中国共产党正式成立，这是近代中国革命历史上划时代的里程碑。毛泽东主席曾说：&ldquo;中国产生了共产党，这是开天辟地的大事变。&rdquo;<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第二枚&ldquo;烽火岁月&rdquo;，以人民英雄纪念碑及其浮雕为画面元素。我们党领导全国人民取得了新民主主义革命的胜利，建立了中华人民共和国。没有共产党，就没有新中国这是中国人民从长期奋斗历程中得到的最基本、最重要的结论。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第三枚&ldquo;执政创业&rdquo;，以天安门和毛主席纪念堂北大门雕塑群《丰功伟绩》中的一组工农兵雕塑为画面元素。高举毛主席旗帜阔步前进的工农兵形象，象征着中国共产党带领全国人民，在社会主义革命和建设时期取得的伟大胜利。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第四枚&ldquo;改革大潮&rdquo;，以人民日报刊发的十一届三中全会公报和深圳特区标志性建筑、雕塑《拓荒牛》为画面元素。党的十一届三中全会开启了改革开放历史新时期，深圳是我国改革开放的标志性城市。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第五枚&ldquo;世纪跨越&rdquo;，以中华世纪坛和上海浦东标志性建筑为画面元素。中华世纪坛是中国人民迎接新千年、新世纪的标志性纪念建筑。1990年，中国向全世界宣布开发开放上海浦东地区，为改革开放掀开了全新的一页。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 第六枚&ldquo;科学发展&rdquo;，以我国航天员首次实施空间出舱活动、北京奥运会国家体育场和上海世博会中国馆等为画面元素。北京奥运会、上海世博会、神舟七号载人航天飞行等圆满成功，充分展示了改革开放30年来我国显著提高的经济实力、科技实力、综合国力。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 该套邮票由我国著名邮票设计家郝旭东先生设计。<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
