{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}金银币的中国记忆 杰出历史人物纪念币赏析(图{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-22 00:16:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1993年，发行期跨越10个春秋的中国杰出历史人物金银纪念币完美收官，以新中国开国领袖毛泽东为首的中国杰出历史人物金银纪念币（第10组），为整个系列画上了圆满的句号。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	纵观中国杰出历史人物系列金银纪念币，于方寸之间概括记录了近50位为推进中国乃至世界文明发展做出过重大贡献的历史人物的丰功伟绩，全面展示了中华民族勤劳勇敢，坚韧不拔，前赴后继，生生不息的精神风貌，以独特的形式向世界介绍了我国悠久的历史文化，堪称一部镌刻在金银币上的&ldquo;中国通史&rdquo;。特别值得一提的是，该套纪念币的发行，正值中国现代金银币事业的初创时期。历时10年的发行期，完整经历了中国金币行业从无到有，从小到大，从初级阶段到逐渐成熟的全过程，本身就是我国金币事业发展历程的重要见证和缩影。因此，该套纪念币所蕴涵的历史意义、时代意义及其对中国文化的记忆价值，必将引起社会公众的强烈关注。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HI962Z-106391.jpg" style="width: 250px; height: 250px;" /><img alt="" src="/uploads/allimg/c161124/14O95HJ05N0-113534.jpg" style="width: 250px; height: 250px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国杰出历史人物金银纪念币（第10组），承袭了该系列纪念币的一贯风格。既借鉴了西方造型艺术浮雕写实的技法，又传承了中国传统绘画艺术构图之奇巧，人物形象突出，个性鲜明，虚实结合，生动传神。制作中采用了镜面和浮雕工艺，层次丰富，明净无瑕。<br />
	<span style="text-indent: 2em;">&nbsp; &nbsp; &nbsp; &nbsp;该套纪念币含金币1枚，银币4枚，由沈阳造币厂铸造。金银币共同正面为繁体字中华人民共和国国名、国徽和发行年号。1/3盎司金币的背面图案选用了毛泽东主席的侧面头像，这幅头像同时也是《毛泽东选集》封面的画像。背景是庄严的天安(港股00028)门及猎猎舞动的五星红旗，头像下方是毛泽东手书姓名和&ldquo;1893&mdash;1976&rdquo;字样。整体构图显得既庄重大方，又极具亲和力。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<span style="text-indent: 2em;"><img alt="" src="/uploads/allimg/c161124/14O95HJ33c0-12Bb.jpg" style="width: 250px; height: 250px;" /><img alt="" src="/uploads/allimg/c161124/14O95HJ42320-13K23.jpg" style="width: 250px; height: 250px;" /><br />
	<img alt="" src="/uploads/allimg/c161124/14O95HJ4E40-14L33.jpg" style="width: 250px; height: 250px;" /><img alt="" src="/uploads/allimg/c161124/14O95HJFR0-1525I.jpg" style="width: 250px; height: 250px;" /></span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	4 枚银币的背面人物分别是周恩来总理、全国人大委员长朱德、国家主席刘少奇和中国共产党的创始人李大钊。周恩来总理选用的是他作政府工作报告时的形象。画面上的周恩来手捧报告，面对话筒，神态端庄威严，双目炯炯有神，背景是庄严的人民大会堂。周恩来的手书姓名和&ldquo;1898&mdash;1976&rdquo;字样，呈弧形环刻在币面的右上方；开国元帅朱德选用的是他作为中国人民解放军总司令，乘坐敞篷军车检阅部队的画面。朱总司令一身戎装，精神矍铄，左手扶栏，右臂轻挥，远处是迎风招展的&ldquo;八一&rdquo;军旗，以及耸立在蓝天下的华表，画面外，是雄壮的受阅将士，他们正以响遏行云的呐喊，回应着总司令的号令；第三枚银币上的刘少奇臂搭外衣，风尘仆仆，睿智的双目远望着云缠雾绕的群山，目光沉静而坚定，形象质朴而纯粹，令人深长思之，久久难忘；李大钊是中国共产主义的最早传播者和实践者，中国共产党的创始人之一，与陈独秀并称&ldquo;南陈北李&rdquo;。银币上的李大钊身穿中式长袍大褂，架一副眼镜，腋下夹书，目光深邃，表情凝重，背景是威严的城楼和发生在北京的&ldquo;五四&rdquo;运动。这套银币与此前的同类银币有所不同的是，每个人物都采用了本人的手书姓名，使银币更具有了文化及收藏价值。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国杰出历史人物金银纪念币1-10组发行结束，距今已有20多年了，当时受国内经济发展状况所限，该套纪念币发行数量较少、价格偏低，且大部分纪念均销往了海外，致使国内市场早已难觅芳踪，一币难求。笔者借此文，与泉友们共赏吧。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HI962Z-106391_lit.jpg{/dede:field}
