{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}全国首家邮币卡投资人俱乐部在汉成立{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 16:55:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											人民网武汉11月10日电 11月8日，全国首家邮币卡投资人自律组织&mdash;&mdash;湖北华中文化产权交易所投资人俱乐部在武汉成立，并召开第一次会员大会。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											俱乐部成立后，将积极发挥投资人和华中文交所的桥梁作用，为广大投资人创造健康交易环境，规范市场秩序、维护行业稳健发展。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											华中文交所董事长程家忠对俱乐部成立表示热烈祝贺。程家忠指出，我国文化产业拥有巨大的市场潜力、庞大的投资群体和崭新的发展契机，然而当前交易场所鱼龙混杂，市场参与人面临着较大风险，投资人俱乐部应运而生。华中文交所作为国资背景交易平台，始终把规范自律、把投资人利益放在首位，俱乐部的成立将有利于促进邮币卡电子交易市场的健康规范。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											据悉，邮币卡线上交易平台快速发展，截至目前，全国已有30多家交易平台投入运营，正在筹备的有20多家。华中文交所邮币卡电子盘自今年4月7日上线以来，发展势头强劲。截止11月8日，上市藏品总数达到67支，总成交额突破300亿元，单日成交额最高10亿元，投资会员近7万人，在全国文交所行业高踞上游。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
