{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}十二届人大政协会议纪念封（601001）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);">十二届人大政协会议纪念封（601001）</span></strong><br style="padding: 0px; margin: 0px;" />
															交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：601001<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：18元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：217300枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 1枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：217300枚<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：第十二届人民政协全国委员会第一次会议纪念封<br style="padding: 0px; margin: 0px;" />
															【邮票类型】 : 纪念封<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】 : 1.20元<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2013年3月3日<br style="padding: 0px; margin: 0px;" />
															【纪念封设计】：王晓红</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 中国人民政治协商会议第十二届全国委员会第一次会议于2013年3月3日在北京召开。为此，特发行纪念封1枚。<br style="padding: 0px; margin: 0px;" />
															&nbsp;<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
