{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪念币人民币收藏价值的背后：其实很多人都亏{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 00:52:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp; 近年来纪念币、人民币收藏市场越来越火，然而真的能升值吗、有收藏价值吗？</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">　 &nbsp;去年抗日战争纪念币、航天纪念币/钞、猴年纪念币等一系列纪念币的推出点燃了老百姓的投资热情，预约需要及早去抢，网点兑换往往也大排场龙。此外，前不久山东省部分城市一元纸币退出市场，试行用硬币代替，又激发出老百姓对于人民币的收藏热情。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">　　随着社会财富水平不断积累，很多人开始注重投资与收藏，因此近年来纪念币及人民币的收藏价值也被放大了很多。然而，很多人不懂收藏就盲目跟风入市，这种行为并不可取。有些纪念币、人民币的收藏价值非常有限，表面上看是升值了，但实际上却有可能亏损。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif, 宋体; font-size: 14px; line-height: 22px; text-indent: 2em;" />
<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">　　我们来看看过去发行的一些人民币及纪念币的升值情况。</span>
<div style="text-align: center;">
	<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;"><img alt="" src="/uploads/allimg/c161124/14O95HOFb0-W3W.jpg" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HOFb0-W3W_lit.jpg{/dede:field}
