{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}珍惜生命之水（ 600019）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<br />
<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<span style="color: rgb(105, 105, 105);"><strong>普通邮票&ldquo;珍惜生命之水&rdquo;（ 600019）</strong></span><br />
														交易参数：<br />
														【交易代码】：600019<br />
														【首日挂牌指导价】：8元/枚<br />
														【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：200000枚<br />
														【最小变动价位】： 0.01元<br />
														【最小提货数量】: 40枚<br />
														【市场流通量】：200000枚<br />
														【备注】：&nbsp;以整版自提<br />
														&nbsp;<br />
														藏品信息：<br />
														【藏品名称】：珍惜生命之水<br />
														【发行日期】：2002年4月1日<br />
														【面 &nbsp; &nbsp; &nbsp; 值】 : 0.80元<br />
														【整张枚数】：40枚<br />
														【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
														【邮票规格】：25&times;30毫米<br />
														【版 &nbsp; &nbsp; &nbsp; 别】：影写<br />
														【设 &nbsp;计 者】：张森、杨波<br />
														【发行机构】：中国邮政<br />
														【印&nbsp; 制&nbsp; 厂】：北京邮票厂<br />
														<br />
														藏品介绍：<br />
														2002年2月1日，我国发行了普30《保护人类共有的家园》（第一组）邮票二枚，邮票图案为地球形象，地球图案的一半为树木和蓝天中的白云，二枚邮票名称分别是保护森林和防治大气污染；同年4月1日，我国又发行了普30《保护人类共有的家园》（第二组）邮票四枚，同样是地球图案，邮票名称为珍惜生命之水、稳定低生育水平、珍惜矿产资源、保护海洋资源，反映了我国保护环境、合理利用资源和计划生育的基本国策；时隔两年我国又于2004年1月1日，发行了普30《保护人类共有的家园》（第三组）邮票二枚，邮票名称分别为防治荒漠化、保护生物多样性。&nbsp;&nbsp;<br />
														风险分析：<br />
														各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
