<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","想要成功拥有财富，必先拥有“坚持”到底恒心",89,190);
$z[2][4]['name']="title";
$z[3]=Array("field","",192,231);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",233,283);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-07 00:05:00 &nbsp",285,350);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">很多事情尽管我们已经作出了正确和勇敢的决策，但如果没有耐力与恒心是不会成功的。</span>",352,711);
$z[6][4]['name']="body";
$z[7]=Array("field","",713,752);
$z[7][4]['name']="litpic";

?>