{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}想要成功拥有财富，必先拥有“坚持”到底恒心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-07 00:05:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">很多事情尽管我们已经作出了正确和勇敢的决策，但如果没有耐力与恒心是不会成功的。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
