{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《建党九十周年》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-26 20:03:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将纪念邮票&nbsp;&ldquo;建党九十周年&rdquo;（以下简称&ldquo;建党九十周年&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：</span><br style="padding: 0px; margin: 0px;" />
										<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">&nbsp;一、 上市商品信息</strong><br style="padding: 0px; margin: 0px;" />
										&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61E922P-4D09.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px;" /><br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">二、上市交易</strong><br style="padding: 0px; margin: 0px;" />
										上市交易日期：2016年9月28日<br style="padding: 0px; margin: 0px;" />
										本公告解释权归宁夏西邮文化艺术品交易中心所有。<br style="padding: 0px; margin: 0px;" />
										特此公告!&nbsp;</span><br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										<div style="padding: 0px; margin: 0px; text-align: right;">
											<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
											2016年9月26日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61E922P-4D09_lit.jpg{/dede:field}
