{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于西邮所交易时间调整的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-12 15:27:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<br />
	<span style="padding: 0px; margin: 0px;">尊敬的经纪、交易会员：<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），随着文化商品品种及交易量的增加，为了给广大客户提供更加完善、便捷的交易服务，本中心经研究决定，自2016年9月19日(星期一）起上线周六交易。相关交易时间说明如下：<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;交易所交易时间：周一到周六</span><br style="padding: 0px; margin: 0px;" />
	<span style="padding: 0px; margin: 0px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 9:30-11:30，13:00-15:00<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;请广大客户知晓。<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;感谢您对交易中心的支持！<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;特此公告！</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
