{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普30 邮票“珍惜矿产资源”（ 600020）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<strong>普30 邮票&ldquo;珍惜矿产资源&rdquo;（ 600020）</strong><br />
														交易参数：<br />
														【交易代码】：600020<br />
														【首日挂牌指导价】：8元/枚<br />
														【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：200000枚<br />
														【最小变动价位】： 0.01元<br />
														【最小提货数量】: 40枚<br />
														【市场流通量】：200000枚<br />
														<br />
														藏品信息：<br />
														【藏品名称】：保护人类共有的家园（第二组）-珍惜矿产资源<br />
														【藏品志号】：普30<br />
														【面 &nbsp; &nbsp; &nbsp; 值】 : 0.3元<br />
														【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
														【邮票规格】：25&times;30mm<br />
														【齿孔度数】：13&times;13.5度<br />
														【整张枚数】：40枚<br />
														【发行日期】：2002年4月1日<br />
														【版 &nbsp; &nbsp; &nbsp; 别】：影写<br />
														【防伪方式】：蓝色防伪纤维纸、防伪荧光油墨、异性齿孔、无色荧光喷码<br />
														【设 计 &nbsp;者】：张森、杨波、方军、史渊<br />
														【发行机构】：中国邮政<br />
														【印刷单位】：北京邮票厂<br />
														<br />
														藏品介绍：<br />
														&nbsp; &nbsp; &nbsp; 中国是世界上为数不多的、矿产资源种类较齐全的、矿产自给程度较高的国家之一。一部分矿种(矿组)的储量名列世界前茅或首位。但人均占有量却低于世界水平。中国至少在50万年以前就开始利用矿产资源(见周口店古人类遗址)。在明代和更早的时期，对矿产资源的利用技术就居当时世界先进地位。19世纪后半叶，帝国主义以掠夺方式在中国开办矿山，因而自清朝末年开始，中国的矿产资源就处于这种半殖民地的地位被开发掠夺。但到1949年为止，中国探明一定储量的矿种仅有18种。<br />
														风险分析：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
