{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《青屿干线通车纪念》小型张藏品入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-26 15:51:25 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，1997年香港小型张 &ldquo;青屿干线通车纪念&rdquo;（以下简称&ldquo;青屿干线通车纪念&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><strong>入库藏品清单</strong></span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
