{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪念邮票“中国现代科学家”（ 600021）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px;" width="220">
				<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
					<tbody style="padding: 0px; margin: 0px;">
						<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
							<td style="padding: 0px; margin: 0px;">
								<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
									<tbody style="padding: 0px; margin: 0px;">
										<tr style="padding: 0px; margin: 0px;">
											<td style="padding: 0px; margin: 0px;">
												<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
													<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
														<br />
														<strong>纪念邮票&ldquo;中国现代科学家&rdquo;（ 600021）</strong><br />
														交易参数：<br />
														【交易代码】：600021<br />
														【首日挂牌指导价】：10元/枚<br />
														【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
														【单笔最大委托量】：200000枚<br />
														【最小变动价位】： 0.01元<br />
														【最小提货数量】: 6枚<br />
														【市场流通量】：200000枚<br />
														【备注】：&nbsp;以整套自提<br />
														&nbsp;<br />
														藏品信息：<br />
														【藏品名称】：《中国现代科学家（六）》纪念邮票<br />
														【藏品志号】：2014-25<br />
														【图案面值】<br />
														（6-1）J王淦昌&nbsp;&nbsp; 1.20元<br />
														（6-2）J赵九章 &nbsp;&nbsp;1.20元<br />
														（6-3）J郭永怀&nbsp;&nbsp; 1.20元<br />
														（6-4）J邓稼先&nbsp;&nbsp; 1.20元<br />
														（6-5）J朱光亚&nbsp;&nbsp; 1.20元<br />
														（6-6）J王 选 &nbsp; &nbsp; 1.20元<br />
														【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
														【邮票规格】：30&times;50mm<br />
														【齿孔度数】：13.5度<br />
														【整张枚数】：16枚<br />
														【整张规格】：146&times;240毫米<br />
														【发行日期】：2014年10月16日<br />
														【版 &nbsp; &nbsp; &nbsp;别】：影写<br />
														【防伪方式】：防伪纸张、防伪油墨、异形齿孔、荧光喷码<br />
														【设 计 &nbsp;者】：毕建勋<br />
														【资料提供】：清华大学<br />
														【责任编辑】：董研<br />
														【发行机构】：中国邮政<br />
														【印刷单位】：北京邮票厂<br />
														<br />
														藏品介绍：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;2014年10月16日发行《中国现代科学家（六）》纪念邮票1套6枚，图案分别为： 核物理学家王淦昌、气象学家、地球物理学家赵九章 、物理学家郭永怀、核物理学家邓稼先、核物理学家朱光亚和计算机技术专家王选；<br />
														&nbsp; &nbsp; &nbsp; &nbsp;王淦昌（两弹一星元勋），1907年5月28日出生，江苏常熟人，两弹一星元勋，中国实验原子核物理、宇宙射线及基本粒子物理研究的主要奠基人和开拓者，在国际上享有很高的声誉，被誉为&ldquo;中国核武器之父&rdquo;、&ldquo;中国原子弹之父&rdquo;。1929年毕业于清华大学物理系，1933年于德国柏林大学获博士学位。1936年~1952年，王淦昌在浙江大学任教，先后任物理系教授、系主任，在浙大度过了他一生中最美好的16年，并培养了李政道、叶笃正、程开甲等一大批优秀的科学家。在70年科研生涯中，他奋力攀登，取得了多项令世界瞩目的科学成就。1998年12月10日21时48分，王淦昌因病在北京逝世，享年91岁。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;赵九章（1907年10月15日----1968年10月26日），浙江湖州市吴兴人，毕业于河南留学欧美预备学校（今河南大学）。 中科院院士，著名的科学家、气象学家、地球物理学家和空间物理学家。为中国人造卫星事业做出杰出的贡献。赵九章是中国著名科学家，&ldquo;651&rdquo;卫星设计院院长。为中国第一颗人造卫星上天做出过巨大贡献。然而在&ldquo;文革&rdquo;那个混乱的年代里，面对现实，他无力承受从未见过的人身攻击。于是，他用自己的鲜血和生命给自己写了一张&ldquo;大字报&rdquo;，名字就叫：自杀！<br />
														&nbsp; &nbsp; &nbsp; &nbsp;郭永怀（1909年4月4日&mdash;1968年12月5日），男，山东荣成人，中共党员。著名力学家、应用数学家、空气动力学家，中国科学院学部委员，近代力学事业的奠基人之一。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;邓稼先（1924年6月25日&mdash;1986年7月29日），安徽怀宁人，中国著名核物理学家，中国科学院院士。历任中国科学院近代物理研究所助理研究员、原子能研究所副研究员，核工业部第九研究院院长，核工业部科技委员会副主任，国防科学工业委员会科技委员会副主任，中科院数学物理学部委员，中国核学会第一、二届常务理事。曾参加组织和领导我国核武器的研究、设计工作，是我国核武器理论研究工作的奠基者之一，是中国核武器研制与发展的主要组织者、领导者，被称为&ldquo;两弹一星元勋&rdquo;。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;朱光亚（1924年12月25日---2011年2月26日），汉族，湖北武汉人。美国密执安大学研究生院物理系原子核物理专业研究生毕业，我国核科学事业的主要开拓者之一，中国科学院、中国工程院资深院士，中国科学技术协会名誉主席、原主席，中国工程院原院长、党组书记，中国人民政治协商会议第八届、九届全国委员会副主席。2011年，荣膺感动中国人物。1997年后担任南京大学校友总会名誉董事长。吉林大学物理学的奠基人之一。2002年5月， 获南京大学&ldquo;世纪校友学术成就金质奖章&rdquo;。<br />
														&nbsp; &nbsp; &nbsp; &nbsp;王选（1937年2月5日－2006年2月13日）生于上海，江苏无锡人，中国科学院院士，中国工程院院士，第三世界科学院院士，北京大学教授。他是汉字激光照排系统的创始人和技术负责人。他所领导的科研集体研制出的汉字激光照排系统为新闻、出版全过程的计算机化奠定了基础，被誉为&ldquo;汉字印刷术的第二次发明&rdquo;。<br />
														风险分析：<br />
														&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
														特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
