<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/2016/1118/378.html",61,166);
$z[2]=Array("keywordtrim","",168,205);
$z[3]=Array("descriptiontrim","",207,252);
$z[4]=Array("item","\r\n   {dede:match}<div class=\"nDTitle\">[内容]</div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",254,428);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",428,568);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match};来源：[内容];{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",568,727);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}<div class=\"nDInfos\">发布时间：[内容];{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",727,913);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"nDContent\">[内容]</div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",913,1090);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>