{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}宁夏西邮商品发售交易规则（暂行）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<br />
										<strong style="padding: 0px; margin: 0px;">商品发售交易规则（暂行）</strong><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第一章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">总则</strong><br style="padding: 0px; margin: 0px;" />
										第一条、为规范宁夏西邮文化艺术品交易中心（以下简称&ldquo;本中心&rdquo;）发售交易行为，维护本中心交易秩序，保护会员合法权益，根据《中华人民共和国物权法》、《中华人民共和国电子签名法》、《中华人民共国合同法》等法律法规，制定本交易规则。<br style="padding: 0px; margin: 0px;" />
										第二条、凡参与本中心发售交易的会员都必须遵守本规则。<br style="padding: 0px; margin: 0px;" />
										第三条、凡在本中心交易的挂牌商品都适用本规则。<br style="padding: 0px; margin: 0px;" />
										第四条、本中心发售交易流程包括挂牌申请、鉴定托管、挂牌发售等若干环节。<br style="padding: 0px; margin: 0px;" />
										第五条、会员参与本中心发售交易须本着自愿、有偿、诚实信用的精神，遵守国家相关法律法规及本中心的业务规则。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第二章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">会员</strong><br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第一节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">会员类别</strong><br style="padding: 0px; margin: 0px;" />
										第六条、本中心采用会员制，非会员不得在本中心参与交易。参与本中心发售交易，须事先按照相关规定申请成为本中心会员。<br style="padding: 0px; margin: 0px;" />
										第七条、本中心会员分为经纪会员和会员。<br style="padding: 0px; margin: 0px;" />
										第八条、经纪会员可以从事以下业务：<br style="padding: 0px; margin: 0px;" />
										1）自营发售、交易；<br style="padding: 0px; margin: 0px;" />
										2）在商品鉴定、托管、入库、入场、挂牌、征集、再托管等各个环节为会员提供综合经纪服务；<br style="padding: 0px; margin: 0px;" />
										3）本中心规则制度准许的其他业务。<br style="padding: 0px; margin: 0px;" />
										第九条、会员可以在本中心从事以下业务：<br style="padding: 0px; margin: 0px;" />
										1）发售、交易；<br style="padding: 0px; margin: 0px;" />
										2）本中心规则制度准许的其他业务。<br style="padding: 0px; margin: 0px;" />
										&nbsp;<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第二节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">会员账户</strong><br style="padding: 0px; margin: 0px;" />
										第十条、本中心一个会员对应一个会员账户。<br style="padding: 0px; margin: 0px;" />
										第十一条、本中心实行会员资金银行监管，会员须在本中心指定的银行开设资金账户，并开通银行与本中心的绑定业务；同时，在本中心进行交易的商品必须托管入库至本中心指定仓库中；&nbsp;<br style="padding: 0px; margin: 0px;" />
										第十二条、会员同意本中心按照会员的交易申请和电子合同结算每一笔交易，包括划拨资金、支付费用和调整商品持有量。<br style="padding: 0px; margin: 0px;" />
										第十三条、本中心提供电子版的交易账户结算单。<br style="padding: 0px; margin: 0px;" />
										第十四条、会员的资金可以在交易账户和银行资金账户间自由划拨，费用自理。本中心对于资金划拨有监管的责任和权利，对于因资金监管导致的资金划拨延迟，会员需自行承担由此产生的相关后果。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第三节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">会员管理</strong><br style="padding: 0px; margin: 0px;" />
										第十五条、会员必须遵守国家法规和本中心规则制度，接受有关行政管理部门和本中心的管理与监督，遵守社会公共道德、严格自律、自觉维护正常的交易和交收秩序，认真履行应尽职责，充分行使享有的合法权利，自觉维护会员的合法权益和本中心的声誉。<br style="padding: 0px; margin: 0px;" />
										第十六条、会员应根据国家法律法规和本中心规则制度自行申报和缴纳应承担的各项税费。<br style="padding: 0px; margin: 0px;" />
										第十七条、会员在任何情况下不代表本中心。会员与经纪会员之间的关系为相互自愿的合约关系。<br style="padding: 0px; margin: 0px;" />
										第十八条、针对经纪会员的不专业行为，会员有权向本中心投诉。本中心会在5个工作日内给予答复。<br style="padding: 0px; margin: 0px;" />
										第十九条、本中心有权对会员的业务开展情况进行监督检查指导，并对会员违反国家法规或本中心规则制度的行为，视其行为性质和情节严重程度，可以对其采取警告、通报批评、限期整改、暂停交易等一项或多项措施，情节严重的，还可以采取限制交易、暂停或终止其会员资格，涉嫌犯罪的，依法移送至司法机关处理。<br style="padding: 0px; margin: 0px;" />
										第二十条、会员若对本中心的处理决定不服，有权自收到处理决定后15个工作日内，以书面形式向本中心提请复议。对于会员的复议申请，本中心受理并做出决定。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第三章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">发售</strong><br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第一节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">商品</strong><br style="padding: 0px; margin: 0px;" />
										第二十一条、国家允许流通的商品均可在本中心进行交易。<br style="padding: 0px; margin: 0px;" />
										第二十二条、在本中心进行发售的商品会有若干个交易品种，交易品种等级录入发售目录。本中心实行挂牌商品登记制度，全部商品必须按目录指定的编号登记后方可交易。<br style="padding: 0px; margin: 0px;" />
										第二十三条、每个商品条目包括交易品种名称、代码、交易单位和加价幅度，交易单位如、&ldquo;枚&rdquo;、&ldquo;套&rdquo;等。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第二节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">挂牌申请</strong><br style="padding: 0px; margin: 0px;" />
										第二十四条、会员应委托本中心经纪会员向本中心提出挂牌申请。会员和经纪会员须向本中心提交《委托挂牌代理协议》、《挂牌申请书》、《商品投资报告》、《持有人承诺书》等相关文件。<br style="padding: 0px; margin: 0px;" />
										第二十五条、会员向本中心提交挂牌申请，视为其接受本中心的各项交易条款和会员的权利与义务。<br style="padding: 0px; margin: 0px;" />
										第二十六条、经纪会员提供发售商品的《商品投资报告》，包括但不仅限于该商品的合法性、市场规模、市场趋势、投资价值研究和由专业人员签发的商品价值评估报告。<br style="padding: 0px; margin: 0px;" />
										第二十七条、《商品投资报告》仅供会员参考，不能作为本中心对该商品投资前景的承诺或认可。<br style="padding: 0px; margin: 0px;" />
										第二十八条、申请挂牌流通的商品市值不得低于人民币200万元。<br style="padding: 0px; margin: 0px;" />
										第二十九条、本中心收到挂牌申请后，于五个工作日内进行初步审核，合格后组织本中心专家委员会评审，评审通过后经本中心挂牌审核小组复审，通过后本中心将向挂牌申请人出具挂牌申请回执。<br style="padding: 0px; margin: 0px;" />
										第三十条、对于本中心公告的公开征集发售商品名单中的品种，经本中心挂牌审核小组审核同意后，该商品可直接进入挂牌托管流程，当托管市值达到交易规则要求即可挂牌上市交易。<br style="padding: 0px; margin: 0px;" />
										第三十一条、商品经本中心相关部门审核通过后，本中心将在官网上发布公告,进入发售商品目录。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第三节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">入场登记</strong><br style="padding: 0px; margin: 0px;" />
										第三十二条、持有本中心挂牌商品的会员，在本中心发布托管公告后，可以在公告限定的托管日前通过书面或交易客户端向本中心提出入场登记申请。书面申请须提交以下文件：《入场登记申请书》、《持有人承诺书》、《委托入场登记协议》，如会员委托他人代为办理入场登记事项，还需递交《授权委托书》以及受托人身份证明；通过交易客户端提交申请的，须确认阅读、理解、接受《持有人承诺书》的所有条款，并补交上述书面资料。<br style="padding: 0px; margin: 0px;" />
										第三十三条、会员办理完托管手续后的两个交易日内，须将挂牌费通过交易客户端支付至交易中心，在规定时间内未支付挂牌费的，每延期一日收取挂牌商品市值0.1%的滞纳金。<br style="padding: 0px; margin: 0px;" />
										第三十四条、申请入市的商品经专业机构或行业内专家鉴定合格，方可进入本中心指定的托管库。鉴定费现场收取，凭交款凭证进行商品鉴定；对经鉴定后不符合要求的商品，不准进入托管库，退还挂牌申请人。退还过程中所出现商品的损耗、损失由申请方自行承担。<br style="padding: 0px; margin: 0px;" />
										第三十五条、申请挂牌商品经本中心组织鉴定后，本中心出具《鉴定托管单》并于指定时间内将托管入库量转为挂牌申请人的交易账户内的商品持有量。<br style="padding: 0px; margin: 0px;" />
										第三十六条、申请挂牌的会员的交易账户中生成商品代码与实际持有数量后，该实际持有量对应的各种权益即转移到申请挂牌会员交易账户中。&nbsp;<br style="padding: 0px; margin: 0px;" />
										第三十七条、会员办理商品入库托管必须经其法定代表人或其委托代理人签字确认并加盖公章。<br style="padding: 0px; margin: 0px;" />
										第三十八条、托管流程完成后，本中心将及时发布商品托管入库公告。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第四节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">再托管</strong><br style="padding: 0px; margin: 0px;" />
										第四十条、已挂牌商品在达到再托管条件时方可启动再托管程序，本中心将在官网发布再托管公告。<br style="padding: 0px; margin: 0px;" />
										第四十一条、在本中心发布相关商品再托管公告时，申请人可委托本中心经纪会员向本中心提出二次托管申请。申请时须向本中心提交《托管申请书》及《持有人承诺书》。<br style="padding: 0px; margin: 0px;" />
										第四十二条、再托管规则如下：<br style="padding: 0px; margin: 0px;" />
										1）现货基准价：本中心综合考虑挂牌商品鉴定、存储、托管费用等各种因素后，将依托市场信息采集员采集每个交易日挂牌商品的各地区及专业网站现货市场报价，并综合现货市场报价之均价乘以130%作为现货基准价；<br style="padding: 0px; margin: 0px;" />
										2）风险警示：当挂牌品种线上5日均价有效超过现货基准价且超出部分达现货基准价的100%时，本中心将进行风险警示，发布风险提示公告；<br style="padding: 0px; margin: 0px;" />
										3）再托管：当挂牌商品线上5日均价有效超过现货基准价且超出部分达现货基准价的150%时，本中心将发布再托管公告，对该挂牌商品进行再托管；<br style="padding: 0px; margin: 0px;" />
										4）再托管总量：再托管公告中将明确再托管商品总量。再托管商品总量和具体比例由本中心挂牌审核小组裁定，另发布公告；<br style="padding: 0px; margin: 0px;" />
										第四十三条、挂牌商品持有人可向本中心申请再托管商品份额，经超过60%流通量的持有人同意时，本中心有权根据该商品的交易情况和相关市场情况决定是否针对该商品进行再托管份额。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第四章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">发行申购</strong><br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第一节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">申购原则</strong><br style="padding: 0px; margin: 0px;" />
										第四十四条、进入本中心发售目录的新商品，会员可通过系统进行申购。<br style="padding: 0px; margin: 0px;" />
										第四十五条、申购委托在申购日冻结资金前可以调整申购数量及资金，同时也要遵守本中心在申购日发出的调整公告。<br style="padding: 0px; margin: 0px;" />
										第四十六条、申购挂牌商品须全额预缴申购款及申购手续费。申购抽签结束后，未中签申购款及相应申购手续费将退还至会员账户。<br style="padding: 0px; margin: 0px;" />
										第四十七条、挂牌商品申购日期以本中心公告为准。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第二节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">申购价</strong><br style="padding: 0px; margin: 0px;" />
										第四十八条、申购价即为本中心确定的挂牌商品基准价。<br style="padding: 0px; margin: 0px;" />
										第四十九条、挂牌商品基准价由本中心根据经纪会员推荐挂牌价、专家委员会综合评审价、专业市场现货均价综合考虑制定。<br style="padding: 0px; margin: 0px;" />
										1）经纪会员推荐挂牌价：由挂牌商品申请人与经纪会员协商制定；<br style="padding: 0px; margin: 0px;" />
										2）专家委员会综合评审价：由专家委员会评审小组依据《专家委员会评审规则》确定该商品在评审时可能实现的参考价值；<br style="padding: 0px; margin: 0px;" />
										3）专业市场现货均价：采集于专业现货市场，由本中心特约信息员按规定申报。专业市场现货均价为发布该商品托管公告之前一周现货市场平均价。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第三节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">申购时间</strong><br style="padding: 0px; margin: 0px;" />
										第五十条、会员可于申购日（以下简称T日）申购发行的新商品，申购时间为T日的9:30至11:30和13:00至15:00。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第四节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">申购流程</strong><br style="padding: 0px; margin: 0px;" />
										第五十一条、会员申购（T日）：会员在申购时间内缴足申购款，进行申购委托，申购委托提交后，申购款将被冻结。<br style="padding: 0px; margin: 0px;" />
										第五十二条、抽签（T+1日，非交易日则顺延）：本中心根据抽签规则进行抽签，并对抽签结果进行公布，对未中签部分的申购款予以解冻。<br style="padding: 0px; margin: 0px;" />
										第五十三条、挂牌交易（T+2日，非交易日则顺延）：挂牌上市交易。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第六章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">交易规则</strong><br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第一节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">交易时间</strong><br style="padding: 0px; margin: 0px;" />
										第五十四条、本中心交易日为每周一至周五，国家法定节假日和本中心公告的休市日除外。交易时间为交易日的上午9:30-11:30，下午13:00-15:00。交易期间因故停市，不作顺延。<br style="padding: 0px; margin: 0px;" />
										第五十五条、公告另有规定的，交易时间以公告为准。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第二节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">交易申请</strong><br style="padding: 0px; margin: 0px;" />
										第五十六条&nbsp;&nbsp;交易指令应当在交易时间内发出，在非交易时间，交易系统不接受交易指令，交易指令当日交易时间段内有效。如果交易指令不能一次性全部成交，未成交的部分继续参加当日的交易。<br style="padding: 0px; margin: 0px;" />
										第五十七条&nbsp;&nbsp;交易指令是会员发出的要约，一旦成交，会员必须履行相应的义务。<br style="padding: 0px; margin: 0px;" />
										第五十八条&nbsp;&nbsp;交易指令应包括交易商品代码、名称、交易数量和交易价格等。<br style="padding: 0px; margin: 0px;" />
										第五十九条&nbsp;&nbsp;买入指令。当会员提交购买指令时，应保证交易账户内有足够的资金。系统会在交易指令有效期内，冻结相应的资金。资金在被冻结期间内将不得转出或做其他用途。<br style="padding: 0px; margin: 0px;" />
										第六十条&nbsp;&nbsp;卖出指令。当会员提交卖出指令时，应保证交易账户内有足够的商品持有量。系统会在交易指令有效期内，冻结相应数量的交易商品。商品在被冻结期间内不得用于其他交易或用途。<br style="padding: 0px; margin: 0px;" />
										第六十一条&nbsp;&nbsp;单笔交易最大数量原则上不超过本中心该挂牌商品市场流通量的1%。根据市场流通量的变化，本中心可适时调整单笔交易最大数量。<br style="padding: 0px; margin: 0px;" />
										第六十二条&nbsp;&nbsp;本中心对发售实行价格波动限制，新商品挂牌交易首日价格波动幅度最大为&plusmn;30%，次日起日价格波动幅度最大为&plusmn;10%。当日有效价格范围的计算方法为：当日参照价格&times;（1&plusmn;日价格波动幅度）。计算结果按照四舍五入原则取至价格最小变动单位。根据市场管理需要，本中心可以调整发售商品的日价格波动幅度。<br style="padding: 0px; margin: 0px;" />
										第六十三条&nbsp;&nbsp;开盘价为当日该商品的第一笔成交价格。收盘价为当日该商品交易时间内最后三分钟所有交易的成交量的平均价，最后三分钟无交易的，其收盘价为当日最后一笔成交价。<br style="padding: 0px; margin: 0px;" />
										第六十四条&nbsp;&nbsp;当日参照价格为该商品前一交易日的收盘价。<br style="padding: 0px; margin: 0px;" />
										第六十五条&nbsp;&nbsp;交易指令在被确认成交之前可以撤销，撤销指令应于交易时间内发出。未成交的交易指令于当日收盘后自动失效。。交易指令失效或被成功撤销后，与该交易指令对应的款项或商品将被自动解冻。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第三节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">电子合同</strong><br style="padding: 0px; margin: 0px;" />
										第六十六条、交易指令成交后，卖方与买方随即形成买卖合同关系，双方权利义务以系统自动生成的电子合同为准。<br style="padding: 0px; margin: 0px;" />
										第六十七条、电子合同的主要条款包括但不限于：合同编号、发售商品名称、发售商品代码、成交价格、成交数量、计价单位、交易时间、交易手续费等。<br style="padding: 0px; margin: 0px;" />
										第六十八条、电子合同以人民币计价，计价单位为元。<br style="padding: 0px; margin: 0px;" />
										第六十九条、买卖双方同意根据电子合同和相关交收规则的约定，卖方向买方转移商品的所有权，买方向卖方划转相对应的资金。<br style="padding: 0px; margin: 0px;" />
										第七十条、因不可抗力、意外事件、交易系统被非法侵入等原因造成严重后果的交易，本中心可以采取适当措施或认定无效。对显失公平的交易，经本中心研究认定后，可以采取适当措施进行处理。违反本规定相关条款，严重破坏市场正常运行的交易，本中心有权宣布取消，由此造成的损失由违规交易者承担。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第四节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">商品交收</strong><br style="padding: 0px; margin: 0px;" />
										第七十一条、商品交收须由会员或其委托代理人在本中心指定地点办理。<br style="padding: 0px; margin: 0px;" />
										第七十二条、申请商品交收的数量不得低于本中心规定的该商品最低交收数量。<br style="padding: 0px; margin: 0px;" />
										第七十三条、会员通过交易客户端提出商品交收申请：<br style="padding: 0px; margin: 0px;" />
										1）会员在每个交易日的9:30-11:30、13:00-15:00可通过交易客户端注册提货单，生成提货单后，提货单所对应的商品数量被锁定进入待交收状态，停止在系统上买卖。<br style="padding: 0px; margin: 0px;" />
										2）本中心线上审核提货申请，审核并确认后，安排进入提货流程。<br style="padding: 0px; margin: 0px;" />
										3）会员携提货单及其他材料，至本中心指定交收地办理提货。<br style="padding: 0px; margin: 0px;" />
										第七十四条、会员办理实物交收时所需的全套文件：&ldquo;提货单&rdquo;传真件（或打印件）、营业执照复印件（盖章）、商品交收授权委托书（盖章）、受托提货人的身份证原件与复印件。<br style="padding: 0px; margin: 0px;" />
										第七十五条、仓库办理交收的工作时间：本中心指定交收日的10:00-16:00。如有变动，以公告为准。<br style="padding: 0px; margin: 0px;" />
										第七十六条、会员提出交收申请后，进入&ldquo;商品提货单&rdquo;状态的商品数量将被锁定，会员有权在交易客户端对该提货单进行注销，注销后该&ldquo;商品提货单&rdquo;将被取消，其对应的商品数量将被解除锁定。<br style="padding: 0px; margin: 0px;" />
										第七十八条、&ldquo;商品提货单&rdquo;生成后，若在指定的交收时间内未办理商品交收业务，该&ldquo;商品提货单&rdquo;将作废。<br style="padding: 0px; margin: 0px;" />
										第七十九条、&ldquo;商品提货单&rdquo;作废的，其对应的商品仍被锁定，需要会员在交易客户端进行注销提货单以解除锁定。<br style="padding: 0px; margin: 0px;" />
										第八十条、对于单一交易日提货数量本中心将及时发布出库公告。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第五节</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">市场管理</strong><br style="padding: 0px; margin: 0px;" />
										第八十一条、在鉴定、托管、发行、认购、申购、挂牌、交易等各环节中，本中心发布的公告、指引、说明等均不构成投资建议，也不表明本中心就该等业务对会员做出了任何保证或承诺。<br style="padding: 0px; margin: 0px;" />
										第八十二条、为了维护市场的稳定，保护会员的利益，本中心可以对特定交易品种临时停牌。对于停牌原因和恢复交易的时间，本中心将予以公告。<br style="padding: 0px; margin: 0px;" />
										第八十三条、本中心在交易时间内发布交易即时行情和相关的行业新闻等辅助信息。<br style="padding: 0px; margin: 0px;" />
										第八十四条、本中心实行市场信息员信息采集制度，实现交易中心平台与全国各大专业市场价格联动。<br style="padding: 0px; margin: 0px;" />
										第八十五条、本中心实行风险警示制度。当本中心认为必要时，可以分别采取或同时采取要求会员报告情况、谈话提醒、书面警示、公开谴责、发布风险警示公告、暂停或限制交易、取消交易资格等措施中的一种或多种措施，以控制风险。<br style="padding: 0px; margin: 0px;" />
										第八十六条、本中心产生的交易信息归本中心所有，未经本中心许可，任何机构和个人不得使用和传播。<br style="padding: 0px; margin: 0px;" />
										第八十七条、经本中心许可使用交易信息的机构和个人，未经本中心同意，不得将本中心交易信息提供给其它机构和个人使用或予以传播。<br style="padding: 0px; margin: 0px;" />
										第八十八条、当出现由于不可抗力或计算机系统故障、网络故障等异常时，交易市场进入异常情况并暂停交易。<br style="padding: 0px; margin: 0px;" />
										第八十九条、本中心宣布交易市场进入异常情况并决定采取紧急措施后，将在第一可能的时间内予以公告。由于在市场异常情况下采取相应措施所造成的损失，本中心不承担任何责任。<br style="padding: 0px; margin: 0px;" />
										第九十条、本中心根据需要有权选择升级或更换交易系统，并有权要求会员配合本中心采取相应措施。因会员不配合造成的自身损失，本中心不承担任何责任。<br style="padding: 0px; margin: 0px;" />
										第九十一条、本中心升级或更换交易系统会及时进行公告。<br style="padding: 0px; margin: 0px;" />
										第九十二条、本交易规则中所述时间，以本中心交易系统显示的时间为准。<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">第七章</strong>&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">其他</strong><br style="padding: 0px; margin: 0px;" />
										第九十三条、本交易规则中提及的&ldquo;国家法规&rdquo;，是指中华人民共和国的法律、行政法规、地方性法规、部门规章、地方政府规章及其他规范性文件。<br style="padding: 0px; margin: 0px;" />
										第九十四条、本交易规则中提及的&ldquo;本中心规则制度&rdquo;，是指本中心制定、发布的交易规则、交易细则、会员管理办法、登记结算细则、交收细则、公告等所有管理规定、业务规则和制度性文件。<br style="padding: 0px; margin: 0px;" />
										第九十五条、本交易规则的最终解释权归本中心所有。本中心有权根据情况适时对本交易规则进行修订。<br style="padding: 0px; margin: 0px;" />
										第九十六条、本交易规则自发布之日起实施。{/dede:field}
{dede:field name='litpic'}{/dede:field}
