{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《牧牛图》藏品进行征集托管公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-17 17:30:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px; font-size: 14px;">为了满足市场需求，经本中心研究决定，对《 牧牛图》藏品进行征集托管工作，本次托管采用先申请后摇号的方式进行托管，托管后在本中心挂牌，公告如下：&nbsp;</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
