<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","《牧牛图》藏品进行征集托管公告",89,172);
$z[2][4]['name']="title";
$z[3]=Array("field","",174,213);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",215,265);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-06-17 17:30:00 &nbsp",267,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px; font-size: 14px;\">为了满足市场需求，经本中心研究决定，对《 牧牛图》藏品进行征集托管工作，本次托管采用先申请后摇号的方式进行托管，托管后在本中心挂牌，公告如下：&nbsp;</span>",334,810);
$z[6][4]['name']="body";
$z[7]=Array("field","",812,851);
$z[7][4]['name']="litpic";

?>