{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016S013《长江三峡》藏品申购公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-28 16:03:02 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种1994-18&nbsp;特种邮票&ldquo;长江三峡&rdquo;（以下简称&ldquo;长江三峡&rdquo;）进行定价发行申购。<br />
&nbsp; &nbsp; &nbsp; &nbsp;本次申购比例为：市值申购占可申购总量的0%，资金申购占可申购总量的100%。持仓市值参考为申购日结算后的实际市值。<br />
&nbsp; &nbsp; &nbsp; &nbsp;具体事项公告如下：<br />
一、申购藏品信息</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><img alt="" src="/uploads/allimg/c161124/14O95B3NU60-2Q92.jpg" style="width: 685px; height: 175px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95B3NU60-2Q92_lit.jpg{/dede:field}
