<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016S013《长江三峡》藏品申购公告",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",220,270);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-28 16:03:02 &nbsp",272,337);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种1994-18&nbsp;特种邮票&ldquo;长江三峡&rdquo;（以下简称&ldquo;长江三峡&rdquo;）进行定价发行申购。<br />\r\n&nbsp; &nbsp; &nbsp; &nbsp;本次申购比例为：市值申购占可申购总量的0%，资金申购占可申购总量的100%。持仓市值参考为申购日结算后的实际市值。<br />\r\n&nbsp; &nbsp; &nbsp; &nbsp;具体事项公告如下：<br />\r\n一、申购藏品信息</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O95B3NU60-2Q92.jpg\" style=\"width: 685px; height: 175px;\" /></span>",339,1185);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95B3NU60-2Q92_lit.jpg",1187,1274);
$z[7][4]['name']="litpic";

?>