<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《长江三峡》特种邮票藏品托管入库公告",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",230,280);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-19 17:38:00 &nbsp",282,347);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，1994-18特种邮票&ldquo;长江三峡&rdquo;（以下简称&ldquo;长江三峡&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"text-align: center;\">\r\n	<strong style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">入库藏品清单<br />\r\n	<img alt=\"\" src=\"/uploads/allimg/c161124/14O9554215VP-54P3.jpg\" style=\"width: 628px; height: 161px;\" /></strong>",349,1132);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O9554215VP-54P3_lit.jpg",1134,1222);
$z[7][4]['name']="litpic";

?>