<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016Z010《十二届人大政协封》藏品申购中签公告",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",232,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-11 10:25:00 &nbsp",284,349);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年10月&nbsp;10日对挂牌藏品十二届人大政协会议纪念封面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">&nbsp; &nbsp;&nbsp;</span><img alt=\"\" src=\"/uploads/allimg/c161123/14OXLc06320-1DD.jpg\" style=\"padding: 0px; margin: 10px; border: none; max-width: 700px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; width: 670px; height: 246px;\" />",351,1255);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXLc06320-1DD_lit.jpg",1257,1343);
$z[7][4]['name']="litpic";

?>