{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z014《青马大桥》藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-02 09:42:17 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年11月&nbsp;1日对挂牌藏品1997年香港青屿干线通车纪念小型张（青马大桥）面向所有投资人会员进行定价申购发行，具体事项公告如下：</span><br />
<br />
<div style="text-align: center;">
	<img alt="" src="/uploads/allimg/c161123/14OX611G14P-512S.jpg" style="width: 671px; height: 248px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX611G14P-512S_lit.jpg{/dede:field}
