<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016Z014《青马大桥》藏品申购中签公告",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",220,270);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-02 09:42:17 &nbsp",272,337);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年11月&nbsp;1日对挂牌藏品1997年香港青屿干线通车纪念小型张（青马大桥）面向所有投资人会员进行定价申购发行，具体事项公告如下：</span><br />\r\n<br />\r\n<div style=\"text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OX611G14P-512S.jpg\" style=\"width: 671px; height: 248px;\" />",339,832);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX611G14P-512S_lit.jpg",834,921);
$z[7][4]['name']="litpic";

?>