{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国邮政开办120周年纪念邮票发行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-23 00:16:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	3月20日是中国邮政开办120周年纪念日。记者在当日成都举办的纪念邮票首发式上了解到，当天发行的《中国邮政开办一百二十周年》纪念邮票1套4枚，图案内容分别为:信达天下、便民服务、速递物流、普惠金融，展示了百年邮政&ldquo;信达天下&rdquo;的历史使命和作为现代服务业集团 &ldquo;一体两翼&rdquo;的经营发展战略，全套邮票面值为4.80元。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	此外，中国邮政卡通形象&ldquo;雁雁&rdquo;也在当天正式亮相。&ldquo;雁雁&rdquo;以大雁为原型，表达了&ldquo;鸿雁传书&rdquo;的美好寓意，彰显出中国邮政&ldquo;情系万家，信达天下&rdquo;的内涵，展翅高飞的姿态象征着中国邮政 &ldquo;一体两翼&rdquo;大展宏图的美好前景。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
