{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《美丽中国》普32藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-12 14:30:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: justify;">
	<span style="padding: 0px; margin: 0px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2013癸巳年》普32邮票&ldquo;美丽中国&rdquo;（以下简称&ldquo;美丽中国&rdquo;）藏品已完成托管入库流程，详情见下表：</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
