{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z009《中国梦-人民幸福》藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-27 10:06:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年9&nbsp;月&nbsp;26日对挂牌藏品《中国梦-人民幸福》特种邮票（小全张）面向所有投资人会员进行定价申购发行，具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61FC4P-52L7.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 672px; height: 246px;" /><br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;单一品种单一账户中签总数&nbsp;＝&nbsp;单账号持仓市值&nbsp;&divide;&nbsp;参与申购交易会员总持仓市值&nbsp;&times;&nbsp;0%该品种可供申购总量&nbsp;＋&nbsp;单账户该品种申购资金&nbsp;&divide;&nbsp;该品种申购总资金&nbsp;&times;&nbsp;100%该品种可供申购总量＋&nbsp;随机分配数量。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 中签商品查询：登录西邮文化艺术品交易中心客户端查询（必须注册实盘账户）<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp;《中国梦-人民幸福》将于2016年9&nbsp;月28&nbsp;日正式挂牌交易，首日价格涨幅为30%，跌幅为30%。自2016年9&nbsp;月&nbsp;29日起上述藏品的正常交易日价格涨幅为10%，跌幅为10%。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 特别提醒：本中心入金时间：9:00&mdash;17:30（交易日）；出金时间：9:00&mdash;16:00（交易日）为保证出入金通道顺畅，请勿集中于9:00至10:00办理出入金业务，请合理安排您的出入金时间。<br style="padding: 0px; margin: 0px;" />
<br style="padding: 0px; margin: 0px;" />
特此公告！</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;二零一六年九月二十七日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61FC4P-52L7_lit.jpg{/dede:field}
