<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016Z013《珍惜生命之水》藏品申购中签公告",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",226,276);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-01 11:47:40 &nbsp",278,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年10月&nbsp;31日对挂牌藏品普通邮票珍惜生命之水面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><img alt=\"\" src=\"/uploads/allimg/c161123/14OX611A55P-4K30.jpg\" style=\"width: 670px; height: 244px;\" /></span>",345,828);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX611A55P-4K30_lit.jpg",830,917);
$z[7][4]['name']="litpic";

?>