{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D001号《牧牛图》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-27 17:37:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品：</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OXM1510520-11923.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 606px; height: 109px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM1510520-11923_lit.jpg{/dede:field}
