<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016S005《湖北风光A》藏品申购公告",89,178);
$z[2][4]['name']="title";
$z[3]=Array("field","",180,219);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",221,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-26 11:39:00 &nbsp",273,338);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">&nbsp;经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种邮资明信片湖北风光A组（以下简称&ldquo;湖北风光A&rdquo;）进行定价发行申购。</span>",340,876);
$z[6][4]['name']="body";
$z[7]=Array("field","",878,917);
$z[7][4]['name']="litpic";

?>