<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《中国现代科学家》藏品托管入库公告",89,184);
$z[2][4]['name']="title";
$z[3]=Array("field","",186,225);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",227,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-03 16:05:44 &nbsp",279,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，2014-25纪念邮票&ldquo;中国现代科学家&rdquo;（以下简称&ldquo;中国现代科学家&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><strong>入库藏品清单</strong></span>",346,825);
$z[6][4]['name']="body";
$z[7]=Array("field","",827,866);
$z[7][4]['name']="litpic";

?>