{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}贵金属纪念币的集藏价值{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 23:41:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1979年,中国人民银行在发行了中国第一套贵金属纪念币&mdash;&mdash;&ldquo;中华人民共和国成立三十周年&rdquo;纪念金币。贵金属纪念币的题材十分丰富,似浓缩了的百科全书,是历史文化发展的见证和再现。贵金属纪念币发行后,呈现出逐步沉淀的趋势,开辟了崭新的投资渠道。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	贵金属纪念币的集藏价值体现在以下几个方面:</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其一,权威性。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	贵金属纪念币的权威性表现在国家信用作保障。《中华人民共和国人民币管理条例》规定:&ldquo;纪念币是具有特定主题的限量发行的人民币,包括普通纪念币和贵金属纪念币。&rdquo;贵金属纪念币同流通人民币一样代表着国家,这是其他一切投资品所无法相比的。收藏和投资的贵金属纪念币亦不能像其他投资品般随意损坏,《中华人民共和国人民币管理条例》第四十三条&ldquo;故意毁损人民币的,由公安机关给予警告,并处1万元以下的罚款。&rdquo;贵金属纪念币从出生起就受到国家保护,是投资品中的个例。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其二,价值性。贵金属纪念币的材质主要是金、银、铂、钯等贵金属,自古便是人类财富的象征。马克思说:&ldquo;金银天然不是货币,但货币天然是金银&rdquo;。当前,黄金依然是公认的国际储备货币,仍具有价值尺度、流通手段、支付手段、储藏手段以及世界货币的职能,是不可或缺的投资工具,最可靠的资产、最稳定的财富储备方式。贵金属纪念币本体是货真价实的贵金属,凭借其自身价值,就值得人们去收藏、投资。除此之外,贵金属纪念币是限量发行的人民币,是当代的工艺品、收藏品,具有多重投资价值。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其三,独特艺术性。中国钱币拥有自己特色,是东方钱币文化的代表。贵金属纪念币继承了中国钱币特色,并不断吸收新鲜血液。贵金属纪念币在艺术上追求题材内容与艺术形式的结合,坚信&ldquo;只有民族的,才是世界的&rdquo;,坚持民族文化、传统文化和现代文化的表现手法相结合,在艺术上独树一帜。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其四,展示中华文化。贵金属纪念币题材涉及中国上下五千年历史,构成了丰富历史画卷,展现了中华文化精华。比如,长城、园林、民居世界遗产系列、名胜风光系列、石窟艺术系列、古代及近代名画系列、京剧艺术系列、古典文学名着系列、珍稀动物系列、航空航天系列、宗教文化系列、奥林匹克运动系列,等等。这些纪念币展现了中华民族悠久文化,发挥了教育作用。拓宽了集藏者知识面,提高了集藏者文化修养。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	其五,投资性。贵金属纪念币的权威性,保证了其流通中的真实性,绝少赝品,让投资者放心。目前,我国有贵金属纪念币爱好者数十万,既有投资超千万元的收藏家与投资者,也有只投入数百元的工薪族贵金属纪念币的爱好者。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	在收藏领域,书画、青铜器、玉器等收藏品都具有很高的历史、文化、科技内涵,对于集藏者、投资者的文化知识要求非常高,想要熟知、掌握相关知识,绝非一日之功,&ldquo;打眼&rdquo;者比比皆是。但贵金属纪念币,由于发展历史短,品种相对集中,发行量、工艺技术等非常透明,有利于集藏者、投资者更好地完成知识储备,实现理性投资。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
