{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}无论干什么，选对平台很重要{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-04 09:33:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">我们经常听说一句话&ldquo;有能力的人在哪儿都一样，是金子在哪儿都发光。&rdquo;但是事实并不是总朝着我们希望的方向发展，选对了平台对一个人的职场发展至关重要。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
