<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","无论干什么，选对平台很重要",89,166);
$z[2][4]['name']="title";
$z[3]=Array("field","",168,207);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",209,259);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-04 09:33:00 &nbsp",261,326);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">我们经常听说一句话&ldquo;有能力的人在哪儿都一样，是金子在哪儿都发光。&rdquo;但是事实并不是总朝着我们希望的方向发展，选对了平台对一个人的职场发展至关重要。</span>",328,794);
$z[6][4]['name']="body";
$z[7]=Array("field","",796,835);
$z[7][4]['name']="litpic";

?>