{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普22 “黄果树瀑布”（ 600010）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-06 16:39:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">普22 &ldquo;黄果树瀑布&rdquo;(600010)</strong></span></span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">交易参数：<br style="padding: 0px; margin: 0px;" />
【交易代码】：600010<br style="padding: 0px; margin: 0px;" />
【首日挂牌指导价】：10元/枚<br style="padding: 0px; margin: 0px;" />
【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
【单笔最大委托量】：100000枚<br style="padding: 0px; margin: 0px;" />
【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
【最小提货数量】: 100枚<br style="padding: 0px; margin: 0px;" />
【市场流通量】：100000枚<br style="padding: 0px; margin: 0px;" />
【备注】：&nbsp;以整版自提</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
【藏品名称】：普22黄果树瀑布<br style="padding: 0px; margin: 0px;" />
【藏品分类】：版票<br style="padding: 0px; margin: 0px;" />
【藏品志号】：普22<br style="padding: 0px; margin: 0px;" />
【面 &nbsp; &nbsp; &nbsp;值】 : 3分<br style="padding: 0px; margin: 0px;" />
【材 &nbsp; &nbsp; &nbsp;质】 : 纸质<br style="padding: 0px; margin: 0px;" />
【邮票规格】：26&times;31mm<br style="padding: 0px; margin: 0px;" />
【整张枚数】：100枚<br style="padding: 0px; margin: 0px;" />
【发行日期】：1981年9月1日<br style="padding: 0px; margin: 0px;" />
【版 &nbsp; &nbsp; &nbsp;别】：影写版<br style="padding: 0px; margin: 0px;" />
【设 计 &nbsp;者】：陈晓聪、姜伟杰<br style="padding: 0px; margin: 0px;" />
【发行机构】：中国邮政<br style="padding: 0px; margin: 0px;" />
【印刷单位】：北京邮票厂</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 中国历史悠久，地域辽阔，地形多样，气候温和，河湖众多，海岸漫长，风光秀丽。 　&nbsp;<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 中国以山多著称于世，有世界上最高的山峰----珠穆朗玛峰，　终年积雪的山峰更是不计其数。中国有五岳：山东泰山、陕西华山、山西恒山、湖南衡山、河南嵩山；有佛教四大名山：四川峨眉山、山西五台山、安徽九华山、浙江普陀山；还有集天下名山之大成的安徽黄山，有白雪、绿林相间的吉林长白山、新疆天山。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 中国江、河、湖、泊、溪、泉、池、涧众多，长江三峡、黄河天险、新疆天池、贵州黄果树瀑布、海南天涯海角、河北北戴河等等，都是驰名中外的风景胜地。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 中国岩溶地貌类型繁多，是世界上岩溶地貌发育最典型的地区之一，也是世界上岩溶面积最大的国家。著名风景胜地有桂林山水、广东七星岩等等。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 本套邮票共5枚，展现了中国各地的五处风景胜地，其中有历史古迹，如万里长城；但更多的是自然风光，如天山、黄果树瀑布；既有热带风光，如海南风光；又有塞北风光，如东北林海。设计者精选了中国风光之精粹，浓缩于方寸之间。在构图上，设计者善于先取各地风光最具特色者，或浓或淡，或简或繁，或密或疏，使整套邮票的布局错落有致，既各自成趣，又浑然一体。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 普22甲与普22的区别，就是普22甲有磷光条杠。拿着票对着光源，在一定角度下可以看见数条垂直贯穿票面的磷光条杠。其中4分票有2条杠。<br style="padding: 0px; margin: 0px;" />
风险分析：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
特此提示</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
