{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《澳门中国书法》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-26 11:29:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将小版票2000-3-23-S004&nbsp;&ldquo;澳门中国书法&rdquo;（以下简称&ldquo;澳门中国书法&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">一、&nbsp;上市商品信息</strong></span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OX6152XN0-15927.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 580px; height: 502px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX6152XN0-15927_lit.jpg{/dede:field}
