<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","西邮所约你，来吗？",89,154);
$z[2][4]['name']="title";
$z[3]=Array("field","",156,195);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",197,247);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-05 10:33:00 &nbsp",249,314);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">&nbsp; &nbsp; &nbsp; 法国邮政发行2016年法国欧洲杯足球赛纪念邮票和小版张各一枚，发行量分别120万枚和26.5万枚。目前这套世足赛首发邮票升值很快，最新价已达到4000元人民币。</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O95FRHc0-1E32.jpg\" style=\"width: 690px; height: 351px;\" /></span><br />\r\n	<strong style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 153); font-family: 微软雅黑, 宋体; font-size: 18px; line-height: 32px; text-indent: 28px;\">2016年法国欧洲杯纪念邮票</strong>",316,1203);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95FRHc0-1E32_lit.jpg",1205,1291);
$z[7][4]['name']="litpic";

?>