{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西邮所约你，来吗？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-05 10:33:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp; 法国邮政发行2016年法国欧洲杯足球赛纪念邮票和小版张各一枚，发行量分别120万枚和26.5万枚。目前这套世足赛首发邮票升值很快，最新价已达到4000元人民币。</span>
<div style="text-align: center;">
	<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;"><img alt="" src="/uploads/allimg/c161124/14O95FRHc0-1E32.jpg" style="width: 690px; height: 351px;" /></span><br />
	<strong style="padding: 0px; margin: 0px; color: rgb(51, 51, 153); font-family: 微软雅黑, 宋体; font-size: 18px; line-height: 32px; text-indent: 28px;">2016年法国欧洲杯纪念邮票</strong>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95FRHc0-1E32_lit.jpg{/dede:field}
