{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《牧牛图》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-08 23:45:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将&ldquo;牧牛图(1997年中国邮政贺年（有奖）明信片获奖纪念)&rdquo;（以下简称牧牛图）藏品在本中心正式发行和上市交易，具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">一、上市商品信息</strong></span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OXA555cP-11c2.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 574px; height: 468px;" /></strong></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXA555cP-11c2_lit.jpg{/dede:field}
