{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国邮政发行《中国邮政开办一百二十周年》纪{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 12:55:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<img alt="" src="/uploads/allimg/c161124/14O95GH04O0-3U51.jpg" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国邮政定于2016年3月20日发行《中国邮政开办一百二十周年》纪念邮票1套4枚，图案内容分别为:信达天下、便民服务、速递物流、普惠金融，全套邮票面值为4.80元。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1896年3月20日,清代国家邮政成立,宣告了全民性邮政服务在中国的诞生。民国时期的中华邮政确立了&ldquo;常、妥、速&rdquo;的经营理念。中国共产党领导的人民邮政从战争年代开始至今就一直履行邮政普遍服务义务，对于维护国家统一和民族团结作出巨大贡献。党的十八大以来，中国邮政全面深化改革，加快转型升级，综合能力不断提升，业务领域不断拓宽，已经发展成为经营邮政基础性业务、金融、速递物流及电子商务的现代服务业集团。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	该套邮票由邵立辰、马骥设计，邮票画面将邮政历史和现实融合，突出表现邮政的时代风采。第一图，信达天下，选用清代邮政天津局旧址、古代驿使雕塑、邮政自行车、邮筒等元素，展现了百年邮政的历史画卷，传递了中国邮政&ldquo;信达天下&rdquo;的历史使命。第二图，便民服务，选用邮政服务大厅、便民服务站、易邮柜等元素，表现了中国邮政努力践行&ldquo;便民服务&rdquo;的理念。第三图，速递物流，选用现代化速递物流集散中心、邮运汽车、飞机等元素，突显中国邮政速递物流方便快捷、安全可靠的形象。第四图，普惠金融，选用邮政储蓄银行营业厅、ATM机，邮政银行卡（借记卡和信用卡）、中邮保险形象等元素，传达&ldquo;进步 与您同步&rdquo;的服务理念，凸显&ldquo;普惠金融&rdquo;的行业使命。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	该套在印制上采用高精度胶印和局部冷烫工艺相结合，由河南省邮电印刷厂印制。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	为配合中国邮政120周年纪念活动，采用&ldquo;年年有余&rdquo;和&ldquo;喜临门&rdquo;邮票印制发行小全张一枚，由北京邮票厂印制。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	注：此文属于人民网登载的商业信息，文章内容不代表本网观点，仅供参考。<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GH4220-4P41.jpg" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GH46460-54b9.jpg" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GH4a60-613S.jpg" style="width: 500px; height: 305px;" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GHJ930-O200.jpg" style="width: 500px; height: 314px;" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GHNI0-U200.jpg" style="width: 500px; height: 312px;" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GHU540-91K1.jpg" style="width: 500px; height: 313px;" /><br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95GH92330-1060B.jpg" style="width: 500px; height: 312px;" /></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GH04O0-3U51_lit.jpg{/dede:field}
