<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","《三国演义（第三组）》藏品上市的公告",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",224,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-12 15:33:00 &nbsp",276,341);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将特种邮票&nbsp;1992-9&nbsp;中国古典文学名著《三国演义（第三组）》（以下简称&ldquo;三国演义（第三组）&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：<br style=\"padding: 0px; margin: 0px;\" />\r\n<strong style=\"padding: 0px; margin: 0px;\">一、&nbsp;上市商品信息</strong></span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OXM02D320-45026.jpg\" style=\"padding: 0px; margin: 10px; border: none; max-width: 700px; width: 583px; height: 522px;\" />",343,1415);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OXM02D320-45026_lit.jpg",1417,1505);
$z[7][4]['name']="litpic";

?>