{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《三国演义（第三组）》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-12 15:33:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将特种邮票&nbsp;1992-9&nbsp;中国古典文学名著《三国演义（第三组）》（以下简称&ldquo;三国演义（第三组）&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">一、&nbsp;上市商品信息</strong></span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<img alt="" src="/uploads/allimg/c161123/14OXM02D320-45026.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 583px; height: 522px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM02D320-45026_lit.jpg{/dede:field}
