{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}1998有奖明信片“峡谷雄风图”（ 002005）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><strong style="padding: 0px; margin: 0px;">1998</strong><strong style="padding: 0px; margin: 0px;">中国邮政贺年有奖明信片&ldquo;峡谷雄风图&rdquo;(002005)</strong></span><br style="padding: 0px; margin: 0px;" />
															交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：002005<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：2元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：310000张<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 1张<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：310000张<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整张自提</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：峡谷雄风图 1998中国邮政贺年（有奖）明信片获奖纪念张<br style="padding: 0px; margin: 0px;" />
															【邮票类型】 : 获奖纪念张<br style="padding: 0px; margin: 0px;" />
															【发行日期】：1998年<br style="padding: 0px; margin: 0px;" />
															【发 行 &nbsp;量】：300万<br style="padding: 0px; margin: 0px;" />
															【图画规格】：60mm&times;90mm<br style="padding: 0px; margin: 0px;" />
															【纪念张规格】：92mm&times;140mm<br style="padding: 0px; margin: 0px;" />
															【全套枚数】：1枚<br style="padding: 0px; margin: 0px;" />
															【设 &nbsp; &nbsp; &nbsp; 计】：王志奇<br style="padding: 0px; margin: 0px;" />
															【发行机构 】：中国邮政总公司<br style="padding: 0px; margin: 0px;" />
															【印 &nbsp;制 &nbsp;厂】：河南省邮电印刷厂<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;峡谷雄风图是中国邮政1998年贺年有奖明信片专用兑奖邮品，图案雄伟，设计精美。自1992年来成系列发行至今，市场认知度较高。由于当时兑奖消耗巨大，历经18年沉淀，其中2000年至2006年国家邮政先后6次，采用盖销，打孔，化浆，焚烧等多种方法销毁了库存积压的邮品，总价值超过了230亿元。导致目前存世量很小，原箱原包货源极度匮乏，目前市场价200元有成交，全品相符合上市要求的货源存世无几。全品无瑕疵,原胶全品,有齿孔，控盘量极高，持有量国内第一。<br style="padding: 0px; margin: 0px;" />
															&nbsp;<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
