{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《江苏风光A》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-27 17:32:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61K920P-210P.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 639px; height: 115px;" /><br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 藏品发起人欲引入战略投资人故申请临时停牌，根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年9月28日09时30分起停牌，挂牌藏品《江苏风光A》暂停交易，具体事项和复牌时间请关注交易所官网。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp;交易平台提醒投资者谨慎投资，注意风险。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp;特此公告！</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	二零一六年九月二十七日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61K920P-210P_lit.jpg{/dede:field}
