{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016F001号《唐伯虎》藏品复牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-08 11:54:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp;宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OXM1Y6120-21091.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 606px; height: 108px;" /><br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 复牌说明：停牌期间，藏品持有人与多方进行协商会谈，取得一定结果，同时也向交易所承诺履行护盘义务，特向交易所申请复牌，经审核挂牌藏品《唐伯虎》于2016年8月11日9时30分起复牌交易。<br style="padding: 0px; margin: 0px;" />
<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 特此公告<strong style="padding: 0px; margin: 0px;">！</strong></span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	&nbsp;{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM1Y6120-21091_lit.jpg{/dede:field}
