{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}藏品介绍——《牧牛图》{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="fgx" style="padding: 0px; margin: 0px; clear: both; height: 8px; font-size: 12px; line-height: 8px;">
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
