<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《北京民居》普23藏品托管入库公告",89,180);
$z[2][4]['name']="title";
$z[3]=Array("field","",182,221);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",223,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-05 17:53:00 &nbsp",275,340);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《1986丙寅年》普23邮票&ldquo;北京民居&rdquo;（以下简称&ldquo;北京民居&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<br style=\"padding: 0px; margin: 0px;\" />\r\n	<span style=\"padding: 0px; margin: 0px;\"><strong style=\"padding: 0px; margin: 0px;\">入库藏品清单</strong></span>",342,1170);
$z[6][4]['name']="body";
$z[7]=Array("field","",1172,1211);
$z[7][4]['name']="litpic";

?>