<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","重要通告",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",182,232);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-08-27 13:19:00 &nbsp",234,299);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">尊敬的广大交易商、各会员单位：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<div style=\"padding: 0px; margin: 0px; text-align: justify;\">\r\n		<span style=\"padding: 0px; margin: 0px;\">宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;）， 为规范业务行为，维护市场秩序，保障投资者的合法权益。经本中心核实，现通告：挂牌藏品002003《湖北风光A邮资明信片》发售商，在上市过程中对藏品存在违规宣传，严重损坏了广大交易商正常会员利益。本中心根据《宁夏西邮文化艺术品交易中心风险控制管理办法》的规定特此决定追加其锁仓期限6个月，共18个月，锁仓比例追加至40%，并限制其新建仓位卖出3个月。如后续发现其它违规行为，会采取更严厉的处罚，确保广大会员的利益。</span>",301,1500);
$z[6][4]['name']="body";
$z[7]=Array("field","",1502,1541);
$z[7][4]['name']="litpic";

?>