<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","猴年邮票纪念币在澳受当地人追捧 多数邮局数小",89,191);
$z[2][4]['name']="title";
$z[3]=Array("field","",193,232);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",234,284);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-25 01:22:00 &nbsp",286,351);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	人民网2月3日讯 据澳洲网消息，澳邮政局2月3日起正式发行内容为庆祝猴年新年的系列纪念邮票和生肖纪念币。</p>\r\n<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	报道称，当天11时，澳大部分邮局仅发售数小时就已将相关邮票和纪念币售罄。一些当地华人对火爆的行情始料未及，前来购买时方知已缺货。据悉，当地民众对猴年邮票和纪念币甚是追捧，有人甚至已经坚持每年收藏中国新年邮票超过12年。</p>\r\n<p style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;\">\r\n	设计猴年生肖邮票的是墨尔本华裔平面设计师潘德妮，她也是第二位负责为澳邮局设计农历新年邮票的华裔设计师。此次发行的邮票面值分别为1澳元（约合人民币4.6元）和3澳元（约合人民币13.9元），配首日封和纪念封套；生肖纪念币则推出金银两种材质和四种面值。</p>",353,1687);
$z[6][4]['name']="body";
$z[7]=Array("field","",1689,1728);
$z[7][4]['name']="litpic";

?>