{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}特种邮资明信片“唐伯虎”（002002）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><strong style="padding: 0px; margin: 0px;">特种邮资明信片&ldquo;唐伯虎&rdquo;(002002)</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：002002<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：35元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">&nbsp;&plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：39680枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">&nbsp;2枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：39680枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整本自提<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：唐伯虎系列字画选特种邮资明信片<br style="padding: 0px; margin: 0px;" />
															【邮票类型】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">特种邮资明信片<br style="padding: 0px; margin: 0px;" />
															【志 &nbsp; &nbsp; &nbsp;号】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">&nbsp;yz99<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">0.6元<br style="padding: 0px; margin: 0px;" />
															【发行日期】：1999年3月28日<br style="padding: 0px; margin: 0px;" />
															【发 行 &nbsp;量】：两万套<br style="padding: 0px; margin: 0px;" />
															【大全套数】</span><span style="padding: 0px; margin: 0px;">：</span><span style="padding: 0px; margin: 0px;">10枚/套&nbsp; （双连体）<br style="padding: 0px; margin: 0px;" />
															【藏品规格】：148&times;100毫米<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：2枚<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：胶版<br style="padding: 0px; margin: 0px;" />
															【发行机构】：国家邮政局<br style="padding: 0px; margin: 0px;" />
															【印 &nbsp;制 厂】：沈阳邮电印刷厂<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;唐寅（1470年3月6日-1524年1月7日）生于成化六年二月初四，卒于嘉靖二年十二月二日，字伯虎，后改字子畏，号六如居士、桃花庵主、鲁国唐生、逃禅仙吏等，明代画家、书法家、诗人。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;三十岁时进京会试，涉会试泄题案而被革黜，妻子改嫁，一生坎坷。后游历名山大川，以卖文鬻画闻名天下。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 早年随沈周、周臣学画，宗法李唐、刘松年，融会南北画派，笔墨细秀，布局疏朗，风格秀逸清俊。人物画师承唐代传统，色彩艳丽清雅，体态优美，造型准确；亦工写意人物，笔简意赅，饶有意趣。其花鸟画长于水墨写意，洒脱秀逸。书法奇峭俊秀，取法赵孟頫。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 为弘扬我国书法文化艺术的瑰宝，我局于1999年3月28日发行（江南四大才子名书选）系列之二。为一套十枚，首次采用国内60分牡丹图的邮资明信片，第一图为唐伯虎的（花卉图），第二图文徽明的（蘭竹卷），第三图为沈周的（京江送别图），第四.五图为仇英的（春泉小隐图卷）和（归汾图卷）。封套为仇英的（桃村草堂图轴）。发行量两万套，国家首日发行价每套25元。<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
