{dede:noteinfo notename="市场公告" channelid="1" macthtype="string"
    refurl="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/2016/1008/17.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/list_8_(*).html"
startid="1" endid="14" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="list">{/dede:areastart}
    {dede:areaend}</ul>{/dede:areaend}
{/dede:listrule}
