<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国邮政发行纪念邮票卡通“雁雁”形象将亮相",89,190);
$z[2][4]['name']="title";
$z[3]=Array("field","",192,231);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",233,283);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-23 00:03:00 &nbsp",285,350);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\">&nbsp; &nbsp;3月20日，中国邮政集团公司热闹非凡，中国邮政开办120周年一系列纪念活动在此举办&mdash;&mdash;《中国邮政开办一百二十周年》纪念邮票首发，中国邮政卡通形象&ldquo;雁雁&rdquo;亮相，中国邮政开办120周年纪念图片展启动。中国邮政集团公司副总经理李丕征和中国第一代女投递员、原邮电部副部长罗淑珍出席活动仪式。</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O95HJaV0-1B0O.jpg\" style=\"width: 500px; height: 373px;\" /></span>",352,1232);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95HJaV0-1B0O_lit.jpg",1234,1320);
$z[7][4]['name']="litpic";

?>