{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国邮政发行纪念邮票卡通“雁雁”形象将亮相{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-23 00:03:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp; &nbsp;3月20日，中国邮政集团公司热闹非凡，中国邮政开办120周年一系列纪念活动在此举办&mdash;&mdash;《中国邮政开办一百二十周年》纪念邮票首发，中国邮政卡通形象&ldquo;雁雁&rdquo;亮相，中国邮政开办120周年纪念图片展启动。中国邮政集团公司副总经理李丕征和中国第一代女投递员、原邮电部副部长罗淑珍出席活动仪式。</span>
<div style="text-align: center;">
	<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;"><img alt="" src="/uploads/allimg/c161124/14O95HJaV0-1B0O.jpg" style="width: 500px; height: 373px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HJaV0-1B0O_lit.jpg{/dede:field}
