{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}101006005号段开户送票啦{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-31 17:25:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<br />
										<span style="padding: 0px; margin: 0px;">各位代理商：<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 为答谢全国广大交易会员，为了更好的服务于各位投资者，现101006005号段经纪会员上海琴雁金融信息服务有限公司申请开展开户送原始票的活动。一波接一波，财富多多，具体活动详情请联系相关负责人。101006005号段经纪会员期待您<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;开户方式一：点此直接开户<a href="http://kh.81xiyou.com:6868/client/index.html?parentUsername=101006005" style="padding: 0px 2px; margin: 0px; color: rgb(50, 50, 50); text-decoration: none;">http://kh.81xiyou.com:6868/client/index.html?parentUsername=101006005</a><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;开户方式二：客服协助开户，请将开户所需资料（身份证正反面和银行卡照片+手机号），发送至开户负责人处。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;活动时间：2016年9月1日&mdash;2016年9月30日（名额有限， 送完即止）<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;注：开户之后需要联系客服进行登记上报 &nbsp;<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;联系方式：<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;1.&nbsp; QQ联系： 758103230（客服一）<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;490024850（客服二）<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp;2. 微 信 号： cc883868（客服微信）<br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 注：以上活动内容由101006005号段制定并负责落实<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 宁夏西邮文化艺术品交易中心不承担违约连带责任</span>
										<div style="padding: 0px; margin: 0px; text-align: right;">
											<span style="padding: 0px; margin: 0px;">2016年8月31日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
