{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}FP3邮资明信片“江苏风光A”（ 002004）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-05 18:36:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">FP3邮资明信片&ldquo;江苏风光A&rdquo;（ 002004）</strong></span></span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">交易参数：<br style="padding: 0px; margin: 0px;" />
【交易代码】：002004<br style="padding: 0px; margin: 0px;" />
【首日挂牌指导价】：25元/枚<br style="padding: 0px; margin: 0px;" />
【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
【单笔最大委托量】：37000枚<br style="padding: 0px; margin: 0px;" />
【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
【最小提货数量】: 1枚<br style="padding: 0px; margin: 0px;" />
【市场流通量】：37000枚<br style="padding: 0px; margin: 0px;" />
【备注】：&nbsp;以整本自提</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
【藏品名称】：江苏风光邮资片A组<br style="padding: 0px; margin: 0px;" />
【邮票类型】 : 邮资明信片<br style="padding: 0px; margin: 0px;" />
【面 &nbsp; &nbsp; &nbsp;值】 : 0.4元&times;10<br style="padding: 0px; margin: 0px;" />
【发行日期】：1997年5月8日<br style="padding: 0px; margin: 0px;" />
【大全套数】 : 10枚/套&nbsp;<br style="padding: 0px; margin: 0px;" />
【明信片规格】：148&times;100毫米<br style="padding: 0px; margin: 0px;" />
【邮资图规格】：35&times;28毫米<br style="padding: 0px; margin: 0px;" />
【整张枚数 】：1枚<br style="padding: 0px; margin: 0px;" />
【版 &nbsp; &nbsp; &nbsp; 别】：彩色胶版<br style="padding: 0px; margin: 0px;" />
【设 &nbsp;计 &nbsp;者】：一子<br style="padding: 0px; margin: 0px;" />
【摄 影 &nbsp; 者】：刘大健、张维君、陈许、茅永宽、桂宝林、纪因<br style="padding: 0px; margin: 0px;" />
【印 &nbsp;制 &nbsp;厂】：深圳当纳利旭日印刷有限公司</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;江苏省简称苏，位于中国东部沿海，面积10万多平方公里，人口7100多万。<br style="padding: 0px; margin: 0px;" />
江苏地跨华北平原和长江下游平原，万里长江横穿东西，千年古运河纵贯南北。江苏历史悠久，是吴文化发源地，也是中国历史上开化最早、经济最发达的地区之一。境内交通便捷，风光秀美，胜迹遍布，秀水青山凝水乡风韵，古城名园发思古幽情，是我国著名的旅游胜地。<br style="padding: 0px; margin: 0px;" />
<br style="padding: 0px; margin: 0px;" />
风险分析：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
特此提示</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />{/dede:field}
{dede:field name='litpic'}{/dede:field}
