<?php
$z[0]=Array("noteinfo","",0,226);
$z[0][4]['notename']="多栏目";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/2016/1008/17.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="1";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://www.81xiyou.com/a/xiyouzixun/zhongxindongtai/list_9_(*).html{/dede:addurls}\r\n    {dede:batchrule}[(#)=>http://www.81xiyou.com/a/xiyouzixun/huiyuanhuodong/list_10_(*).html; (*)=1-2; typeid=>19]\r\n[(#)=>http://www.81xiyou.com/a/xiyouzixun/tuoguangonggao/list_11_(*).html; (*)=1-5; typeid=>20]\r\n{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"list\">{/dede:areastart}\r\n    {dede:areaend}</ul>{/dede:areaend}\r\n",228,874);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="(#)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="14";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="1";

?>