{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D019号《宁夏民居》藏品的停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-28 15:41:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61LUX0-35252.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 595px; height: 108px;" /><br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;自2016年9月29日09时30分起，挂牌藏品《普26宁夏民居》暂停交易一天，于2016年9月30日09时30分起恢复交易。&nbsp;<br style="padding: 0px; margin: 0px;" />
&nbsp;<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;交易平台提醒投资者谨慎投资，注意风险。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;特此公告！</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	二零一六年九月二十八日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61LUX0-35252_lit.jpg{/dede:field}
