<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D029号《防止大气污染》藏品停牌的公告",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",232,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-21 15:58:36 &nbsp",284,349);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">&nbsp;宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:</span><br />\r\n<div>\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OX5b12HP-1GO.jpg\" style=\"width: 694px; height: 131px;\" /><br />\r\n	<span style=\"font-size:16px;\">&nbsp; &nbsp; &nbsp; 根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年10月22日09时30分起停牌，挂牌藏品《防止大气污染》暂停交易，于2016年10月24日9时30分起复牌交易。<br />\r\n	&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n	<br />\r\n	&nbsp; &nbsp; &nbsp; 特此公告！</span>",351,1088);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX5b12HP-1GO_lit.jpg",1090,1175);
$z[7][4]['name']="litpic";

?>