{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D029号《防止大气污染》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-21 15:58:36 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp;宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:</span><br />
<div>
	<img alt="" src="/uploads/allimg/c161123/14OX5b12HP-1GO.jpg" style="width: 694px; height: 131px;" /><br />
	<span style="font-size:16px;">&nbsp; &nbsp; &nbsp; 根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年10月22日09时30分起停牌，挂牌藏品《防止大气污染》暂停交易，于2016年10月24日9时30分起复牌交易。<br />
	&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />
	<br />
	&nbsp; &nbsp; &nbsp; 特此公告！</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX5b12HP-1GO_lit.jpg{/dede:field}
