{dede:noteinfo notename="多栏目" channelid="1" macthtype="string"
    refurl="http://www.81xiyou.com/a/xiyouzixun/shichanggonggao/2016/1008/17.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="1" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="(#)"
startid="1" endid="14" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="1"}
    {dede:addurls}http://www.81xiyou.com/a/xiyouzixun/zhongxindongtai/list_9_(*).html{/dede:addurls}
    {dede:batchrule}[(#)=>http://www.81xiyou.com/a/xiyouzixun/huiyuanhuodong/list_10_(*).html; (*)=1-2; typeid=>19]
[(#)=>http://www.81xiyou.com/a/xiyouzixun/tuoguangonggao/list_11_(*).html; (*)=1-5; typeid=>20]{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="list">{/dede:areastart}
    {dede:areaend}</ul>{/dede:areaend}
{/dede:listrule}
