{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《牧牛图》纪念张藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-08 11:14:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，1997年中国邮政贺年（有奖）明信片获奖纪念《牧牛图》（以下简称&ldquo;牧牛图&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">入库藏品清单</strong></span><br style="padding: 0px; margin: 0px;" />
	<img alt="" src="/uploads/allimg/c161124/14O9553SY250-34Y6.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 620px; height: 137px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O9553SY250-34Y6_lit.jpg{/dede:field}
