{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于中秋节放假安排通知{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-06 16:54:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的经纪、交易会员：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 根据《国务院办公厅关于2016年部分节假日安排的通知》，经本交易中心研究决定，现将2016年中秋休市安排公布如下：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 2016年9月15日（星期四）至2016年9月18日（星期天）休市四天。节前最后一个交易日为9月14日（星期三），节后首个交易日为9月19日（星期一）。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 休市期间，本中心暂停交易。网上开户可正常提交开户申请，本中心将于假期后交易日办理网上开户审核。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 请各经纪、交易会员据此安排好相关工作。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 特此公告！</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<br style="padding: 0px; margin: 0px;" />
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	&nbsp;&nbsp;&nbsp;&nbsp;二零一六年九月六日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
