{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}103000号段,卉雅坊开户送票公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-17 17:19:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">各位代理商：</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp; 西邮所<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">103000</span>号段（北京卉雅坊文化交流有限公司）开户可配售线上藏品。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 活动时间：即日起 配完为止<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 即日起，凡在103000（北京卉雅坊文化交流有限公司）号段及本号段下属经纪会员的号段下开户的会员，在活动期内成功签约并入金50元，可配售价值20元的原始票一枚，配售数量一<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">共30000枚</span>，配完为止。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp;&nbsp;</span><span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">欢迎您的加入！</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">注：以上活动内容由103000号段制定并负责落实</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
