{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国邮钞瑰宝 珍稀邮票展示{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-29 00:54:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	一．名称:&ldquo;大龙邮票&rdquo;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	大龙邮票是中国发行第一枚邮票，已有137年的历史，至今存世量不足千枚。全套版票被国家严密保护，价值数亿不止。清代&ldquo;海关大龙邮票&rdquo;通称&ldquo;大龙邮票&rdquo;，1878年7月－9月（光绪四年）清政府发行，选用&ldquo;江山云龙&rdquo;图案，雕刻铜板凸印。他标志着中国近代邮政史的开端，象征有着数千年邮驿通讯历史的中国，进入了现代通信新时期，在中国邮政史上占有举足轻重的地位，有&ldquo;中国第一邮&rdquo;之誉，被奉为稀世真品，&nbsp;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	二.名称:&ldquo;红印花加盖小字当壹圆&rdquo;邮票</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	简介：1896 年中国清朝政府海关印制的红色图案小票，用于加贴在进口税单上，但未投入使用。次年国家邮政成立，此票被加盖&ldquo;当壹圆&rdquo;字样暂作邮票使用，故称为&ldquo;红印花加盖小字当壹圆&rdquo;，存世极为稀少,全球仅有32枚。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	三．&ldquo;稿&rdquo;字邮票</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	简介：1943年淮南交通总站发行&ldquo;稿&rdquo;字邮票，专供给淮南区《新路东》报社记者、通讯员寄发稿件使用。图案是内有面值数字&ldquo;20&rdquo;（分）的五角星，四周有放射的光芒，红色。五角星的上面是拼音文字&ldquo;XUAINAN&rdquo;。五角星的中间加盖黑色二号宋体&ldquo;稿&rdquo;字。此票存世凤毛麟角，属&ldquo;区票&rdquo;中的罕品，现已列入世界珍邮之林。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;稿&rdquo;字邮票是抗日战争时期新四军开辟的淮南区交通总站发行的专用于寄递新闻与稿件的邮票，用量有限且其中大部分在战争中被毁，以前仅发现存世10枚，其中唯一的四方联邮票被国际集邮界誉为&ldquo;东方一宝&rdquo;，</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	四&nbsp;&ldquo;纪54世界学联&rdquo;邮票</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	简介：1958年9月1日，中国人民邮政为纪念国际学联第五届代表大会在北京举办，特发行纪念邮票一套，其中面值&ldquo;22分&rdquo;的邮票，误将&ldquo;国际学联&rdquo;错印为&ldquo;世界学生&rdquo;，故而停发。但由于少数单位已提前出售，致使少量错票流出。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
