{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}感恩十一月，103009009号段原始票大配送{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-18 16:40:52 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="font-size:16px;">各位交易会员：<br />
&nbsp; &nbsp; &nbsp; &nbsp;为感谢全国交易会员，为了更好的服务于各位投资者，现《湖北风光A》藏品战略投资人开展&ldquo;原始票&rdquo;大配送活动。<br />
<br />
<strong>一、活动时间</strong><br />
&nbsp; &nbsp; &nbsp; &nbsp;2016年信息11月19日&mdash;2016年11月21日<br />
<br />
<strong>二、活动内容</strong><br />
&nbsp; &nbsp; &nbsp; &nbsp;因《湖北风光A》藏品引进了新的战略投资人，由新战略投资人要求《湖北风光A》藏品锁仓三个月。<br />
&nbsp; &nbsp; &nbsp; &nbsp;为补偿同意锁仓持有《湖北风光A》会员的时间损失，新战略投资人承诺，按照目前此藏品者持有的数量，以1：1的比例免费配送，给同意锁仓的持有人12月份上市新藏品《马踏飞燕》，《马踏飞燕》上市挂牌价为5元/张。<br />
<br />
<strong>三、其它说明</strong><br />
&nbsp; &nbsp; &nbsp; &nbsp;1、请持有《湖北风光A》藏品的交易会员，于2016年11月19日&mdash;2016年11月21日内（共三天）联系活动方。<br />
&nbsp; &nbsp; &nbsp; &nbsp;2、过期未联系即视为放弃参与活动。<br />
&nbsp;<br />
&nbsp; &nbsp; &nbsp; &nbsp;详情咨询仝先生:<br />
&nbsp; &nbsp; &nbsp; &nbsp;1、QQ：3165978562<br />
&nbsp; &nbsp; &nbsp; &nbsp;2、联系人：13129948808<br />
<br />
&nbsp; &nbsp; &nbsp; 注：以上活动内容由103009009号段制定并负责落实<br />
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 宁夏西邮文化艺术品交易中心不承担违约连带责任</span><br />
<br />
<br />
<div style="text-align: right;">
	<span style="font-size:16px;">2016年11月18&nbsp;日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
