<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","- 交易品种  /  邮票介绍 -",89,160);
$z[2][4]['name']="title";
$z[3]=Array("field","",162,201);
$z[3][4]['name']="writer";
$z[4]=Array("field","",203,242);
$z[4][4]['name']="source";
$z[5]=Array("field","",244,284);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",286,323);
$z[6][4]['name']="body";
$z[7]=Array("field","",325,364);
$z[7][4]['name']="litpic";

?>