<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016S012《珍惜生命之水》藏品申购公告",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",226,276);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-28 14:38:13 &nbsp",278,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种普通邮票普30&ldquo;珍惜生命之水&rdquo;（以下简称&ldquo;珍惜生命之水&rdquo;）进行定价发行申购。<br />\r\n&nbsp; &nbsp; &nbsp; 本次申购比例为：市值申购占可申购总量的0%，资金申购占可申购总量的100%。持仓市值参考为申购日结算后的实际市值。<br />\r\n&nbsp; &nbsp; &nbsp; 具体事项公告如下：<br />\r\n一、申购藏品信息</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O95B40AF-33L5.jpg\" style=\"width: 685px; height: 176px;\" /></span>",345,1182);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95B40AF-33L5_lit.jpg",1184,1270);
$z[7][4]['name']="litpic";

?>