{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}大学生手绘高埗明信片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-29 00:55:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95I1295540-15226.jpg" style="width: 300px; height: 485px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&nbsp; &nbsp; &nbsp; &nbsp;很多明信片，都是一个地方的形象展示窗口，通过特色图片的展示，让人对一个地方留有印象。而通常见到的明信片，都以实物图片为主，但在高埗镇，由一位本地大学生莫梦娜创作的手绘高埗镇卡通明信片就打破了常规明信片模式。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	她通过卡通的画法，把高埗镇的特色都画到了明信片上，既可爱，也特别，让人一看对高埗印象深刻。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	记者了解到，这套明信片共分3张，一张以高埗镇地图为大背景，标注了18条村，基本每条村都标上了本村的特色产业和特色景点。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	而第二张明信片则以醒狮、学校的校车接送、英雄纪念碑祭祀、到广场游玩等在高埗频繁出现的生活场景构成，背景则有高埗大桥、电信大楼、悦南熊公祠等特色建筑。最后一张明信片有粤曲、冼沙鱼丸、保安围扣肉、冬团等特色文化和美食的卡通形象。<span style="text-indent: 2em;">很多明信片，都是一个地方的形象展示窗口，通过特色图片的展示，让人对一个地方留有印象。而通常见到的明信片，都以实物图片为主，但在高埗镇，由一位本地大学生莫梦娜创作的手绘高埗镇卡通明信片就打破了常规明信片模式。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	她通过卡通的画法，把高埗镇的特色都画到了明信片上，既可爱，也特别，让人一看对高埗印象深刻。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	记者了解到，这套明信片共分3张，一张以高埗镇地图为大背景，标注了18条村，基本每条村都标上了本村的特色产业和特色景点。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	而第二张明信片则以醒狮、学校的校车接送、英雄纪念碑祭祀、到广场游玩等在高埗频繁出现的生活场景构成，背景则有高埗大桥、电信大楼、悦南熊公祠等特色建筑。最后一张明信片有粤曲、冼沙鱼丸、保安围扣肉、冬团等特色文化和美食的卡通形象。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95I1295540-15226_lit.jpg{/dede:field}
