<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《木兰辞》小型张藏品托管入库公告",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",224,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-26 21:50:14 &nbsp",276,341);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2016丙申年</span><span style=\"font-size:16px;\">》 小型张澳门中国古典诗词&ldquo;木兰辞&rdquo;（以下简称&ldquo;木兰辞&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><strong>入库藏品清单<br />\r\n	<img alt=\"\" src=\"/uploads/allimg/c161124/14O955424T250-21329.png\" style=\"width: 576px; height: 147px;\" /></strong></span>",343,983);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O955424T250-21329_lit.png",985,1075);
$z[7][4]['name']="litpic";

?>