{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《木兰辞》小型张藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-26 21:50:14 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2016丙申年</span><span style="font-size:16px;">》 小型张澳门中国古典诗词&ldquo;木兰辞&rdquo;（以下简称&ldquo;木兰辞&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><strong>入库藏品清单<br />
	<img alt="" src="/uploads/allimg/c161124/14O955424T250-21329.png" style="width: 576px; height: 147px;" /></strong></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O955424T250-21329_lit.png{/dede:field}
