{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}换不到新钞了 1元纸币要“绝版”了?{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 00:45:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	3月14日，全国人大代表、央行副行长陈雨露透露，1元硬币化将逐步在各地推广。据介绍，1元硬币化工程已于今年1月份率先在山东进行试点。这条消息让很多人以为1元纸币要退出流通了，在钱币收藏市场也掀起了不小的波澜。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;没听说要退出流通，我们银行仍可以兑换1元纸币，只是新的不多而已。&rdquo;昨天，药行街一家银行的客户经理说，第四套人民币仍在流通，因此，第五套人民币的1元纸币更不可能很快退出市场，&ldquo;只是在试点的一些地方停发了而已。&rdquo;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	收藏市场已闻风而动</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	虽然1元纸币短期内不会退出流通，但在收藏市场上钱币收藏的话题却炙手可热。在中国集币在线等几家大型的钱币收藏网站上，有藏家已经开始加价收购第四套人民币，比如第四套人民币中的1元纸币，根据品相以及冠字号等不同，1996年版的1元纸币，一张的价格为5.5～6.5元；1990年版的1元纸币，收购价一张在6～7.5元；1980年版的1元纸币，一张为8～15元。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;大都在炒作，投资者最好不要跟风买，跟风买的后果，就是风停了，钱却被套了。&rdquo;宁波市银润钱币文化传播有限公司负责人王锡军表示，目前市场中流通的1元纸币有好几个版本，价格不一，而且由于第四套人民币仍在流通，所以买卖流通的人民币是违法的。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	王锡军介绍说，近年来，钱币收藏甚是火热，但物以稀为贵，钱币收藏对品相的要求很高，跟其他的收藏品一样，发行量也至关重要，只有存世量少的币种在退出流通后才具有投资价值，而目前正在流通的1元人民币属于第五套人民币，发行量巨大，除非年份非常久远很稀缺，&ldquo;否则可以说几乎不具有收藏价值&rdquo;。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	相对而言，目前已经退出流通的第一第二和第三套人民币更具有收藏属性。昨天，记者从范宅等收藏市场了解到，以1元纸币为例，目前第一套人民币中的1元纸币，根据品相和冠号等不同，一张的价格为1000～2000元；在第二套的1元纸币中，属&ldquo;红一元&rdquo;和&ldquo;黑一元&rdquo;最值钱，一张的价格为3500～4000元；在第四套人民币中，50元的全新纸币价格被炒得很高，一张的收购价格近1000元。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	新中国成立后，共发行了多少套人民币？</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HLG630-1M08.jpg" style="width: 304px; height: 173px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HLN260-25R6.jpg" style="width: 304px; height: 179px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	第一套人民币：1948年12月1日，中国人民银行发行第一套人民币，共12种面额62种版别，其中1元券2种、5元券4种、10元券4种、20元券7种、50元券7种、100元券10种、200元券5种、500元券6种、1000元券6种、5000元券5种、10000元券4种、50000元券2种。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HLQG0-31Q8.jpg" style="width: 312px; height: 166px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HM46430-42562.jpg" style="width: 302px; height: 163px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	第二套人民币：第二套人民币于1955年3月1日开始发行，同时收回第一套人民币。第二套人民币和第一套人民币折合比率为1：10000。第二套人民币共有1分、2分、5分、1角、2角、5角、1元、2元、3元、5元、10元等11种面额，其中1元券有2种，5元券有2种，1分、2分和5分券别有纸币、硬币2种。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	为便于流通，自1957年12月1日起发行1分、2分、5分三种硬币，与纸分币等值流通。1961年3月25日和1962年4月20日，分别发行了黑色1元券和棕色5元券，分别对票面图案、花纹进行了调整和更换。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HN14620-54509.jpg" style="width: 308px; height: 160px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	第三套人民币：第三套人民币于1962年4月20日发行，共有1角、2角、5角、1元、2元、5元、10元等7种面额、13种版别，其中1角券别有4种(包括1种硬币)，2角、5角、1元有纸币、硬币2种。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1966年和1967年，又先后两次对1角纸币进行改版，主要是增加满版水印，调整背面颜色。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HN39220-B241.jpg" style="width: 302px; height: 142px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="text-indent: 2em;">第四套人民币：为了适应经济发展的需要，进一步健全中国的货币制度，方便流通使用和交易核算，中国人民银行1987年4月27日，发行第四套人民币。共有1角、2角、5角、1元、2元、5元、10元、50元、100元等9种面额，其中1角、5角、1元有纸币、硬币2种。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95HN424F-I196.jpg" style="width: 303px; height: 172px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	第五套人民币：1999年10月1日，中国人民银行陆续发行第五套人民币，共有1角、5角、1元、5元、10元、20元、50元、100元等8种面额，其中1角、5角为硬币，1元有纸币、硬币2种。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<br />
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HLG630-1M08_lit.jpg{/dede:field}
