{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}103888001号段，武汉久佳文化开展开户有礼活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-20 16:14:00 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">各位代理商：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;为了回馈广大新老客户，现<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">武汉久佳文化发展有限公司</strong></span>诚招西邮所一级代理，二级代理，居间人，开户可享受原始票配售，西邮交易所<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">103888001</strong></span>号段开户可配售线上藏品，即日起，凡在<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">103888001</strong></span>号段及本号段下属经纪会员的号段下开户，在活动期内成功签约并入金<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">10元</strong></span>，可配原始票挂牌价<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">10元</strong></span>一枚，第一批配售数量一共<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">3000</strong></span>枚，配完为止感恩回馈活动，欢迎您的加入！<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;<br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">1. 活动时间：2016年6月15日起，配完为止</strong><br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">2.&nbsp;</strong><strong style="padding: 0px; margin: 0px;">开户银行：平安银行，平安易宝</strong><br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">开户链接：<a href="http://kh.81xiyou.com:6868/client/index.html?parentUsername=103888001" style="padding: 0px 2px; margin: 0px; color: rgb(50, 50, 50); text-decoration: none;"><span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">http://kh.81xiyou.com:6868/client/index.html?parentUsername=103888001</span></a><br style="padding: 0px; margin: 0px;" />
（武汉久佳文化发展有限公司）</strong><br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">3.&nbsp;</strong><strong style="padding: 0px; margin: 0px;">客户端下载：<a href="http://www.81xiyou.com/xiazaizhongxin/ruanjianxiazai/" style="padding: 0px 2px; margin: 0px; color: rgb(50, 50, 50); text-decoration: none;"><span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">http://www.81xiyou.com/xiazaizhongxin/ruanjianxiazai/</span></a></strong><br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">4.&nbsp;</strong><strong style="padding: 0px; margin: 0px;">绑定流程：<a href="http://www.81xiyou.com/jiaoyizhinan/yinxingbangding/" style="padding: 0px 2px; margin: 0px; color: rgb(50, 50, 50); text-decoration: none;"><span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">http://www.81xiyou.com/jiaoyizhinan/yinxingbangding/</span></a></strong><br style="padding: 0px; margin: 0px;" />
<strong style="padding: 0px; margin: 0px;">5.&nbsp;</strong><strong style="padding: 0px; margin: 0px;">久佳客户QQ群号：<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">20700256</span></strong>&nbsp;</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">注：以上活动内容由103888001号段制定并负责落实</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
