{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《桃花》特种邮票藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-24 17:23:25 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，2013-6特种邮票 &ldquo;桃花&rdquo;（以下简称&ldquo;桃花&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><strong>入库藏品清单<br />
	<img alt="" src="/uploads/allimg/c161124/14O95542391610-12122.jpg" style="width: 629px; height: 155px;" /></strong></span><br />
	&nbsp;{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95542391610-12122_lit.jpg{/dede:field}
