{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D044号《防止大气污染》藏品的停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-07 16:52:26 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size: 16px">&nbsp;宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品：<br />
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX6132000P-22T0.jpg" style="width: 589px; height: 102px;" /></span><br />
<span style="font-size:16px;">&nbsp; &nbsp; &nbsp; &nbsp; 根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br />
&nbsp; &nbsp; &nbsp; &nbsp; 自2016年11月8日09时30分起，挂牌藏品《防止大气污染》暂停交易一天，于2016年11月9日09时30分起恢复交易。&nbsp;<br />
&nbsp;<br />
&nbsp; &nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />
&nbsp; &nbsp; &nbsp; &nbsp; 特此公告！</span>
<div style="text-align: right;">
	<span style="font-size:16px;">宁夏西邮文化艺术品交易中心有限公司<br />
	二零一六年十一月七日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX6132000P-22T0_lit.jpg{/dede:field}
