<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D056号《湖北风光A》藏品停牌的公告",89,184);
$z[2][4]['name']="title";
$z[3]=Array("field","",186,225);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",227,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-22 16:06:59 &nbsp",279,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:<br />\r\n&nbsp; &nbsp; &nbsp;&nbsp;<img alt=\"\" src=\"/uploads/allimg/c161123/14OX614L33P-2J15.jpg\" style=\"width: 643px; height: 135px;\" /><br />\r\n&nbsp; &nbsp; &nbsp; 根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年11月23日09时30分起停牌，挂牌藏品《湖北风光A》暂停交易，具体事项和复牌时间请关注交易所官网。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;<br />\r\n&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n&nbsp; &nbsp; &nbsp; 特此公告！<br />\r\n&nbsp;</span>\r\n<div style=\"text-align: right;\">\r\n	<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心有限公司<br />\r\n	二零一六年十一月二十二日</span>",346,1266);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX614L33P-2J15_lit.jpg",1268,1355);
$z[7][4]['name']="litpic";

?>