<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","李可染的万山红遍1.84亿元易主",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",210,260);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-26 01:54:00 &nbsp",262,327);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\">&nbsp; &nbsp; &nbsp; &nbsp;11月15日晚，备受关注的嘉德秋拍&ldquo;大观&middot;中国书画珍品之夜&rdquo;举槌，88件拍品中，李可染创作的《万山红遍》以5800万元起拍，经多位买家数十轮的竞夺，最终以1.84亿元成交。</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\">&nbsp; &nbsp; &nbsp; &nbsp;<img alt=\"\" src=\"/uploads/allimg/c161124/14O95JEI220-1Q38.jpg\" /></span>",329,1036);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95JEI220-1Q38_lit.jpg",1038,1125);
$z[7][4]['name']="litpic";

?>