{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}李可染的万山红遍1.84亿元易主{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-26 01:54:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp; &nbsp; &nbsp; &nbsp;11月15日晚，备受关注的嘉德秋拍&ldquo;大观&middot;中国书画珍品之夜&rdquo;举槌，88件拍品中，李可染创作的《万山红遍》以5800万元起拍，经多位买家数十轮的竞夺，最终以1.84亿元成交。</span>
<div style="text-align: center;">
	<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp; &nbsp; &nbsp; &nbsp;<img alt="" src="/uploads/allimg/c161124/14O95JEI220-1Q38.jpg" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95JEI220-1Q38_lit.jpg{/dede:field}
