{dede:noteinfo notename="下载中心-相关下载" channelid="1" macthtype="string"
    refurl="http://www.81xiyou.com/a/xiazaizhongxin/xiangguanxiazai/" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.81xiyou.com/a/jiaoyipinzhong/youzifengpian/"
startid="1" endid="3" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<section class="newBox">{/dede:areastart}
    {dede:areaend}</section>{/dede:areaend}
{/dede:listrule}
