{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《十二届人大政协封》藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-14 13:57:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2013癸巳年》 &ldquo;十二届人大政协会议纪念封&rdquo;（以下简称&ldquo;十二届人大政协会议&rdquo;）藏品已完成托管入库流程，详情见下表：</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">入库藏品清单<br style="padding: 0px; margin: 0px;" />
	<img alt="" src="/uploads/allimg/c161124/14O955410C430-32930.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 628px; height: 155px;" /></strong></span><br style="padding: 0px; margin: 0px;" />
	&nbsp;{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O955410C430-32930_lit.jpg{/dede:field}
