<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",302,334);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",577,612);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n                <li><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"border borderL\"></div>\r\n                    <div class=\"border borderR\"></div>\r\n                </li>\r\n                ",876,1249);
$z[4][4]['row']="9";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("field","",1513,1532);
$z[5][4]['name']="title";
$z[6]=Array("field","",1732,1750);
$z[6][4]['name']="body";
$z[7]=Array("include","",1817,1854);
$z[7][4]['filename']="footer.htm";
$z[8]=Array("include","",1893,1933);
$z[8][4]['filename']="footer-js.htm";

?>