<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",302,334);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",577,612);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n                <li><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"border borderL\"></div>\r\n                    <div class=\"border borderR\"></div>\r\n                </li>\r\n                ",876,1249);
$z[4][4]['row']="9";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("global","",1418,1445);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("channel","<a href=\"[field:typelink/]\">[field:typename/]</a>",1475,1553);
$z[7]=Array("field","",1638,1657);
$z[7][4]['name']="title";
$z[8]=Array("field","",1723,1779);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[9]=Array("field","",1802,1822);
$z[9][4]['name']="source";
$z[10]=Array("field","",1870,1897);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",1921,1944);
$z[11][4]['name']="id";
$z[12]=Array("field","",1949,1973);
$z[12][4]['name']="mid";
$z[13]=Array("field","",2128,2146);
$z[13][4]['name']="body";
$z[14]=Array("include","",2211,2248);
$z[14][4]['filename']="footer.htm";
$z[15]=Array("include","",2287,2327);
$z[15][4]['filename']="footer-js.htm";

?>