{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}朝鲜发行两枚个别邮票 纪念首枚邮票问世70年{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-22 23:37:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GGD30-19B5.jpg" style="width: 448px; height: 307px;" /><br />
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		朝鲜邮政部门日前发行两枚个别邮票，纪念朝鲜第一枚邮票诞生70周年。图为其中一枚邮票。</p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		据朝媒12日报道，朝鲜邮政部门日前发行两枚个别邮票，纪念朝鲜第一枚邮票诞生70周年。</p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		据报道，这两枚新发行的邮票上方均写有&ldquo;朝鲜第一枚邮票发行70周年&rdquo;字样。</p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
		<img alt="" src="/uploads/allimg/c161124/14O95GGX130-26149.jpg" style="width: 449px; height: 306px;" /></p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		图为朝鲜此次发行的另一枚邮票。</p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		这两枚邮票中，一枚邮票的内容为朝鲜1946年3月12日发行的《三仙岩》等图案。另一枚邮票的图案为朝鲜国旗，以及朝鲜邮票展场和近期发行的邮票。</p>
	<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: left;">
		&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GGD30-19B5_lit.jpg{/dede:field}
