<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《珍惜生命之水》普通邮票藏品入库公告",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",230,280);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-27 13:53:12 &nbsp",282,347);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2002壬午年》普通邮票普30&ldquo;珍惜生命之水&rdquo;（以下简称&ldquo;珍惜生命之水&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"font-size:16px;\"><strong>入库藏品清单<br />\r\n	<img alt=\"\" src=\"/uploads/allimg/c161124/14O955425493F-31228.jpg\" style=\"width: 627px; height: 154px;\" /></strong></span>",349,953);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O955425493F-31228_lit.jpg",955,1045);
$z[7][4]['name']="litpic";

?>