{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普23 “江苏民居”（ 600009）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">普23 &ldquo;江苏民居&rdquo;(600009)</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：600009<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：8元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：120000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 60枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：120000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整版自提</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：普23江苏民居<br style="padding: 0px; margin: 0px;" />
															【藏品分类】：版票<br style="padding: 0px; margin: 0px;" />
															【藏品志号】：普23<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】 : 4分<br style="padding: 0px; margin: 0px;" />
															【材 &nbsp; &nbsp; &nbsp;质】 : 纸质<br style="padding: 0px; margin: 0px;" />
															【邮票规格】：25&times;30mm<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：60枚<br style="padding: 0px; margin: 0px;" />
															【发行日期】：1986年4月1日<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：影写版<br style="padding: 0px; margin: 0px;" />
															【设 计 &nbsp;者】：陈汉民 励忠发、华建心<br style="padding: 0px; margin: 0px;" />
															【发行机构】：中国邮政<br style="padding: 0px; margin: 0px;" />
															【印刷单位】：北京邮票厂</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 在中国建筑历史上，对民间居住建筑习惯称为&ldquo;民居&rdquo;。民居在人们的日常生活中占有极为重要的位置。中国的民居建筑，是千百年来劳动人民用自己的勤劳与智慧，在与大自然的搏斗中创造出来的。中国幅员辽阔，民族众多，由于各地区的自然地理条件不同、民族风格和传统各异、生产和生活方式各具特点、建筑材料千差万别。使中国的民居建筑多姿多彩，富有创造性。民居建筑不仅记载着人世间的沧桑，每一块砖、每一片瓦也都烙下了劳动者的印迹，都有一段可歌可泣的动人故事。这套邮票的14种图案，都采用较小票幅，白色底衬，铭记和面值文字统一设计在底部，朴素大方，醒目突出，符合普通邮票的特征。<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
