<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《建党九十周年》纪念邮票托管入库公告",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",230,280);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-23 15:06:00 &nbsp",282,347);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2011辛卯年》纪念邮票 &ldquo;建党九十周年&rdquo;（以下简称&ldquo;建党九十周年&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<span style=\"padding: 0px; margin: 0px;\"><strong style=\"padding: 0px; margin: 0px;\">入库藏品清单<br style=\"padding: 0px; margin: 0px;\" />\r\n	<img alt=\"\" src=\"/uploads/allimg/c161124/14O95541K0N0-1D30.jpg\" style=\"width: 628px; height: 153px;\" /></strong></span>",349,1294);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95541K0N0-1D30_lit.jpg",1296,1384);
$z[7][4]['name']="litpic";

?>