{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}103000号段,卉雅坊上市辅导活动公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-27 17:15:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">北京卉雅坊文化交流有限公司对旗下会员展开上市辅导活动，为期一年。<br style="padding: 0px; margin: 0px;" />
所有卉雅坊旗下开户会员，即日起公司隆重推出持仓配票，锁仓送票活动。活动期为一年。详见以下：</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: justify;">
	<span style="padding: 0px; margin: 0px;">&nbsp; 一、&nbsp;凡申报参加活动并自愿持仓牧牛图50枚，每次公司发行新票可按申购价配售2枚原始票，自愿持仓100枚，可按申购价配售4枚原始票，自愿持仓500枚，可按申购价配售200枚原始票，自愿持仓1000枚，可按申购价配售400枚原始票。活动时间为一年，活动期间须持有不卖出牧牛图，每次申购前须审核通过，中间卖出视为退出活动，后续不再配票，且不得再次申请参加活动。<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp;二、&nbsp;凡申报参加并自愿锁仓牧牛图500枚者，每次公司发行新票可免费获赠200枚，自愿锁仓1000枚，可每次免费获赠400枚。活动时间为一年，活动期间持仓的牧牛图为锁定状态，不得卖出。同时，为充分保障参加锁仓活动的普通投资者之利益，公司承诺以下：<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; （1）上市发起人在未来五个交易日内通过回购等手段，向西邮所提出自愿锁仓牧牛图60000&plusmn;1000枚一年，与普通投资者同日锁仓，并不得提前申请解锁。<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; （2）如解锁日前一天牧牛图收盘价低于活动基准价81.63元，上市发起人履行此义务，既（上市发起人将持有的牧牛图锁仓筹码按比例全部赠与参加锁仓活动的会员）<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; （3）如解锁日前一天牧牛图收盘价高于活动前基准价但不足活动前基准价的2倍，即163.26元，上市发起人履行此义务，既（上市发起人将牧牛图锁仓筹码，按实际差额赠与参加锁仓活动的会员，或补偿相应现金）&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; （4）持仓有配票，锁仓享分红，利益有保障，此活动名额有限，全体会员的累积最大参与量不超过30000枚。如第二年到期后继续开展此活动，则仅向首批参与的有效会员开放。<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; （5）持仓配票与锁仓送票活动只面向卉雅坊旗下会员开放。为使广大投资者充分了解到上述信息，特向西邮所申请牧牛图停牌三个交易日。参加活动报名截止期限为2016年8月8日。本次活动起始日期为2016年8月9日，结束日期为2017年8月8日。以上解释权为卉雅坊文化交流有限公司所有。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
