{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《中国梦—人民幸福》特种邮票托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-23 16:58:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2015乙未年》特种邮票（小全张）&ldquo;中国梦-人民幸福&rdquo;（以下简称&ldquo;中国梦-人民幸福&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">入库藏品清单<br style="padding: 0px; margin: 0px;" />
	<img alt="" src="/uploads/allimg/c161124/14O9554192U10-23Z3.jpg" style="width: 630px; height: 160px;" /></strong></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O9554192U10-23Z3_lit.jpg{/dede:field}
