{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于苹果手机使用交易软件恢复正常的通知{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-12 11:20:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的经纪、交易会员：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），苹果官方审核已通过，目前苹果手机使用交易软件已经恢复正常。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp;&nbsp; 感谢您对交易中心的支持！<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;请各位客户知晓，由此给您带来的不便敬请谅解！<br style="padding: 0px; margin: 0px;" />
<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;特此通知</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	&nbsp;&nbsp;&nbsp;2016年9月12日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
