<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于苹果手机使用交易软件恢复正常的通知",89,184);
$z[2][4]['name']="title";
$z[3]=Array("field","",186,225);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",227,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-12 11:20:00 &nbsp",279,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">尊敬的经纪、交易会员：<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），苹果官方审核已通过，目前苹果手机使用交易软件已经恢复正常。<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp;&nbsp; 感谢您对交易中心的支持！<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; &nbsp;请各位客户知晓，由此给您带来的不便敬请谅解！<br style=\"padding: 0px; margin: 0px;\" />\r\n<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; &nbsp;特此通知</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">宁夏西邮文化艺术品交易中心有限公司<br style=\"padding: 0px; margin: 0px;\" />\r\n	&nbsp;&nbsp;&nbsp;2016年9月12日</span>",346,1552);
$z[6][4]['name']="body";
$z[7]=Array("field","",1554,1593);
$z[7][4]['name']="litpic";

?>