{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016年邮票发行计划早知道{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 17:58:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 21px 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; text-align: justify; line-height: 24px; text-indent: 32px;">
	<span style="padding: 0px; margin: 0px; font-family: 宋体;">近日，记者获悉，2016年将发行第四轮首枚《丙申年》猴邮票，36年后，92岁高龄的黄永玉再次执笔，为即将到来的丙申猴年设计一套猴票，再次演绎&ldquo;大圣归来&rdquo;，震撼开启生肖邮票的第四个崭新的轮回。</span></p>
<p style="padding: 0px; margin: 21px 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; text-align: justify; line-height: 24px; text-indent: 32px;">
	<span style="padding: 0px; margin: 0px; font-family: 宋体;">此外，中国邮政还将延续往年发行过的一些题材邮票，继续发行《拜年》、《中国古典文学名著&mdash;&mdash;红楼梦》、《水果》、《中华孝道》、《抗震救灾》、《中国共产党早期领导人(四)》，这些同类题材的邮票深受各界追捧。</span></p>
<p style="padding: 0px; margin: 21px 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; text-align: justify; line-height: 24px; text-indent: 32px;">
	<span style="padding: 0px; margin: 0px; font-family: 宋体;">同时，为配合习近平主席提出的&ldquo;一带一路&rdquo;战略构想，中国邮政2016年将发行《21世纪海上丝绸之路》邮票，该套邮票与之前发行的丝绸之路邮票遥相呼应。</span></p>
<p style="padding: 0px; margin: 21px 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; text-align: justify; line-height: 24px; text-indent: 32px;">
	<span style="padding: 0px; margin: 0px; font-family: 宋体;">在发行了长江邮票、黄河邮票之后，2016年中国邮政将发行《万里长城》邮票;绘画系列题材邮票，2016年将发行《刘海粟作品选》邮票。古画邮票将发行《高逸图》古画邮票，高逸图为唐代孙位的作品，现藏上海博物馆;大学系列题材的邮票，2016年正值四川大学建校120周年，中国邮政将发行《四川大学建校120周年》邮票加以纪念;人物系列邮票，继孔子、关公、诸葛亮、包公后，2016年将发行《玄奘》邮票，还有《孙中山诞生150周年》的邮票;盛会系列邮票，2016年还将发行《唐山世界园博会》、《第31届奥运会》、《第39届国际标准化组织大会》等邮票;文化遗产、文物古迹方面，2016年将发行《文化遗产日》、《正定隆兴寺》及《殷墟》等邮票;其他题材，2016年将发行《足球运动》、《全民阅读》、《相思鸟》、《月圆中秋》等邮票。</span></p>
<div>
	&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
