<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","西邮所:依法合规经营 严禁不当行为管控各项风险",89,192);
$z[2][4]['name']="title";
$z[3]=Array("field","",194,233);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",235,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-08-23 18:01:13 &nbsp",287,352);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n					<tbody>\r\n						<tr>\r\n							<td>\r\n								<div>\r\n									<div>\r\n										<div>\r\n											<br />\r\n											<span style=\"font-size: 18px\">尊敬的广大交易商、各会员单位：</span><br />\r\n											&nbsp;",354,750);
$z[6][4]['name']="body";
$z[7]=Array("field","",752,791);
$z[7][4]['name']="litpic";

?>