{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西邮所:依法合规经营 严禁不当行为管控各项风险{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-23 18:01:13 &nbsp{/dede:field}
{dede:field name='body'}<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
				<table border="0" cellpadding="0" cellspacing="0">
					<tbody>
						<tr>
							<td>
								<div>
									<div>
										<div>
											<br />
											<span style="font-size: 18px">尊敬的广大交易商、各会员单位：</span><br />
											&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
