{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《珍惜矿产资源》普30藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-03 16:02:13 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2002壬午年》普30邮票&ldquo;珍惜矿产资源&rdquo;（以下简称&ldquo;珍惜矿产资源&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><strong>入库藏品清单<br />
	<img alt="" src="/uploads/allimg/c161124/14O955425V430-49352.jpg" style="width: 628px; height: 152px;" /></strong></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O955425V430-49352_lit.jpg{/dede:field}
