{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z004《唐伯虎》藏品申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-18 09:38:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年7月15日对挂牌藏品《唐伯虎》系列字画选特种邮资明信片面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>
										<div style="padding: 0px; margin: 0px;">
											<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OXM12G920-2cY.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 673px; height: 249px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM12G920-2cY_lit.jpg{/dede:field}
