{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D048号《保护森林》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-12 14:57:55 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size: 16px">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品:<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX613M11P-15J6.jpg" style="width: 650px; height: 127px" /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年11月14日09时30分起停牌，挂牌藏品《普30 保护森林》暂停交易一周，于2016年11月21日09时30分起复牌交易。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交易平台提醒投资者谨慎投资，注意风险。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 特此公告！</span>
<div style="text-align: right">
	<span style="font-size: 16px">宁夏西邮文化艺术品交易中心有限公司<br />
	二零一六年十一月十二日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX613M11P-15J6_lit.jpg{/dede:field}
