{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《普23江苏民居》等藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-07 15:18:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将《普23江苏民居》、《普22黄果树瀑布》藏品在本中心正式发行和上市交易，具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
										<strong style="padding: 0px; margin: 0px;">一、&nbsp;上市商品信息</strong></span>
										<div style="padding: 0px; margin: 0px; text-align: center;">
											<span style="padding: 0px; margin: 0px;"><img alt="" src="/uploads/allimg/c161123/14OX61591SP-21B1.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 615px; height: 553px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61591SP-21B1_lit.jpg{/dede:field}
