{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财富就在你手中{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-05 09:33:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">
	<span style="padding: 0px; margin: 0px;">有一个一无所长的年轻人,感到自己生活得非常无聊。于是，他就去拜访一位哲人，希望哲人能够给他的未来指一条道路。</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
