<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","财富就在你手中",89,148);
$z[2][4]['name']="title";
$z[3]=Array("field","",150,189);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",191,241);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-07-05 09:33:00 &nbsp",243,308);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">\r\n	<span style=\"padding: 0px; margin: 0px;\">有一个一无所长的年轻人,感到自己生活得非常无聊。于是，他就去拜访一位哲人，希望哲人能够给他的未来指一条道路。</span>",310,712);
$z[6][4]['name']="body";
$z[7]=Array("field","",714,753);
$z[7][4]['name']="litpic";

?>