{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}航天币钞即将发行：广州预约火爆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 17:37:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="text-align: center;">
	&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
