<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","航天币钞即将发行：广州预约火爆",89,172);
$z[2][4]['name']="title";
$z[3]=Array("field","",174,213);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",215,265);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-25 17:37:00 &nbsp",267,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"text-align: center;\">\r\n	&nbsp;",334,413);
$z[6][4]['name']="body";
$z[7]=Array("field","",415,454);
$z[7][4]['name']="litpic";

?>