{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}名家珍藏邮票获藏家热烈竞投{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-31 23:08:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GPBS0-15038.jpg" style="width: 500px; height: 410px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1897年慈禧寿辰大字改值10分于12分橙棕色&ldquo;黄金龙&rdquo;票，估价为50万至60万港元。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	苏黎世亚洲拍卖行将于2月27日至28日在香港北角海逸酒店举行拍卖会，呈献逾3200件珍贵邮票、纸币与钱币。此次拍卖会还将特别推出香港著名的集邮家&mdash;&mdash;裘集成医生的珍藏，并首次推出纸币与钱币拍卖专场。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	此次拍卖的焦点拍品为一枚非常罕有的1873年上海书信馆壹分银于银八分红色改值灰蓝色小龙新票，估价为70万至80万港元。这枚邮票曾为著名藏家贝克曼伉俪所珍藏，是已知现存世仅4枚同类票之一，弥足珍贵。该票背贴原胶，背部更附紫色鉴证印，预计将引起藏家们的热烈竞投。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	另一枚广受关注的邮票为1897年慈禧寿辰大字改值10分于12分橙棕色&ldquo;黄金龙&rdquo;票，估价为50万至60万港元。据了解，现存世的&ldquo;黄金龙&rdquo;新票仅有13枚，本次推出的原胶新票属其中的极品，并附2012年鉴真证书。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1949年11月23日由安康寄兰州的实寄封估价为40万至45万港元。该实寄封背贴陕南毛主席像点线齿票，包括10美分绿蓝色十五方连及50美分橙色三直连，销腰截形&ldquo;山西/安康&rdquo;戳，以及中英文&ldquo;兰州&rdquo;到达戳，封面则有同款&ldquo;山西/安康&rdquo;戳，是市场上少见的贴刷方连实寄封。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	本次拍卖会上也将呈现一系列深受藏家青睐的珍稀清朝红印花改值票，包括一枚1897年红印花大字加盖当伍圆于3分新票，票背附有签名，估价为30万至40万港元。1897年慈禧寿辰小字改值10分于6分棕色四方连原胶新票，属横中缝漏齿，估价为28万至32万港元。现存世仅有两件同类四方连，在市场上难得一见，本场呈献的是其中的优秀范例，背胶更附有集邮名家钟笑炉的鉴真蓝印，极具收藏价值。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	此外，首次推出的纸币与片比拍卖专场涵盖了多件精品。其中，民国1931年版中国垦业银行壹圆纸币票面印有山径、佛塔及大宅图样，保存完好，品相完美，实属难得，估价为6万至8万港元。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GPBS0-15038_lit.jpg{/dede:field}
