{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}普23 “北京民居”（ 600008）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">普23 &ldquo;北京民居&rdquo;(600008)</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：600008<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：8元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：120000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 60枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：120000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整版自提</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：普23北京民居<br style="padding: 0px; margin: 0px;" />
															【藏品分类】：版票<br style="padding: 0px; margin: 0px;" />
															【藏品志号】：普23<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】 : 8分<br style="padding: 0px; margin: 0px;" />
															【材 &nbsp; &nbsp; &nbsp;质】 : 纸质<br style="padding: 0px; margin: 0px;" />
															【邮票规格】：25&times;20mm<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：60枚<br style="padding: 0px; margin: 0px;" />
															【发行日期】：1986年6月15日<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：影写版<br style="padding: 0px; margin: 0px;" />
															【设 计 &nbsp;者】：陈汉民 励忠发、华建心<br style="padding: 0px; margin: 0px;" />
															【发行机构】：中国邮政<br style="padding: 0px; margin: 0px;" />
															【印刷单位】：北京邮票厂</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 民居是建筑中最早出现的类型，是中国建筑史上对民间居住建筑物的习惯称呼，作为住房的民居在人们的日常生活建筑中占有极为重要的位置。中国的民居建筑是千百年来劳动人民用自己勤劳智慧的双手，在适应与改造大自然的漫长岁月中创造出来的。由于中国幅员广阔，各地区的自然地理条件不同，56个民族风格与传统各异，生产和生活各具特色，建筑材料千差万别，使中国的民居建筑多姿多彩，富有创造性。从2002年开始，国家邮政局停止发行《民居》系列普票，使得普通邮票进入收藏领域，因消耗大、留存少等原因，为邮迷一致看好。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp;北京民居（1986.6.15）&mdash;&mdash;四合院　四合院式的住房是我国最为普遍、历史最为久远的住宅形式。其布局常为&ldquo;一正两厢&rdquo;，正房(上房)位置在全宅的中轴线上，坐北朝南，开间、进深、高度和装饰等都央全宅之首。院子两侧的厢房、陪衬着正房。院子是交通、采光、通风的枢纽，并配以绿化，成为休息与家庭活动的中心。住宅大门多设在东南角上，象征风水八卦上的&ldquo;巽门&rdquo;方位，附会&ldquo;紫气东来&rdquo;的吉祥，以北京的四合院最具有代表性。<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; 各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
