{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《一轮生肖虎大版票》延期挂牌交易的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-17 09:10:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的经纪会员、交易会员：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 为配合营销配售活动，经决定《一轮生肖虎大版票》延期挂牌交易&nbsp;，具体挂牌交易时间尽请关注官网通知。<br style="padding: 0px; margin: 0px;" />
具体如下：&nbsp;<br style="padding: 0px; margin: 0px;" />
<img alt="" src="/uploads/allimg/c161123/14OXM22G520-22223.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 714px; height: 135px;" /></span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">特此公告！</span>
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	二零一六年八月十七日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OXM22G520-22223_lit.jpg{/dede:field}
