{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}猴年你家要是有这个邮票，可就值钱了{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-27 01:15:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;">&nbsp; &nbsp; &nbsp; &nbsp;年年底，北京有个邮局在开门营业前，门口就排起了长队，从石猴街的西墙一直排到了500多米外的全聚德烤鸭店东墙外！</span>
<div style="text-align: center;">
	<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;"><img alt="" src="/uploads/allimg/c161124/14O95HT43P-15232.png" style="width: 490px; height: 337px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95HT43P-15232_lit.png{/dede:field}
