<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","猴年你家要是有这个邮票，可就值钱了",89,178);
$z[2][4]['name']="title";
$z[3]=Array("field","",180,219);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",221,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-03-27 01:15:00 &nbsp",273,338);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\">&nbsp; &nbsp; &nbsp; &nbsp;年年底，北京有个邮局在开门营业前，门口就排起了长队，从石猴街的西墙一直排到了500多米外的全聚德烤鸭店东墙外！</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 32px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O95HT43P-15232.png\" style=\"width: 490px; height: 337px;\" /></span>",340,973);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95HT43P-15232_lit.png",975,1062);
$z[7][4]['name']="litpic";

?>