{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮资明信片“映日荷花”（ 002006）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);">邮资明信片&ldquo;映日荷花&rdquo;(002006)</span></strong><br style="padding: 0px; margin: 0px;" />
															交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：002006<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：6元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：300000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 100枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：300000枚<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															&nbsp;藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：映日荷花<br style="padding: 0px; margin: 0px;" />
															【邮票类型】 : 普通邮资明信片<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp; 值】：0.80元<br style="padding: 0px; margin: 0px;" />
															【发行日期】：2005年9月20日<br style="padding: 0px; margin: 0px;" />
															【正面图案】：右荷花<br style="padding: 0px; margin: 0px;" />
															【明信片规格】：148mm&times;100mm<br style="padding: 0px; margin: 0px;" />
															【邮票规格】：30mm&times;24mm<br style="padding: 0px; margin: 0px;" />
															【整套枚数】：1枚<br style="padding: 0px; margin: 0px;" />
															【设 &nbsp; &nbsp; &nbsp; 计】：张桂徵<br style="padding: 0px; margin: 0px;" />
															【发行机构】：国家邮政局<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp; 别】：胶版<br style="padding: 0px; margin: 0px;" />
															【责任编辑】：虞平<br style="padding: 0px; margin: 0px;" />
															【防伪方式】：缩微文字<br style="padding: 0px; margin: 0px;" />
															【印&nbsp; 制 厂】：河南省邮电印刷厂<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp; 因荷花的出尘脱新的品质，荷花也有清白、高尚之意，由于&ldquo;荷&rdquo;与&ldquo;和&rdquo;、&ldquo;合&rdquo;谐音，&ldquo;莲&rdquo;与&ldquo;联&rdquo;、&ldquo;连&rdquo;谐音，中华传统文化中，经常以荷花即莲花作为和平、和谐、合作、合力、团结、联合等象征；以荷花的高洁象征和平事业、和谐世界的高洁。因此，某种意义上说，赏荷也是对中华&ldquo;和&rdquo;文化的一种弘扬。荷花品种丰富多彩，是&ldquo;荷（和）而不同&rdquo;，但又共同组成了高洁的荷花世界，是&ldquo;荷（和）为贵&rdquo;。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp; 国家邮政局在1999年发行了《荷花》普通邮资明信片之后，2005年又以荷花为题材，再次发行了《映日荷花》普通邮资明信片，既体现了映日荷花是荷花中的佼佼者，又表达出了国家构建和谐社会，倡导和平发展之意。<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;《映日荷花》普通邮资明信片图案设计美观、高雅、大气，主图居中一朵荷花映日绽放，左上两朵荷花含苞待放，整体构图饱满有序，色调温润，浑然天成，高低错落，极富艺术感染力。<br style="padding: 0px; margin: 0px;" />
															&nbsp;<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
