{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于平安银行平安易宝提前签退的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-14 09:51:00 &nbsp{/dede:field}
{dede:field name='body'}<br />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">尊敬的广大交易商、各会员单位：<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 接平安银行的通知，受平安银行平安易宝系统升级的影响，2016年10月14日（星期五）签退时间由原来的16:00提前至14:00，签退后将无法进行出入金、签解约操作。本中心10月14日收盘时间由原来的15点提前至14点，望各位会员单位知悉并做好交易客户的解释工作。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; 由此给您带来的不便，我们深表歉意！感谢您对本中心的理解和支持。</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp; &nbsp; &nbsp; 特此公告。</span>
<div style="text-align: right;">
	<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;二零一六年十月十四日</span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
