{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“西邮所”送好礼，原始票大配送{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-08-15 17:11:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">各位交易会员：<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 为答谢全国广大交易会员，为了更好的服务于各位投资者，现宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）面向各位亲爱的会员，不分号段，关注&ldquo;宁夏西邮所&rdquo;微信公众号，并转发其中任意一篇文章至朋友圈，可按挂牌价配售20元以上的原始票一枚。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">&nbsp; 具体活动详情如下:</strong><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; ①.&nbsp;转发其中任意一篇文章至朋友圈并截图，发送至975239639@qq.com邮箱。邮件统一格式为：姓名+交易账号+手机号码+微信或QQ号及朋友圈转发截图，以便统计，名额有限，先到先得，配完为止。<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; ②.新老&ldquo;西邮所&rdquo;会员，在活动期间，完成任意藏品买入交易一笔（无论是否卖出），可按挂牌价配售20元以上的原始票一枚。发送邮件，姓名+交易账号+手机号码+微信或QQ号至975239639@qq.com邮箱登记领取，名额有限，先到先得，配完为止。</span><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp;<span style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);">&nbsp;&nbsp;<strong style="padding: 0px; margin: 0px;">&nbsp;活动日期：</strong></span><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 2016年8月16日起至2016年8月31日<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; &nbsp; 活动①②可以同时参加，单个账户最大配售量为2枚，活动①配售500枚原始票，活动②配售1500枚原始票，活动总数量为2000枚，先到先得，配完为止。最终配售到账时间和最终配售名单将在9月30日前公布，参加活动的用户，账户内须入金100元，在公布名单后方可出金。</span><br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										<span style="padding: 0px; margin: 0px;">&nbsp; &nbsp; &nbsp;<strong style="padding: 0px; margin: 0px;">&nbsp;活动须知：</strong><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; 1.&nbsp;微信公众号：宁夏西邮所&nbsp;+<img src="/uploads/allimg/c161123/14OY2a4L120-12639.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 87px; height: 85px;" /><br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; 2.&nbsp;官网网址:&nbsp;http://81xiyou.com/index.html<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; 3.&nbsp;客服电话：4000-738-817<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp; QQ:&nbsp;2862629582，2657814015<br style="padding: 0px; margin: 0px;" />
										&nbsp;<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp;宁夏西邮文化艺术品交易中心期待您<br style="padding: 0px; margin: 0px;" />
										&nbsp; &nbsp;注：本活动最终解释权归本中心所有。</span>
										<div style="padding: 0px; margin: 0px; text-align: right;">
											<span style="padding: 0px; margin: 0px;">2016年8月15日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OY2a4L120-12639_lit.jpg{/dede:field}
