{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016D016号《防止大气污染》停牌公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-26 18:30:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">&nbsp;宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品：<br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61E130P-350O.jpg" style="padding: 0px; margin: 10px; border: none; max-width: 700px; width: 612px; height: 115px;" /><br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：&nbsp;&nbsp;<br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;自2016年9月27日09时30分起，挂牌藏品《防止大气污染》暂停交易一天，于2016年9月28日09时30分起恢复交易。<br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br style="padding: 0px; margin: 0px;" />
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 特此公告！</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: right;">
	<span style="padding: 0px; margin: 0px;">宁夏西邮文化艺术品交易中心有限公司<br style="padding: 0px; margin: 0px;" />
	二零一六年九月二十六日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61E130P-350O_lit.jpg{/dede:field}
