{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于“宁夏民居”普通邮票藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-10 10:30:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《1990庚午年》普通邮票普26&ldquo;宁夏民居&rdquo;（以下简称&ldquo;宁夏民居&rdquo;）藏品已完成托管入库流程，详情见下表：</span><br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<br style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;" />
<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;">
	<div style="padding: 0px; margin: 0px;">
		<span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;"><span style="padding: 0px; margin: 0px; font-family: arial, helvetica, sans-serif;">入库藏品清单</span></strong></span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
