{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国立故宫博物院南院落成开馆邮票12月10日台湾发{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-24 17:26:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	国立故宫博物院南部院区落成开馆，为宣传该院典藏之亚洲艺文珍品，本公司特选取4件该院首展展品为题材，设计邮票1组3枚及小全张1张，预定于2015年发行。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	一、邮票图桉: 首次以邮票票铭区隔上、下2款图桉，展现各文物重点特色。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	1.清乾隆 右旋白螺 &lt;面值5元&gt;: 俗称定风珠。清乾隆林爽文事件及嘉庆蔡牵事件时，曾随清兵渡海至台湾，具有护佑航海作用。白螺为藏传法器，属印度圣贝。螺上端吹口饰敲花莲瓣及卷草纹。护板钉接于螺口与底端，银质内板刻藏文右旋螺赞词及汉、满、蒙、藏四体文款：「大清乾隆年製」；外板镀金，并饰藏文赞词; 底端刻「乾隆年製」四楷字。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	2.印度 平口双柄盖碗 &lt;面值10元&gt;: 豆绿色玉琢成深腹盖碗。盖面与腹壁上用白玉、碧玉、红色镶嵌物与金属丝组成缤纷璀璨的花叶纹，盖钮琢成花蕾形。 双柄在腹壁中段立凋斜上捲叶，叶内绽放盛开的白色花朵。此碗贡入清廷后，很受乾隆皇帝的珍爱，命玉工在碗心及盖内分别刻上「乾隆御用」及「子孙永宝」。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	3.清御製三星图颂并恭绘图 轴 &lt;面值12元&gt;: ：全幅以缂丝织成，部分细部以画笔润饰，挂轴上方以黑丝线织出清高宗御製「三星图颂」，画心主题为手抱仙童或手持如意、灵芝与仙桃的福、禄、寿三星， 围绕着手拿牡丹花瓶、如意、兵器等吉祥物的仙童，周围饰以树木、花草与奇石。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	二、小全张图桉：内含面值25元邮票2枚。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	邮票图桉为「龙藏经」第八函之上、下经板。清康熙皇帝为圆祖母孝庄太皇太后的心愿，派人以泥金誊写，製作此部「龙藏经」，总计108函。每函上、下经板均以五层五色经帘保护;掀起经帘，上经板中央以梵、藏文刻写「顶礼佛、顶礼法、顶礼僧，顶礼三宝」，两旁彩绘诸佛菩萨，下经板则彩绘5尊护法。全帙五万多叶经文，泥金成色饱满，上、下经板彩绘尊像总计756尊，镶嵌各种珠宝，极富皇家气派。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	本组邮票由大观视觉顾问股份有限公司设计，新西兰南方印刷有限公司以彩色平版印製。配合邮票发行， 特印製首日封、贴票卡、护票卡、活页集邮卡及原图明信片各一批，于民国104年12月8日开始发售; 另製作预销首日戳低值封 、套票封、 小全张封 、预销原图明信片及专册，于12月10日邮票发行当天出售 。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
