{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}近几年新邮市价“猛涨”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 02:19:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	近期邮币卡交易所的数量大幅增加，新成立的邮币卡交易所首要的工作便是在卢工邮市等实体市场和媒体做好宣传工作，使邮币卡市场的经营者、投资者、集藏爱好者和市民能参与其中。有人认为，如果邮币卡交易所&ldquo;电子盘&rdquo;各品种不再像股市的股票那样炒作，而其价格根植在实体邮币卡市场上，那样邮币卡交易所就有了立足之地。但目前邮币卡&ldquo;电子盘&rdquo;还是以炒作为主，虽然邮币卡交易所数量越多，但是大多数品种的价格已脱离了实体市场，如果&ldquo;电子盘&rdquo;品种的价格高于实体邮币卡市场同类品种价格很多倍，毕竟是一个潜在的危机，只有与实体邮币卡市场价格接轨，邮币卡交易所才能发展得更好。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="padding: 0px; margin: 0px; text-indent: 2em;">10月上旬，邮政部门发行了&ldquo;新疆成立60周年&rdquo;、&ldquo;天津大学120周年&rdquo;和&ldquo;故宫博物院&rdquo;3套邮票，从11月至年底的邮票发行计划看，新邮发行密度大幅降低，仅有&ldquo;诗词歌赋&rdquo;和&ldquo;喷气式支线客机交付运营&rdquo;两套邮票。全年邮票发行接近尾声，大家近两个月尽可养足精力，迎接明年初第四轮生肖邮票&ldquo;丙申猴&rdquo;的面世。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<span style="padding: 0px; margin: 0px; text-indent: 2em;"><img alt="" src="/uploads/allimg/c161124/14O95J5Z4220-13402.jpg" style="width: 261px; height: 220px;" /></span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="padding: 0px; margin: 0px; text-indent: 2em;">与9月初市价相比，近期上海卢工邮市大多数邮品价格没有明显变化，但令人较为欣慰的是，自&ldquo;故宫博物院&rdquo;邮票上市后，新邮上市后就下跌之势有所改观。由于邮市中近几年发行的邮票大版票、小版张和小型张都已经涨幅很大，受其带动，近几年发行的单套邮票也出现了一波看似不错的行情，&ldquo;中央党校&rdquo;邮票价格短时间内出现翻番，现价已达13元，&ldquo;黄埔军校90周年&rdquo;邮票价格也从4元上涨至7元，&ldquo;大闹天宫&rdquo;邮票为6元，&ldquo;黄梅戏&rdquo;邮票为5元，&ldquo;红楼梦（1）&rdquo;邮票为6元，&ldquo;浴马图&rdquo;邮票为13元，&ldquo;诸葛亮&rdquo;邮票为8元，&ldquo;中法建交50周年&rdquo;邮票为8元，前两年邮票出现的明显上涨也使今年发行的部分新邮市价回升，有的已跌破面值的邮票开始脱离打折圈，如&ldquo;遵义会议80周年&rdquo;邮票为2.9元，&ldquo;鸳鸯&rdquo;邮票为3.5元，&ldquo;环境日&rdquo;邮票为1.9元，&ldquo;人工胰岛素&rdquo;邮票为2.1元，&ldquo;钱塘江大潮&rdquo;邮票为3.4元，&ldquo;天津大学120周年&rdquo;邮票为2.8元，&ldquo;西游记（1）&rdquo;邮票为6元；此外，&ldquo;抗战胜利70周年&rdquo;、&ldquo;故宫博物院&rdquo;等邮票套票现基本已和面值持平，并有继续向好的趋势；&ldquo;新疆60周年&rdquo;和&ldquo;西藏50周年&rdquo;等邮票虽仍在面值8折左右，但也出现了一些转机。临近年底，邮人预料2015年邮票年册上市后将成为热销邮品，但近两年邮票市价上涨幅度之大仍然出乎多数人的意外。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="padding: 0px; margin: 0px; text-indent: 2em;">由于很多编年小型张一年来均出现了市价翻番走势，10月以来，已沉寂两年多的JT小型张中的部分品种异军突起，成交量有所放大，市场内外介入的资金明显增多，如&ldquo;白鹤&rdquo;和&ldquo;熊猫&rdquo;小型张9月的价格分别仅为40元和20元，明显低于很多发行量较大的编年小型张，近一个月来迅速上涨，目前&ldquo;白鹤&rdquo;和&ldquo;熊猫&rdquo;小型张最高价已分别上涨至 150元和45元，&ldquo;辽代彩塑&rdquo;和&ldquo;益鸟&rdquo;小型张也分别从9月的220元和170元涨到450元和250元，其他1983年至1991年发行的小型张价格也平均上涨了一倍左右。其中涨幅靠前的&ldquo;名楼&rdquo;、&ldquo;兰花&rdquo;、&ldquo;避暑山庄&rdquo;和&ldquo;西湖&rdquo;小型张，现价已分别为100元、90元、50元和45元。这次部分JT小型张的上涨行情是属于投资性的还是炒作性的，目前尚难下定论，但从长期投资价值来看，这些已发行了20多年的邮品也到了发挥其市场潜力的时候了。</span></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	<span style="padding: 0px; margin: 0px; text-indent: 2em;">&ldquo;抗战胜利70周年&rdquo;普通纪念币上市之日，散币的最高成交价为10元，随后一直维持在7元至8元。纪念币的收藏形势虽然越来越被人们看好，集藏者和市民兑换后作为纪念品或少量收藏无可厚非，但从投资的角度看，刚上市就大量高价买进发行量达5亿枚的新币，投资者需要很大的胆量，还是谨慎投资为好。10月29日，全国各大银行所属部分营业网点再次兑换&ldquo;抗战胜利70周年&rdquo;普通纪念币，近日市场价格逐渐回落，目前散币成交价在3.5元至4.5元之间。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95J5Z4220-13402_lit.jpg{/dede:field}
