<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016D046号《防止大气污染》藏品停牌的公告",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",232,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-11-10 15:27:07 &nbsp",284,349);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:<br />\r\n&nbsp; &nbsp; &nbsp;&nbsp;<img alt=\"\" src=\"/uploads/allimg/c161123/14OX61333YP-46093.jpg\" style=\"width: 646px; height: 131px;\" /><br />\r\n&nbsp; &nbsp; &nbsp; 根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年11月11日09时30分起停牌，挂牌藏品《防止大气污染》暂停交易两天，于2016年11月14日09时30分起复牌交易。<br />\r\n&nbsp; &nbsp; &nbsp;<br />\r\n&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n&nbsp;&nbsp; &nbsp; &nbsp;特此公告！</span><br />\r\n<br />\r\n<div style=\"text-align: right;\">\r\n	<span style=\"font-size:16px;\">&nbsp;<br />\r\n	宁夏西邮文化艺术品交易中心有限公司<br />\r\n	二零一六年十一月十日</span>",351,1287);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX61333YP-46093_lit.jpg",1289,1377);
$z[7][4]['name']="litpic";

?>