{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D046号《防止大气污染》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-10 15:27:07 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;)挂牌藏品:<br />
&nbsp; &nbsp; &nbsp;&nbsp;<img alt="" src="/uploads/allimg/c161123/14OX61333YP-46093.jpg" style="width: 646px; height: 131px;" /><br />
&nbsp; &nbsp; &nbsp; 根据《宁夏西邮商品发售交易规则（暂行）》中第四节第八十二条制度规定，自2016年11月11日09时30分起停牌，挂牌藏品《防止大气污染》暂停交易两天，于2016年11月14日09时30分起复牌交易。<br />
&nbsp; &nbsp; &nbsp;<br />
&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />
&nbsp;&nbsp; &nbsp; &nbsp;特此公告！</span><br />
<br />
<div style="text-align: right;">
	<span style="font-size:16px;">&nbsp;<br />
	宁夏西邮文化艺术品交易中心有限公司<br />
	二零一六年十一月十日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX61333YP-46093_lit.jpg{/dede:field}
