<?php
$z[0]=Array("noteinfo","",0,229);
$z[0][4]['notename']="中心动态";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.81xiyou.com/a/xiyouzixun/zhongxindongtai/2016/1011/84.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"list\">{/dede:areastart}\r\n    {dede:areaend}</ul>{/dede:areaend}\r\n",231,679);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.81xiyou.com/a/xiyouzixun/zhongxindongtai/list_9_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="4";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>