<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","西邮所:依法合规经营 严禁不当行为管控各项风险_西邮所（官网）-宁夏西邮艺术品交易中心",89,248);
$z[2][4]['name']="title";
$z[3]=Array("field","",250,289);
$z[3][4]['name']="writer";
$z[4]=Array("field","",291,330);
$z[4][4]['name']="source";
$z[5]=Array("field","",332,369);
$z[5][4]['name']="body";
$z[6]=Array("field","",371,411);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",413,452);
$z[7][4]['name']="litpic";

?>