<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于2016S010《十二届人大政协封》藏品申购公告",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",232,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-09-30 14:06:00 &nbsp",284,349);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种十二届人大政协会议纪念封（以下简称&ldquo;十二届人大政协会议&rdquo;）进行定价发行申购。<br style=\"padding: 0px; margin: 0px;\" />\r\n&nbsp; &nbsp; &nbsp; &nbsp;本次申购比例为：市值申购占可申购总量的0%，资金申购占可申购总量的100%。持仓市值参考为申购日结算后的实际市值。<br style=\"padding: 0px; margin: 0px;\" />\r\n具体事项公告如下：<br style=\"padding: 0px; margin: 0px;\" />\r\n一、申购藏品信息</span>\r\n<div style=\"text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161124/14O95DX0N0-22425.jpg\" style=\"width: 690px; height: 182px;\" />",351,1363);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O95DX0N0-22425_lit.jpg",1365,1452);
$z[7][4]['name']="litpic";

?>