{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016S010《十二届人大政协封》藏品申购公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-09-30 14:06:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，面向所有交易会员对挂牌上市交易品种十二届人大政协会议纪念封（以下简称&ldquo;十二届人大政协会议&rdquo;）进行定价发行申购。<br style="padding: 0px; margin: 0px;" />
&nbsp; &nbsp; &nbsp; &nbsp;本次申购比例为：市值申购占可申购总量的0%，资金申购占可申购总量的100%。持仓市值参考为申购日结算后的实际市值。<br style="padding: 0px; margin: 0px;" />
具体事项公告如下：<br style="padding: 0px; margin: 0px;" />
一、申购藏品信息</span>
<div style="text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95DX0N0-22425.jpg" style="width: 690px; height: 182px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95DX0N0-22425_lit.jpg{/dede:field}
