<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于 《澳门中国书法》小版票藏品托管入库公告",89,191);
$z[2][4]['name']="title";
$z[3]=Array("field","",193,232);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",234,284);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-08-19 15:15:00 &nbsp",286,351);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，小版票2000-3-23-S004 &ldquo;澳门中国书法&rdquo;（以下简称&ldquo;澳门中国书法&rdquo;）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: center;\">\r\n	<span style=\"padding: 0px; margin: 0px;\"><strong style=\"padding: 0px; margin: 0px;\">入库藏品清单</strong></span>",353,1143);
$z[6][4]['name']="body";
$z[7]=Array("field","",1145,1184);
$z[7][4]['name']="litpic";

?>