{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于2016D050号《北京民居》藏品停牌的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-11-12 15:38:29 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size: 16px">&nbsp; 宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌藏品：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img alt="" src="/uploads/allimg/c161123/14OX613W04P-35961.png" style="width: 647px; height: 129px" /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2016年11月14日09时30分起停牌，挂牌藏品《普23北京民居》暂停交易一天，于2016年11月15日09时30分起复牌交易。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 特此公告！ </span>
<div style="text-align: right">
	<span style="font-size: 16px">宁夏西邮文化艺术品交易中心有限公司<br />
	二零一六年十一月十二日</span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX613W04P-35961_lit.png{/dede:field}
