<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","2016D038号《黄果树瀑布》藏品的停牌公告",89,180);
$z[2][4]['name']="title";
$z[3]=Array("field","",182,221);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",223,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-31 17:29:23 &nbsp",275,340);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）挂牌商品：<br />\r\n&nbsp; &nbsp; &nbsp;&nbsp;<img alt=\"\" src=\"/uploads/allimg/c161123/14OX611562N0-323I.jpg\" style=\"width: 592px; height: 103px;\" /><br />\r\n&nbsp; &nbsp; &nbsp; 根据《宁夏西邮文化艺术品交易中心风险控制管理办法》中第五章第十五条涨跌停板制度规定，属价格异常波动：<br />\r\n&nbsp; &nbsp; &nbsp; 自2016年11月1日09时30分起，挂牌藏品《普22黄果树瀑布》暂停交易一小时，于2016年11月1日10时30分起恢复交易。&nbsp;<br />\r\n&nbsp;<br />\r\n&nbsp; &nbsp; &nbsp; 交易平台提醒投资者谨慎投资，注意风险。<br />\r\n&nbsp; &nbsp; &nbsp; 特此公告！<br />\r\n&nbsp;</span>\r\n<div style=\"text-align: right;\">\r\n	<span style=\"font-size:16px;\">宁夏西邮文化艺术品交易中心有限公司<br />\r\n	二零一六年十月三十一日</span>",342,1331);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX611562N0-323I_lit.jpg",1333,1421);
$z[7][4]['name']="litpic";

?>