{dede:noteinfo notename="交易品种-邮票介绍" channelid="1" macthtype="string"
    refurl="http://www.81xiyou.com/a/jiaoyiguize/jiaoyizhidu/2016/1007/6.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.81xiyou.com/a/jiaoyipinzhong/youpiaojieshao/list_26_(*).html"
startid="1" endid="3" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<section class="newBox">{/dede:areastart}
    {dede:areaend}</section>{/dede:areaend}
{/dede:listrule}
