{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于西邮所托管仓库的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-14 12:12:00 &nbsp{/dede:field}
{dede:field name='body'}<div style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px; text-align: justify;">
	<br />
	<span style="padding: 0px; margin: 0px;">尊敬的会员：<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），研究决定，现向各交易中心做出以下声明：<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;西邮所是宁夏回族自治区文化厅备案，由宁夏回族自治区省级人民政府主管部门（宁文函[2016]31号）批准成立的一家综合性文化艺术品交易中心。目前宁夏和武汉都设立了托管仓库，宁夏设立标准仓库、武汉仓库已经验收合格。<br style="padding: 0px; margin: 0px;" />
	&nbsp;<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;感谢您对交易中心的支持！<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请各位会员知晓，本公告解释权归本中心所有，未尽事宜本中心有权修改与补充。<br style="padding: 0px; margin: 0px;" />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;特此公告！</span><br style="padding: 0px; margin: 0px;" />
	&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
