{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}巨量发行遭遇升值尴尬 ＂猴币＂高开低走人气下{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-28 23:33:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	中国宁波网讯 随着航天钞开放回笼消息的传开，更多市民开始关注一度深夜抢先预约，又第一时间赶往兑换的猴币行情。不少收藏者开始发问：纪念币还值得收藏吗？收藏价值能否持续&hellip;&hellip;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;航天钞市价回落了，我手中的5枚猴年纪念币不知行情如何？是不是也不值钱了？&rdquo;市民张小姐昨天来到银行打探。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	据张小姐称，早在1月6日，农行开放预约首日凌晨，她便熬夜在网上成功预约到了5枚猴年纪念币。&ldquo;当时很多朋友还没能预约到呢。&rdquo;她说。而随着第一批猴币兑换日期的到来，这枚10元面值的猴年普通纪念币一度被炒到50多元，更让她觉得自己尤其幸运。&ldquo;事实上，那天刚从银行拿到猴币，就有人愿意出双倍的价钱悉数回收。&rdquo;然而，面对春节以后，同期发行的航天纪念钞跌回面值的尴尬，张小姐又开始质疑猴币的涨跌行情。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	据悉，去年11月26日，面值100元的中国航天纪念钞正式发行，在随后的3天左右时间，在宁波收藏市场价格猛涨，最高炒到了160元以上。不过，随着大多数市民相继换购到航天钞，其市价很快又出现直线下跌。截至本月，已然跌到了102元左右，接近面值。难道纪念币的投资收藏价值已不如从前了？有市民开始困惑。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	有资深钱币收藏爱好者分析，纪念货币的升值空间跟发行量有紧密的关系。发行量多达3亿张的航天纪念钞身价的&ldquo;暴涨暴跌&rdquo;难免引起了市民对发行量更大的猴年纪念币收藏价值的质疑。记者了解，猴年纪念币全国发行量达到5亿枚。而此前，羊年的生肖贺岁纪念币的发行量仅8000万枚。其收藏价值可见一斑。记者昨天从范宅等收藏市场了解到。眼下，面值为10元的猴币市价已从近60元的高点跌至20余元，收藏界人士表示，随着第二批猴币兑换日期的到来，猴年纪念币的价格很有可能再次回落。而面对猴币的&ldquo;巨量发行&rdquo;，2015年生肖羊币则变得更加稀有，出现了身价暴涨的大好行情。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;除了发行量，纪念币的市场价格受市场行情影响又非常大，换句话说，随着收藏者追捧热情的变化，其价格涨得快，回落得也快，因此，市民可以适当介入收藏，但不要盲目跟风，谨慎追高便好。&rdquo;钱币收藏专家陈海永称。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
