{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮资明信片“湖北风光A”（ 002003）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div class="content_wrap_1" style="padding: 0px; margin: 0px auto; width: 1003px; overflow: hidden; color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma;">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="padding: 0px; margin: 0px; color: rgb(105, 105, 105);"><span style="padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">邮资明信片&ldquo;湖北风光A&rdquo;(002003)</strong></span></span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">交易参数：<br style="padding: 0px; margin: 0px;" />
															【交易代码】：002003<br style="padding: 0px; margin: 0px;" />
															【首日挂牌指导价】：25元/枚<br style="padding: 0px; margin: 0px;" />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br style="padding: 0px; margin: 0px;" />
															【单笔最大委托量】：100000枚<br style="padding: 0px; margin: 0px;" />
															【最小变动价位】： 0.01元<br style="padding: 0px; margin: 0px;" />
															【最小提货数量】: 1枚<br style="padding: 0px; margin: 0px;" />
															【市场流通量】：100000枚<br style="padding: 0px; margin: 0px;" />
															【备注】：&nbsp;以整本自提<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															藏品信息：<br style="padding: 0px; margin: 0px;" />
															【藏品名称】：湖北风光邮资片A组<br style="padding: 0px; margin: 0px;" />
															【邮票类型】 : 邮资明信片<br style="padding: 0px; margin: 0px;" />
															【志 &nbsp; &nbsp; &nbsp;号】 : YP16＜片＞<br style="padding: 0px; margin: 0px;" />
															【面 &nbsp; &nbsp; &nbsp;值】 : 0.15元&times;10</span><br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">【发行日期】：1994年11月4日<br style="padding: 0px; margin: 0px;" />
															【发 &nbsp;行 量】：55万套<br style="padding: 0px; margin: 0px;" />
															【大全套数】 : 10枚/套&nbsp;<br style="padding: 0px; margin: 0px;" />
															【藏品规格】：153&times;114毫米<br style="padding: 0px; margin: 0px;" />
															【整张枚数】：1枚<br style="padding: 0px; margin: 0px;" />
															【版 &nbsp; &nbsp; &nbsp;别】：胶版<br style="padding: 0px; margin: 0px;" />
															【发行机构】：中国人民共和国邮电部发行<br style="padding: 0px; margin: 0px;" />
															【印 制 &nbsp;厂】：深圳当纳利旭日印刷有限公司</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<span style="padding: 0px; margin: 0px;">藏品介绍：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;1994年11月4日邮电部发行yp16《湖北风光》邮资明信片，由任国思设计，深圳当纳利旭印刷有限公司印刷，摄影者：黄克勤、李福堂、张晓军、李靖、党国光、黄河、任国思，湖北风光片A组发行量55万套，里面相关的长江非常震撼人心！湖北历史沉淀深厚是个历史古迹多多的省份，该风光邮资片内的&ldquo;荆州古城&rdquo;&ldquo;古隆中&rdquo;等也是邮迷喜爱的内容，现在收藏的价值取向也是重&ldquo;钱途&rdquo;，轻文化欣赏！<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															风险分析：<br style="padding: 0px; margin: 0px;" />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br style="padding: 0px; margin: 0px;" />
															特此提示</span><br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															<br style="padding: 0px; margin: 0px;" />
															&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
