{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《映日荷花》邮资明信片藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-17 16:07:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2005乙酉年》邮资明信片&ldquo;映日荷花&rdquo;（以下简称&ldquo;映日荷花&rdquo;）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<strong style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">入库藏品清单<br />
	<img alt="" src="/uploads/allimg/c161124/14O95541b0330-42B8.jpg" style="width: 628px; height: 155px;" /></strong>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95541b0330-42B8_lit.jpg{/dede:field}
