<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","关于《西游记》小型张藏品托管入库公告",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",224,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-06-10 15:28:00 &nbsp",276,341);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2015乙未年》特种邮票《中国古典文学名著&mdash;&mdash;&lt;西游记&gt;（一）》（以下简称西游记）藏品已完成托管入库流程，详情见下表：</span>\r\n<div style=\"text-align: center;\">\r\n	<span style=\"padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;\"><img alt=\"\" src=\"/uploads/allimg/c161124/14O9553M45K0-1C41.jpg\" style=\"width: 589px; height: 203px;\" /></span>",343,1161);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161124/14O9553M45K0-1C41_lit.jpg",1163,1251);
$z[7][4]['name']="litpic";

?>