{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于《西游记》小型张藏品托管入库公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-10 15:28:00 &nbsp{/dede:field}
{dede:field name='body'}<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）会员申请，中心专家委员会评估审核，《2015乙未年》特种邮票《中国古典文学名著&mdash;&mdash;&lt;西游记&gt;（一）》（以下简称西游记）藏品已完成托管入库流程，详情见下表：</span>
<div style="text-align: center;">
	<span style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 28px;"><img alt="" src="/uploads/allimg/c161124/14O9553M45K0-1C41.jpg" style="width: 589px; height: 203px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O9553M45K0-1C41_lit.jpg{/dede:field}
