<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","特种邮票“长江三峡”（ 600015）",89,170);
$z[2][4]['name']="title";
$z[3]=Array("field","",172,211);
$z[3][4]['name']="writer";
$z[4]=Array("field","",213,252);
$z[4][4]['name']="source";
$z[5]=Array("field","",254,294);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div>\r\n	&nbsp;",296,347);
$z[6][4]['name']="body";
$z[7]=Array("field","",349,388);
$z[7][4]['name']="litpic";

?>