{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邮储银行发行首款邮票主题生肖信用卡{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-25 23:37:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											近期，邮储银行隆重推出别具特色的生肖邮票主题信用卡，该类卡产品集信用卡金融功能与集邮相关权益于一体，紧跟生肖邮票的发行自成系列逐年推出，是收藏爱好者、集邮爱好者的首选。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											2016年首发卡种为《丙申年》信用卡生肖卡，从外观上看，丙申年生肖卡采用第四轮生肖邮票&ldquo;猴票&rdquo;为卡面，图案中灵猴攀爬树枝手托寿桃，笑容可掬，生动活泼。灵猴攀枝托桃，寓意猴年蒸蒸日上、福寿吉祥，传递新春贺喜的美好祝愿。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											该款生肖卡是个人标准银联金卡信用卡，属磁条芯片复合卡，产品有限期为6年。为给客户提供优质的产品功能和权益服务，该卡具备包括免费交易提醒、双倍积分礼遇、积分永久有效、尊享VIP服务、失卡保障服务等。年费方面执行优惠政策，即首年免年费、消费满6笔即可免次年年费。</p>
										<p style="padding: 0px; margin: 0px; text-indent: 2em;">
											此外，信用卡生肖卡具备邮储银行金卡级IC信用卡的全部功能，包括消费、取现、分期、免息期等基本信用卡金融功能，还具备电子现金功能，支持脱机小额支付、圈存充值与查询等IC卡金融服务。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
