{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}特种邮票“桃花”（ 600016）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<div>
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="color: rgb(102, 102, 102); font-family: Verdana, Arial, Tahoma; padding: 0px; margin: 0px;" width="1003">
		<tbody style="padding: 0px; margin: 0px;">
			<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
				<td style="padding: 0px; margin: 0px;" width="220">
					<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
						<tbody style="padding: 0px; margin: 0px;">
							<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
								<td style="padding: 0px; margin: 0px;">
									<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
										<tbody style="padding: 0px; margin: 0px;">
											<tr style="padding: 0px; margin: 0px;">
												<td style="padding: 0px; margin: 0px;">
													<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
														<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
															<br />
															<span style="color:#696969;"><strong>特种邮票&ldquo;桃花&rdquo;（ 600016）</strong></span><br />
															交易参数：<br />
															【交易代码】：600016<br />
															【首日挂牌指导价】：7.8元/枚<br />
															【涨跌幅度】: &plusmn;10%(上市首日&plusmn;30%)<br />
															【单笔最大委托量】：310000枚<br />
															【最小变动价位】： 0.01元<br />
															【最小提货数量】: 12枚<br />
															【市场流通量】：310000枚<br />
															【备注】：&nbsp;以整套自提<br />
															&nbsp;<br />
															藏品信息：<br />
															【藏品名称】：2013-6《桃花》特种邮票小版张<br />
															【藏品志号】：2013-6<br />
															【发行日期】：2013年3月16日<br />
															【图案面值】<br />
															（12-1）T 白碧桃&nbsp; 0.80元<br />
															（12-2）T 单粉&nbsp; &nbsp; 0.80元<br />
															（12-3）T 品霞 &nbsp;&nbsp;&nbsp;1.20元<br />
															（12-4）T 紫叶桃&nbsp; 1.20元<br />
															（12-5）T 瑕玉寿星1.20元<br />
															（12-6）T 碧桃&nbsp;&nbsp;&nbsp; 1.20元<br />
															（12-7）T 五宝桃　1.20元<br />
															（12-8）T 照手红　1.20元<br />
															（12-9）T 绿萼垂枝1.20元<br />
															（12-10）T 二色桃 1.20元<br />
															（12-11）T 菊花桃 1.20元<br />
															（12-12）T 绯桃　 1.50元<br />
															【全套枚数】：12枚<br />
															【材 &nbsp; &nbsp; &nbsp; 质】 : 纸质<br />
															【邮票规格】：33mm&times;33mm<br />
															【整张枚数】：版式一 ：16枚（一、二图各8枚/张，三、四图各8枚/张，五、六图各8枚/张，七、八图各8枚/张，九、十图各8枚/张，十 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;一、十二图各8枚/张）&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br />
															&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;版式二 ：12枚（一、二、三、四、五、六图各2枚/张，七、八、九、十、十一、十二图各2枚/张）<br />
															【整张规格】：版式一160&times;180毫米，版式二140&times;180毫米&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
															【齿孔度数】：13.5&times;13度<br />
															【版 &nbsp; &nbsp; &nbsp; 别】：影写（香味油墨）<br />
															【防伪方式】：防伪纸张、&nbsp;防伪油墨、异形齿孔、荧光喷码<br />
															【设 计 &nbsp;者】：郝旭东、李庆发<br />
															【责任编辑】：陈宜思<br />
															【印 &nbsp;制 &nbsp;厂】：北京邮票厂<br />
															<br style="padding: 0px; margin: 0px;" />
															藏品介绍：<br />
															&nbsp; &nbsp; &nbsp; &nbsp;这套《桃花（T）原版》特种邮票，1套共12枚，面值总计13.9元，分80分、1.20元、1.50元三种面值，由郝旭东、李庆发设计，版别为影写（香味油墨），采用了防伪纸张，防伪油墨，异形齿孔，荧光喷码的防伪技术。像这种1套12枚的大全套邮票样式，中国邮政只发行过10套，其中很多都成为了经典。此次的《桃花（T）原版》特种邮票是中国邮政继发行梅花、玉兰花、杜鹃花等系列花卉邮票之后枚数最多的一次，还未发行就受邮迷们的关注、喜爱与追捧。桃花，即桃树盛开的花朵，属蔷薇科植物。叶椭圆状披针形，核果近球形，主要分果桃和花桃两大类。桃花原产于中国中部、北部，现已在世界温带国家及地区广泛种植，其繁殖以嫁接为主。桃花可制成桃花丸、桃花茶等食品。其具有很高的观赏价值，是文学创作的常用素材。此外，桃花中元素有疏通经络、滋润皮肤的药用价值。其花语及代表意义为：爱情的俘虏。每年3月份，各地会以桃花为媒，举办桃花节盛会。此次《桃花》邮票内容拟为邮票表现内容包括单粉、白碧桃、二色桃、菊花桃、碧桃、绯桃、五宝桃、绿萼垂枝、照手姬、瑕玉寿星、品霞、紫叶桃等。为配合邮票发行，中国集邮总公司特别推出多款《桃花》系列邮品。<br />
															<br />
															风险分析：<br />
															&nbsp; &nbsp; &nbsp; &nbsp;各位会员在购买本藏品时可能会面临一定风险。由于我国宏观经济形势的变化，国家相关法律法规及政策的变动以及各类不可抗力等因素，可能存在影响本挂牌藏品价格波动或日常交易的情形，使得投资收益存在不确定性。因此在交易过程中，投资者应确保对各种可能遇到的风险因素有客观的认识。请广大会员根据自身的风险承受能力理性投资。<br />
															特此提示{/dede:field}
{dede:field name='litpic'}{/dede:field}
