{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2016Z011《中国古典诗词－木兰辞》申购中签公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-29 10:12:06 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）于2016年10月&nbsp;28日对挂牌藏品中国古典诗词－木兰辞面向所有投资人会员进行定价申购发行，具体事项公告如下：</span>
<div style="text-align: center;">
	<span style="font-size:16px;"><img alt="" src="/uploads/allimg/c161123/14OX6109632P-45043.jpg" style="width: 673px; height: 247px;" /></span>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX6109632P-45043_lit.jpg{/dede:field}
