{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于客服热线异常情况的说明{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-06-15 17:55:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px; font-family: arial, helvetica, sans-serif;">尊敬的客户：</span><br style="padding: 0px; margin: 0px;" />
										<br style="padding: 0px; margin: 0px;" />
										<div style="padding: 0px; margin: 0px;">
											<span style="padding: 0px; margin: 0px; font-family: arial, helvetica, sans-serif;"><span style="padding: 0px; margin: 0px;">&nbsp; &nbsp; &nbsp; &nbsp;由于工信部近日下发通知，全国全部实行所有电话进行实名制，为了响应国家号召实行反恐怖主义法。</span><span style="padding: 0px; margin: 0px;">导致近期我公司<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">&ldquo;4000-738-817&rdquo;</strong></span>&nbsp;客户热线</span><span style="padding: 0px; margin: 0px;">出现异&nbsp;</span><span style="padding: 0px; margin: 0px;">常，目前我公司已紧急联系相关人员，尽快恢复正常。</span><br style="padding: 0px; margin: 0px;" />
											<br style="padding: 0px; margin: 0px;" />
											<span style="padding: 0px; margin: 0px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请各位客户知晓，由此给您造成的不便我们深表歉意！</span></span><br style="padding: 0px; margin: 0px;" />
											<br style="padding: 0px; margin: 0px;" />
											&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
