<?php
$z[0]=Array("addurls","http://www.81xiyou.com/a/xiyouzixun/zhongxindongtai/list_9_(*).html",6,102);
$z[1]=Array("batchrule","[(#)=>http://www.81xiyou.com/a/xiyouzixun/huiyuanhuodong/list_10_(*).html; (*)=1-2; typeid=>19]\r\n[(#)=>http://www.81xiyou.com/a/xiyouzixun/tuoguangonggao/list_11_(*).html; (*)=1-5; typeid=>20]\r\n",108,335);
$z[2]=Array("regxrule","",341,372);
$z[3]=Array("areastart","<ul class=\"list\">",378,428);
$z[4]=Array("areaend","</ul>",434,468);

?>