{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}英国推出彼得兔纪念币{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-03-31 23:16:00 &nbsp{/dede:field}
{dede:field name='body'}<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em; text-align: center;">
	<img alt="" src="/uploads/allimg/c161124/14O95GPX410-21a7.jpg" style="width: 550px; height: 331px;" /></p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	英国皇家铸币厂将首次把儿童文学中的角色印到硬币上，而这款硬币的主角就是儿童画家碧雅翠丝&middot;波特笔下爱偷东西的彼得兔。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	彼得兔穿着偷吃麦奎格先生花园的蔬菜被发现后弄丢的蓝色夹克，彩色的50便士特别版纪念币现在已经可以买到了。英国皇家铸币厂将彼得兔誉为&ldquo;波特笔下最知名的角色，儿童文学的瑰宝之一&rdquo;。今年晚些时候，铸币厂还将推出可以流通的非彩色版彼得兔硬币。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	为庆祝波特诞辰150周年，今年波特笔下还有三位角色将登上英国货币，届时硬币形象将由设计师艾玛&middot;诺布尔创作。诺布尔表示，&ldquo;有机会和这么著名和值得珍藏的文学角色一起工作真是太棒了&rdquo;。</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	&ldquo;我的设计将围绕碧雅翠丝&middot;波特的原版插图进行，因为这些插图实在是太可爱了，图中的角色也早已家喻户晓，&rdquo;诺布尔说，&ldquo;我觉得它们每一个单独拿出来都是经典，这样设计既适合彩色纪念版的硬币，也适合非彩色的流通款硬币。我真心希望大家会喜欢这套硬币。&rdquo;</p>
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, 宋体; font-size: 16px; line-height: 32px; text-indent: 2em;">
	《彼得兔的故事》于1902年由费德里克&middot;沃恩公司出版。这是碧雅翠丝&middot;波特出版的第一本故事书。书中主要讲述了彼得兔和三个姐姐的故事。三个姐姐分别名叫弗洛普茜、默普茜和棉球尾，她们都比彼得兔乖。此后，波特又接着创作了一系列深受喜爱的故事，从《松鼠坚果果的故事》一直到《傻鸭子杰米玛》。这些故事历经百年，依旧风靡至今。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161124/14O95GPX410-21a7_lit.jpg{/dede:field}
