{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}关于手机交易软件更新的通知{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-07-15 18:40:00 &nbsp{/dede:field}
{dede:field name='body'}<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="1003">
	<tbody style="padding: 0px; margin: 0px;">
		<tr align="left" style="padding: 0px; margin: 0px;" valign="top">
			<td style="padding: 0px; margin: 0px; color: rgb(102, 102, 102);">
				<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px; margin: 0px;" width="100%">
					<tbody style="padding: 0px; margin: 0px;">
						<tr style="padding: 0px; margin: 0px;">
							<td style="padding: 0px; margin: 0px;">
								<div class="neirong" style="padding: 0px; margin: 15px 0px 5px; float: left; height: auto; overflow: visible; color: rgb(51, 51, 51); font-size: 14px; min-height: 400px; line-height: 24px; clear: both; text-indent: 2em; font-family: arial, 宋体, sans-serif;">
									<div class="neirong_text" style="padding: 0px; margin: 0px auto; line-height: 32px; clear: both; font-size: 16px; font-family: 微软雅黑, 宋体;">
										<span style="padding: 0px; margin: 0px;">尊敬的会员：</span>
										<div style="padding: 0px; margin: 0px;">
											<span style="padding: 0px; margin: 0px;">&nbsp;宁夏西邮文化艺术品交易中心有限公司（以下简称&ldquo;西邮所&rdquo;），现手机交易软件最新版本已更新，如目前手机版本不能正常操作的请即时登录官网，<span style="padding: 0px; margin: 0px; color: rgb(255, 0, 0);"><strong style="padding: 0px; margin: 0px;">下载中心&mdash;软件下载&mdash;手机交易软件&mdash;&mdash;二维码下载进行扫描，并且安装。</strong></span></span>{/dede:field}
{dede:field name='litpic'}{/dede:field}
