<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","《桃花》藏品上市的公告",89,160);
$z[2][4]['name']="title";
$z[3]=Array("field","",162,201);
$z[3][4]['name']="writer";
$z[4]=Array("field","未知&nbsp",203,253);
$z[4][4]['name']="source";
$z[5]=Array("field","2016-10-25 17:21:17 &nbsp",255,320);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"font-size:16px;\">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将2013-6特种邮票&nbsp;&ldquo;桃花&rdquo;（以下简称&ldquo;桃花&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：<br />\r\n<strong>一、&nbsp;上市商品信息</strong></span>\r\n<div style=\"text-align: center;\">\r\n	<img alt=\"\" src=\"/uploads/allimg/c161123/14OX610534b0-1N57.jpg\" style=\"width: 581px; height: 494px;\" />",322,934);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161123/14OX610534b0-1N57_lit.jpg",936,1024);
$z[7][4]['name']="litpic";

?>