{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《桃花》藏品上市的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}未知&nbsp{/dede:field}
{dede:field name='pubdate'}2016-10-25 17:21:17 &nbsp{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">经宁夏西邮文化艺术品交易中心（以下简称&ldquo;西邮所&rdquo;）邮币卡交易中心发行审核委员会审核通过，鉴定机构鉴定入库完毕，现决定将2013-6特种邮票&nbsp;&ldquo;桃花&rdquo;（以下简称&ldquo;桃花&rdquo;）藏品在本中心正式发行和上市交易，具体事项公告如下：<br />
<strong>一、&nbsp;上市商品信息</strong></span>
<div style="text-align: center;">
	<img alt="" src="/uploads/allimg/c161123/14OX610534b0-1N57.jpg" style="width: 581px; height: 494px;" />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161123/14OX610534b0-1N57_lit.jpg{/dede:field}
