<?php
$z[0]=Array("global","",93,125);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",214,238);
$z[1][4]['name']="cfg_phone";
$z[2]=Array("global","",525,557);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","(@me==\"\")? @me=\" class='active' \":@me=\"\";",832,923);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",933,960);
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("channel","\r\n                <li><a href=\"[field:typelink/]\"> [field:typename/] </a>\r\n                    <div class=\"border\" style=\"display: block;\"></div>\r\n                </li>\r\n            ",1071,1379);
$z[5][4]['row']="7";
$z[5][4]['type']="top";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[6]=Array("global","",1894,1926);
$z[6][4]['name']="cfg_templets_skin";

?>