<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",302,334);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",545,570);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("include","",1313,1348);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                <li class=\"\"><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"border borderL\"></div>\r\n                    <div class=\"border borderR\"></div>\r\n                </li>\r\n                ",1602,1872);
$z[5][4]['row']="9";
$z[6]=Array("field","",2112,2131);
$z[6][4]['name']="title";
$z[7]=Array("arclist","\r\n            <a href=\"[field:arcurl/]\" class=\"bigNew\">\r\n                <div class='imgs'>[field:image/]</div>\r\n                <div class=\"time\">\r\n                    <div class=\"date\">[field:pubdate function=strftime('%m-%d',@me)/]</div>\r\n                    <div class=\"year\">[field:pubdate function=strftime('%Y',@me)/]</div>\r\n                </div>\r\n                <div class=\"textBox\">\r\n                    <div class=\"tit\">[field:title/]</div>\r\n                    <div class=\"text\">[field:description function=\"cn_substr(@me,80)\"/]...</div>\r\n                    <div class=\"lookMore\">查看详情</div>\r\n                </div>\r\n            </a>\r\n        ",2321,3078);
$z[7][4]['flag']="h";
$z[7][4]['type']=".image";
$z[7][4]['imgwidth']="100%";
$z[7][4]['imgheight']="100%";
$z[7][4]['row']="1";
$z[8]=Array("arclist","\r\n            <li class=''>\r\n                <a href=\"[field:arcurl/]\">\r\n                    <div class=\"time\">\r\n                        <div class=\"date\">[field:pubdate function=strftime('%m-%d',@me)/]</div>\r\n                        <div class=\"year\">[field:pubdate function=strftime('%Y',@me)/]</div>\r\n                    </div>\r\n                    <div class=\"textBox\">\r\n                        <div class=\"tit\">[field:title/]</div>\r\n                        <div class=\"text\">[field:description function=\"cn_substr(@me,80)\"/]...</div>\r\n                    </div>\r\n                    <div class=\"arrow\"></div>\r\n                </a>\r\n            </li>\r\n            ",3153,3904);
$z[8][4]['titlelen']="60";
$z[8][4]['row']="99999";
$z[8][4]['tagid']="mynews";
$z[8][4]['pagesize']="8";
$z[9]=Array("arcpagelist","",4059,4093);
$z[9][4]['tagid']="mynews";
$z[10]=Array("include","",4203,4240);
$z[10][4]['filename']="footer.htm";
$z[11]=Array("include","",4279,4319);
$z[11][4]['filename']="footer-js.htm";

?>