<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",302,334);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",577,612);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n                <li><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"border borderL\"></div>\r\n                    <div class=\"border borderR\"></div>\r\n                </li>\r\n                ",866,1239);
$z[4][4]['row']="9";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("field","",1466,1485);
$z[5][4]['name']="title";
$z[6]=Array("list","\r\n            <li class=''>\r\n                <a href=\"[field:arcurl/]\">\r\n                    <div class=\"time\">\r\n                        <div class=\"date\">[field:pubdate function=strftime('%m-%d',@me)/]</div>\r\n                        <div class=\"year\">[field:pubdate function=strftime('%Y',@me)/]</div>\r\n                    </div>\r\n                    <div class=\"textBox\">\r\n                        <div class=\"tit\">[field:title function=\"cn_substr(@me,60)\"/]...</div>\r\n                        <div class=\"text\">[field:description function=\"cn_substr(@me,80)\"/]...</div>\r\n                    </div>\r\n                    <div class=\"btn\">查看详情</div>\r\n                </a>\r\n            </li>\r\n            ",1706,2454);
$z[6][4]['pagesize']="10";
$z[7]=Array("pagelist","",2610,2687);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",2779,2816);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("include","",2855,2895);
$z[9][4]['filename']="footer-js.htm";

?>