<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",302,334);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",577,612);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n                <li><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"border borderL\"></div>\r\n                    <div class=\"border borderR\"></div>\r\n                </li>\r\n                ",866,1239);
$z[4][4]['row']="9";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("field","",1479,1498);
$z[5][4]['name']="title";
$z[6]=Array("list","\r\n            <li class=''>\r\n                <a href=\"[field:arcurl/]\">\r\n                    <div class=\"time\">\r\n                        <div class=\"date\">[field:pubdate function=strftime('%m-%d',@me)/]</div>\r\n                        <div class=\"year\">[field:pubdate function=strftime('%Y',@me)/]</div>\r\n                    </div>\r\n                    <div class=\"textBox\">\r\n                        <div class=\"tit\">[field:title function=\"cn_substr(@me,40)\"/]...</div>\r\n                        <div class=\"text\">[field:description function=\"cn_substr(@me,80)\"/]...</div>\r\n                    </div>\r\n                    <div class=\"arrow\"></div>\r\n                </a>\r\n            </li>\r\n            ",2586,3323);
$z[6][4]['pagesize']="8";
$z[7]=Array("pagelist","",3479,3556);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",3648,3685);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("include","",3724,3764);
$z[9][4]['filename']="footer-js.htm";

?>